/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.tdmysql.v20211122.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeDBSBackupStatisticsResponse extends AbstractModel {

    /**
    * <p>Backup method statistics</p>
Note: This field may return null, indicating that no valid values can be obtained.
    */
    @SerializedName("BackupMethodStatistics")
    @Expose
    private BackupMethodStatisticsModel BackupMethodStatistics;

    /**
    * <p>Backup set statistics</p>
Note: This field may return null, indicating that no valid values can be obtained.
    */
    @SerializedName("BackupStatistics")
    @Expose
    private BackupStatisticsModel BackupStatistics;

    /**
    * <p>Backup statistics.</p>
Note: This field may return null, indicating that no valid values can be obtained.
    */
    @SerializedName("DataBackupStatistics")
    @Expose
    private DataBackupStatisticsModel DataBackupStatistics;

    /**
    * <p>Log backup statistics</p>
Note: This field may return null, indicating that no valid values can be obtained.
    */
    @SerializedName("LogBackupStatistics")
    @Expose
    private LogBackupStatisticsModel LogBackupStatistics;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get <p>Backup method statistics</p>
Note: This field may return null, indicating that no valid values can be obtained. 
     * @return BackupMethodStatistics <p>Backup method statistics</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public BackupMethodStatisticsModel getBackupMethodStatistics() {
        return this.BackupMethodStatistics;
    }

    /**
     * Set <p>Backup method statistics</p>
Note: This field may return null, indicating that no valid values can be obtained.
     * @param BackupMethodStatistics <p>Backup method statistics</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public void setBackupMethodStatistics(BackupMethodStatisticsModel BackupMethodStatistics) {
        this.BackupMethodStatistics = BackupMethodStatistics;
    }

    /**
     * Get <p>Backup set statistics</p>
Note: This field may return null, indicating that no valid values can be obtained. 
     * @return BackupStatistics <p>Backup set statistics</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public BackupStatisticsModel getBackupStatistics() {
        return this.BackupStatistics;
    }

    /**
     * Set <p>Backup set statistics</p>
Note: This field may return null, indicating that no valid values can be obtained.
     * @param BackupStatistics <p>Backup set statistics</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public void setBackupStatistics(BackupStatisticsModel BackupStatistics) {
        this.BackupStatistics = BackupStatistics;
    }

    /**
     * Get <p>Backup statistics.</p>
Note: This field may return null, indicating that no valid values can be obtained. 
     * @return DataBackupStatistics <p>Backup statistics.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public DataBackupStatisticsModel getDataBackupStatistics() {
        return this.DataBackupStatistics;
    }

    /**
     * Set <p>Backup statistics.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     * @param DataBackupStatistics <p>Backup statistics.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public void setDataBackupStatistics(DataBackupStatisticsModel DataBackupStatistics) {
        this.DataBackupStatistics = DataBackupStatistics;
    }

    /**
     * Get <p>Log backup statistics</p>
Note: This field may return null, indicating that no valid values can be obtained. 
     * @return LogBackupStatistics <p>Log backup statistics</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public LogBackupStatisticsModel getLogBackupStatistics() {
        return this.LogBackupStatistics;
    }

    /**
     * Set <p>Log backup statistics</p>
Note: This field may return null, indicating that no valid values can be obtained.
     * @param LogBackupStatistics <p>Log backup statistics</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public void setLogBackupStatistics(LogBackupStatisticsModel LogBackupStatistics) {
        this.LogBackupStatistics = LogBackupStatistics;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeDBSBackupStatisticsResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeDBSBackupStatisticsResponse(DescribeDBSBackupStatisticsResponse source) {
        if (source.BackupMethodStatistics != null) {
            this.BackupMethodStatistics = new BackupMethodStatisticsModel(source.BackupMethodStatistics);
        }
        if (source.BackupStatistics != null) {
            this.BackupStatistics = new BackupStatisticsModel(source.BackupStatistics);
        }
        if (source.DataBackupStatistics != null) {
            this.DataBackupStatistics = new DataBackupStatisticsModel(source.DataBackupStatistics);
        }
        if (source.LogBackupStatistics != null) {
            this.LogBackupStatistics = new LogBackupStatisticsModel(source.LogBackupStatistics);
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamObj(map, prefix + "BackupMethodStatistics.", this.BackupMethodStatistics);
        this.setParamObj(map, prefix + "BackupStatistics.", this.BackupStatistics);
        this.setParamObj(map, prefix + "DataBackupStatistics.", this.DataBackupStatistics);
        this.setParamObj(map, prefix + "LogBackupStatistics.", this.LogBackupStatistics);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

