/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.tdmysql.v20211122.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeInstanceDataReservedSpaceResponse extends AbstractModel {

    /**
    * <p>Actual reserved ratio (%, per node)</p>
    */
    @SerializedName("ReservedRate")
    @Expose
    private Float ReservedRate;

    /**
    * <p>Actual reserved space in GB (single node)</p><p>Unit: GB</p>
    */
    @SerializedName("ReservedSpaceGB")
    @Expose
    private Float ReservedSpaceGB;

    /**
    * <p>Available user space in GB (per node)</p><p>Unit: GB</p>
    */
    @SerializedName("UsableSpaceGB")
    @Expose
    private Float UsableSpaceGB;

    /**
    * <p>true=earlier version (&lt;21.6.4.0), value from the old parameter tdstore_enter_readonly_threshold; false=new version</p>
    */
    @SerializedName("IsLegacy")
    @Expose
    private Boolean IsLegacy;

    /**
    * <p>Kernel version number</p>
    */
    @SerializedName("KernelVersion")
    @Expose
    private String KernelVersion;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get <p>Actual reserved ratio (%, per node)</p> 
     * @return ReservedRate <p>Actual reserved ratio (%, per node)</p>
     */
    public Float getReservedRate() {
        return this.ReservedRate;
    }

    /**
     * Set <p>Actual reserved ratio (%, per node)</p>
     * @param ReservedRate <p>Actual reserved ratio (%, per node)</p>
     */
    public void setReservedRate(Float ReservedRate) {
        this.ReservedRate = ReservedRate;
    }

    /**
     * Get <p>Actual reserved space in GB (single node)</p><p>Unit: GB</p> 
     * @return ReservedSpaceGB <p>Actual reserved space in GB (single node)</p><p>Unit: GB</p>
     */
    public Float getReservedSpaceGB() {
        return this.ReservedSpaceGB;
    }

    /**
     * Set <p>Actual reserved space in GB (single node)</p><p>Unit: GB</p>
     * @param ReservedSpaceGB <p>Actual reserved space in GB (single node)</p><p>Unit: GB</p>
     */
    public void setReservedSpaceGB(Float ReservedSpaceGB) {
        this.ReservedSpaceGB = ReservedSpaceGB;
    }

    /**
     * Get <p>Available user space in GB (per node)</p><p>Unit: GB</p> 
     * @return UsableSpaceGB <p>Available user space in GB (per node)</p><p>Unit: GB</p>
     */
    public Float getUsableSpaceGB() {
        return this.UsableSpaceGB;
    }

    /**
     * Set <p>Available user space in GB (per node)</p><p>Unit: GB</p>
     * @param UsableSpaceGB <p>Available user space in GB (per node)</p><p>Unit: GB</p>
     */
    public void setUsableSpaceGB(Float UsableSpaceGB) {
        this.UsableSpaceGB = UsableSpaceGB;
    }

    /**
     * Get <p>true=earlier version (&lt;21.6.4.0), value from the old parameter tdstore_enter_readonly_threshold; false=new version</p> 
     * @return IsLegacy <p>true=earlier version (&lt;21.6.4.0), value from the old parameter tdstore_enter_readonly_threshold; false=new version</p>
     */
    public Boolean getIsLegacy() {
        return this.IsLegacy;
    }

    /**
     * Set <p>true=earlier version (&lt;21.6.4.0), value from the old parameter tdstore_enter_readonly_threshold; false=new version</p>
     * @param IsLegacy <p>true=earlier version (&lt;21.6.4.0), value from the old parameter tdstore_enter_readonly_threshold; false=new version</p>
     */
    public void setIsLegacy(Boolean IsLegacy) {
        this.IsLegacy = IsLegacy;
    }

    /**
     * Get <p>Kernel version number</p> 
     * @return KernelVersion <p>Kernel version number</p>
     */
    public String getKernelVersion() {
        return this.KernelVersion;
    }

    /**
     * Set <p>Kernel version number</p>
     * @param KernelVersion <p>Kernel version number</p>
     */
    public void setKernelVersion(String KernelVersion) {
        this.KernelVersion = KernelVersion;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeInstanceDataReservedSpaceResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeInstanceDataReservedSpaceResponse(DescribeInstanceDataReservedSpaceResponse source) {
        if (source.ReservedRate != null) {
            this.ReservedRate = new Float(source.ReservedRate);
        }
        if (source.ReservedSpaceGB != null) {
            this.ReservedSpaceGB = new Float(source.ReservedSpaceGB);
        }
        if (source.UsableSpaceGB != null) {
            this.UsableSpaceGB = new Float(source.UsableSpaceGB);
        }
        if (source.IsLegacy != null) {
            this.IsLegacy = new Boolean(source.IsLegacy);
        }
        if (source.KernelVersion != null) {
            this.KernelVersion = new String(source.KernelVersion);
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "ReservedRate", this.ReservedRate);
        this.setParamSimple(map, prefix + "ReservedSpaceGB", this.ReservedSpaceGB);
        this.setParamSimple(map, prefix + "UsableSpaceGB", this.UsableSpaceGB);
        this.setParamSimple(map, prefix + "IsLegacy", this.IsLegacy);
        this.setParamSimple(map, prefix + "KernelVersion", this.KernelVersion);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

