/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.tdmysql.v20211122.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeDBSAvailableRecoveryTimeResponse extends AbstractModel {

    /**
    * <P>End time</p>
Note: This field may return null, indicating that no valid values can be obtained.
    */
    @SerializedName("EndTime")
    @Expose
    private String EndTime;

    /**
    * <P>Recoverable time interval.</p>
Note: This field may return null, indicating that no valid values can be obtained.
    */
    @SerializedName("Intervals")
    @Expose
    private ArchiveLogInterval [] Intervals;

    /**
    * <P>Start time</p>
Note: This field may return null, indicating that no valid values can be obtained.
    */
    @SerializedName("StartTime")
    @Expose
    private String StartTime;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get <P>End time</p>
Note: This field may return null, indicating that no valid values can be obtained. 
     * @return EndTime <P>End time</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public String getEndTime() {
        return this.EndTime;
    }

    /**
     * Set <P>End time</p>
Note: This field may return null, indicating that no valid values can be obtained.
     * @param EndTime <P>End time</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public void setEndTime(String EndTime) {
        this.EndTime = EndTime;
    }

    /**
     * Get <P>Recoverable time interval.</p>
Note: This field may return null, indicating that no valid values can be obtained. 
     * @return Intervals <P>Recoverable time interval.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public ArchiveLogInterval [] getIntervals() {
        return this.Intervals;
    }

    /**
     * Set <P>Recoverable time interval.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     * @param Intervals <P>Recoverable time interval.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public void setIntervals(ArchiveLogInterval [] Intervals) {
        this.Intervals = Intervals;
    }

    /**
     * Get <P>Start time</p>
Note: This field may return null, indicating that no valid values can be obtained. 
     * @return StartTime <P>Start time</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public String getStartTime() {
        return this.StartTime;
    }

    /**
     * Set <P>Start time</p>
Note: This field may return null, indicating that no valid values can be obtained.
     * @param StartTime <P>Start time</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public void setStartTime(String StartTime) {
        this.StartTime = StartTime;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeDBSAvailableRecoveryTimeResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeDBSAvailableRecoveryTimeResponse(DescribeDBSAvailableRecoveryTimeResponse source) {
        if (source.EndTime != null) {
            this.EndTime = new String(source.EndTime);
        }
        if (source.Intervals != null) {
            this.Intervals = new ArchiveLogInterval[source.Intervals.length];
            for (int i = 0; i < source.Intervals.length; i++) {
                this.Intervals[i] = new ArchiveLogInterval(source.Intervals[i]);
            }
        }
        if (source.StartTime != null) {
            this.StartTime = new String(source.StartTime);
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "EndTime", this.EndTime);
        this.setParamArrayObj(map, prefix + "Intervals.", this.Intervals);
        this.setParamSimple(map, prefix + "StartTime", this.StartTime);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

