/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.cls.v20201016.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeKafkaConsumerGroupDetailResponse extends AbstractModel {

    /**
    * Logset id
    */
    @SerializedName("LogsetId")
    @Expose
    private String LogsetId;

    /**
    * Consumer group name
    */
    @SerializedName("Group")
    @Expose
    private String Group;

    /**
    * List of consumer group information
    */
    @SerializedName("PartitionInfos")
    @Expose
    private GroupPartitionInfo [] PartitionInfos;

    /**
    * Empty: The group has no members but has submitted offsets. All consumers have left but retained offsets.
Dead: No members in the group and no submitted offset. The group is deleted or has long-term inactivity.
Stable: Members in the group consume normally, and partition allocation is balanced. Normal operating status.
PreparingRebalance: The group is preparing to rebalance. A new member joins or an existing member leaves.
CompletingRebalance: The group is preparing to rebalance. New members join or existing members leave.
    */
    @SerializedName("State")
    @Expose
    private String State;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Logset id 
     * @return LogsetId Logset id
     */
    public String getLogsetId() {
        return this.LogsetId;
    }

    /**
     * Set Logset id
     * @param LogsetId Logset id
     */
    public void setLogsetId(String LogsetId) {
        this.LogsetId = LogsetId;
    }

    /**
     * Get Consumer group name 
     * @return Group Consumer group name
     */
    public String getGroup() {
        return this.Group;
    }

    /**
     * Set Consumer group name
     * @param Group Consumer group name
     */
    public void setGroup(String Group) {
        this.Group = Group;
    }

    /**
     * Get List of consumer group information 
     * @return PartitionInfos List of consumer group information
     */
    public GroupPartitionInfo [] getPartitionInfos() {
        return this.PartitionInfos;
    }

    /**
     * Set List of consumer group information
     * @param PartitionInfos List of consumer group information
     */
    public void setPartitionInfos(GroupPartitionInfo [] PartitionInfos) {
        this.PartitionInfos = PartitionInfos;
    }

    /**
     * Get Empty: The group has no members but has submitted offsets. All consumers have left but retained offsets.
Dead: No members in the group and no submitted offset. The group is deleted or has long-term inactivity.
Stable: Members in the group consume normally, and partition allocation is balanced. Normal operating status.
PreparingRebalance: The group is preparing to rebalance. A new member joins or an existing member leaves.
CompletingRebalance: The group is preparing to rebalance. New members join or existing members leave. 
     * @return State Empty: The group has no members but has submitted offsets. All consumers have left but retained offsets.
Dead: No members in the group and no submitted offset. The group is deleted or has long-term inactivity.
Stable: Members in the group consume normally, and partition allocation is balanced. Normal operating status.
PreparingRebalance: The group is preparing to rebalance. A new member joins or an existing member leaves.
CompletingRebalance: The group is preparing to rebalance. New members join or existing members leave.
     */
    public String getState() {
        return this.State;
    }

    /**
     * Set Empty: The group has no members but has submitted offsets. All consumers have left but retained offsets.
Dead: No members in the group and no submitted offset. The group is deleted or has long-term inactivity.
Stable: Members in the group consume normally, and partition allocation is balanced. Normal operating status.
PreparingRebalance: The group is preparing to rebalance. A new member joins or an existing member leaves.
CompletingRebalance: The group is preparing to rebalance. New members join or existing members leave.
     * @param State Empty: The group has no members but has submitted offsets. All consumers have left but retained offsets.
Dead: No members in the group and no submitted offset. The group is deleted or has long-term inactivity.
Stable: Members in the group consume normally, and partition allocation is balanced. Normal operating status.
PreparingRebalance: The group is preparing to rebalance. A new member joins or an existing member leaves.
CompletingRebalance: The group is preparing to rebalance. New members join or existing members leave.
     */
    public void setState(String State) {
        this.State = State;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeKafkaConsumerGroupDetailResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeKafkaConsumerGroupDetailResponse(DescribeKafkaConsumerGroupDetailResponse source) {
        if (source.LogsetId != null) {
            this.LogsetId = new String(source.LogsetId);
        }
        if (source.Group != null) {
            this.Group = new String(source.Group);
        }
        if (source.PartitionInfos != null) {
            this.PartitionInfos = new GroupPartitionInfo[source.PartitionInfos.length];
            for (int i = 0; i < source.PartitionInfos.length; i++) {
                this.PartitionInfos[i] = new GroupPartitionInfo(source.PartitionInfos[i]);
            }
        }
        if (source.State != null) {
            this.State = new String(source.State);
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "LogsetId", this.LogsetId);
        this.setParamSimple(map, prefix + "Group", this.Group);
        this.setParamArrayObj(map, prefix + "PartitionInfos.", this.PartitionInfos);
        this.setParamSimple(map, prefix + "State", this.State);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

