/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.cls.v20201016.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class MachineGroupInfo extends AbstractModel {

    /**
    * Machine group ID
    */
    @SerializedName("GroupId")
    @Expose
    private String GroupId;

    /**
    * Machine group name
    */
    @SerializedName("GroupName")
    @Expose
    private String GroupName;

    /**
    * Machine group type
    */
    @SerializedName("MachineGroupType")
    @Expose
    private MachineGroupTypeInfo MachineGroupType;

    /**
    * Creation time.
Time format: yyyy-MM-dd HH:mm:ss
    */
    @SerializedName("CreateTime")
    @Expose
    private String CreateTime;

    /**
    * List of tags bound to machine group
    */
    @SerializedName("Tags")
    @Expose
    private Tag [] Tags;

    /**
    * Whether machine group auto-update is enabled
    */
    @SerializedName("AutoUpdate")
    @Expose
    private String AutoUpdate;

    /**
    * Start time of upgrade. It is suggested to upgrade LogListener in the off-peak period of the business.
Time format: HH:mm:ss
    */
    @SerializedName("UpdateStartTime")
    @Expose
    private String UpdateStartTime;

    /**
    * End time of upgrade. It is suggested to upgrade LogListener in the off-peak period of the business.
Time format: HH:mm:ss.
    */
    @SerializedName("UpdateEndTime")
    @Expose
    private String UpdateEndTime;

    /**
    * Whether service logs are enabled to record logs generated by the LogListener service itself. Once enabled, it will create an internal log set cls_service_logging, and log topics including loglistener_status, loglistener_alarm, and loglistener_business, without incurring charges.
    */
    @SerializedName("ServiceLogging")
    @Expose
    private Boolean ServiceLogging;

    /**
    * Regular cleanup time for offline machines in the machine group, in days, default setting 30 days.
    */
    @SerializedName("DelayCleanupTime")
    @Expose
    private Long DelayCleanupTime;

    /**
    * Metadata information list of a machine group
    */
    @SerializedName("MetaTags")
    @Expose
    private MetaTagInfo [] MetaTags;

    /**
    * Operating system type, 0: Linux, 1: Windows
    */
    @SerializedName("OSType")
    @Expose
    private Long OSType;

    /**
     * Get Machine group ID 
     * @return GroupId Machine group ID
     */
    public String getGroupId() {
        return this.GroupId;
    }

    /**
     * Set Machine group ID
     * @param GroupId Machine group ID
     */
    public void setGroupId(String GroupId) {
        this.GroupId = GroupId;
    }

    /**
     * Get Machine group name 
     * @return GroupName Machine group name
     */
    public String getGroupName() {
        return this.GroupName;
    }

    /**
     * Set Machine group name
     * @param GroupName Machine group name
     */
    public void setGroupName(String GroupName) {
        this.GroupName = GroupName;
    }

    /**
     * Get Machine group type 
     * @return MachineGroupType Machine group type
     */
    public MachineGroupTypeInfo getMachineGroupType() {
        return this.MachineGroupType;
    }

    /**
     * Set Machine group type
     * @param MachineGroupType Machine group type
     */
    public void setMachineGroupType(MachineGroupTypeInfo MachineGroupType) {
        this.MachineGroupType = MachineGroupType;
    }

    /**
     * Get Creation time.
Time format: yyyy-MM-dd HH:mm:ss 
     * @return CreateTime Creation time.
Time format: yyyy-MM-dd HH:mm:ss
     */
    public String getCreateTime() {
        return this.CreateTime;
    }

    /**
     * Set Creation time.
Time format: yyyy-MM-dd HH:mm:ss
     * @param CreateTime Creation time.
Time format: yyyy-MM-dd HH:mm:ss
     */
    public void setCreateTime(String CreateTime) {
        this.CreateTime = CreateTime;
    }

    /**
     * Get List of tags bound to machine group 
     * @return Tags List of tags bound to machine group
     */
    public Tag [] getTags() {
        return this.Tags;
    }

    /**
     * Set List of tags bound to machine group
     * @param Tags List of tags bound to machine group
     */
    public void setTags(Tag [] Tags) {
        this.Tags = Tags;
    }

    /**
     * Get Whether machine group auto-update is enabled 
     * @return AutoUpdate Whether machine group auto-update is enabled
     */
    public String getAutoUpdate() {
        return this.AutoUpdate;
    }

    /**
     * Set Whether machine group auto-update is enabled
     * @param AutoUpdate Whether machine group auto-update is enabled
     */
    public void setAutoUpdate(String AutoUpdate) {
        this.AutoUpdate = AutoUpdate;
    }

    /**
     * Get Start time of upgrade. It is suggested to upgrade LogListener in the off-peak period of the business.
Time format: HH:mm:ss 
     * @return UpdateStartTime Start time of upgrade. It is suggested to upgrade LogListener in the off-peak period of the business.
Time format: HH:mm:ss
     */
    public String getUpdateStartTime() {
        return this.UpdateStartTime;
    }

    /**
     * Set Start time of upgrade. It is suggested to upgrade LogListener in the off-peak period of the business.
Time format: HH:mm:ss
     * @param UpdateStartTime Start time of upgrade. It is suggested to upgrade LogListener in the off-peak period of the business.
Time format: HH:mm:ss
     */
    public void setUpdateStartTime(String UpdateStartTime) {
        this.UpdateStartTime = UpdateStartTime;
    }

    /**
     * Get End time of upgrade. It is suggested to upgrade LogListener in the off-peak period of the business.
Time format: HH:mm:ss. 
     * @return UpdateEndTime End time of upgrade. It is suggested to upgrade LogListener in the off-peak period of the business.
Time format: HH:mm:ss.
     */
    public String getUpdateEndTime() {
        return this.UpdateEndTime;
    }

    /**
     * Set End time of upgrade. It is suggested to upgrade LogListener in the off-peak period of the business.
Time format: HH:mm:ss.
     * @param UpdateEndTime End time of upgrade. It is suggested to upgrade LogListener in the off-peak period of the business.
Time format: HH:mm:ss.
     */
    public void setUpdateEndTime(String UpdateEndTime) {
        this.UpdateEndTime = UpdateEndTime;
    }

    /**
     * Get Whether service logs are enabled to record logs generated by the LogListener service itself. Once enabled, it will create an internal log set cls_service_logging, and log topics including loglistener_status, loglistener_alarm, and loglistener_business, without incurring charges. 
     * @return ServiceLogging Whether service logs are enabled to record logs generated by the LogListener service itself. Once enabled, it will create an internal log set cls_service_logging, and log topics including loglistener_status, loglistener_alarm, and loglistener_business, without incurring charges.
     */
    public Boolean getServiceLogging() {
        return this.ServiceLogging;
    }

    /**
     * Set Whether service logs are enabled to record logs generated by the LogListener service itself. Once enabled, it will create an internal log set cls_service_logging, and log topics including loglistener_status, loglistener_alarm, and loglistener_business, without incurring charges.
     * @param ServiceLogging Whether service logs are enabled to record logs generated by the LogListener service itself. Once enabled, it will create an internal log set cls_service_logging, and log topics including loglistener_status, loglistener_alarm, and loglistener_business, without incurring charges.
     */
    public void setServiceLogging(Boolean ServiceLogging) {
        this.ServiceLogging = ServiceLogging;
    }

    /**
     * Get Regular cleanup time for offline machines in the machine group, in days, default setting 30 days. 
     * @return DelayCleanupTime Regular cleanup time for offline machines in the machine group, in days, default setting 30 days.
     */
    public Long getDelayCleanupTime() {
        return this.DelayCleanupTime;
    }

    /**
     * Set Regular cleanup time for offline machines in the machine group, in days, default setting 30 days.
     * @param DelayCleanupTime Regular cleanup time for offline machines in the machine group, in days, default setting 30 days.
     */
    public void setDelayCleanupTime(Long DelayCleanupTime) {
        this.DelayCleanupTime = DelayCleanupTime;
    }

    /**
     * Get Metadata information list of a machine group 
     * @return MetaTags Metadata information list of a machine group
     */
    public MetaTagInfo [] getMetaTags() {
        return this.MetaTags;
    }

    /**
     * Set Metadata information list of a machine group
     * @param MetaTags Metadata information list of a machine group
     */
    public void setMetaTags(MetaTagInfo [] MetaTags) {
        this.MetaTags = MetaTags;
    }

    /**
     * Get Operating system type, 0: Linux, 1: Windows 
     * @return OSType Operating system type, 0: Linux, 1: Windows
     */
    public Long getOSType() {
        return this.OSType;
    }

    /**
     * Set Operating system type, 0: Linux, 1: Windows
     * @param OSType Operating system type, 0: Linux, 1: Windows
     */
    public void setOSType(Long OSType) {
        this.OSType = OSType;
    }

    public MachineGroupInfo() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public MachineGroupInfo(MachineGroupInfo source) {
        if (source.GroupId != null) {
            this.GroupId = new String(source.GroupId);
        }
        if (source.GroupName != null) {
            this.GroupName = new String(source.GroupName);
        }
        if (source.MachineGroupType != null) {
            this.MachineGroupType = new MachineGroupTypeInfo(source.MachineGroupType);
        }
        if (source.CreateTime != null) {
            this.CreateTime = new String(source.CreateTime);
        }
        if (source.Tags != null) {
            this.Tags = new Tag[source.Tags.length];
            for (int i = 0; i < source.Tags.length; i++) {
                this.Tags[i] = new Tag(source.Tags[i]);
            }
        }
        if (source.AutoUpdate != null) {
            this.AutoUpdate = new String(source.AutoUpdate);
        }
        if (source.UpdateStartTime != null) {
            this.UpdateStartTime = new String(source.UpdateStartTime);
        }
        if (source.UpdateEndTime != null) {
            this.UpdateEndTime = new String(source.UpdateEndTime);
        }
        if (source.ServiceLogging != null) {
            this.ServiceLogging = new Boolean(source.ServiceLogging);
        }
        if (source.DelayCleanupTime != null) {
            this.DelayCleanupTime = new Long(source.DelayCleanupTime);
        }
        if (source.MetaTags != null) {
            this.MetaTags = new MetaTagInfo[source.MetaTags.length];
            for (int i = 0; i < source.MetaTags.length; i++) {
                this.MetaTags[i] = new MetaTagInfo(source.MetaTags[i]);
            }
        }
        if (source.OSType != null) {
            this.OSType = new Long(source.OSType);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "GroupId", this.GroupId);
        this.setParamSimple(map, prefix + "GroupName", this.GroupName);
        this.setParamObj(map, prefix + "MachineGroupType.", this.MachineGroupType);
        this.setParamSimple(map, prefix + "CreateTime", this.CreateTime);
        this.setParamArrayObj(map, prefix + "Tags.", this.Tags);
        this.setParamSimple(map, prefix + "AutoUpdate", this.AutoUpdate);
        this.setParamSimple(map, prefix + "UpdateStartTime", this.UpdateStartTime);
        this.setParamSimple(map, prefix + "UpdateEndTime", this.UpdateEndTime);
        this.setParamSimple(map, prefix + "ServiceLogging", this.ServiceLogging);
        this.setParamSimple(map, prefix + "DelayCleanupTime", this.DelayCleanupTime);
        this.setParamArrayObj(map, prefix + "MetaTags.", this.MetaTags);
        this.setParamSimple(map, prefix + "OSType", this.OSType);

    }
}

