/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.cls.v20201016.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class SearchCosRechargeInfoResponse extends AbstractModel {

    /**
    * First few lines of data from a certain file under the matched bucket
    */
    @SerializedName("Data")
    @Expose
    private String [] Data;

    /**
    * Number of files under the matched bucket
    */
    @SerializedName("Sum")
    @Expose
    private Long Sum;

    /**
    * Current preview file path
    */
    @SerializedName("Path")
    @Expose
    private String Path;

    /**
    * Reason for preview data fetch failure
    */
    @SerializedName("Msg")
    @Expose
    private String Msg;

    /**
    * Status.
-0: Success
-10000: Parameter error. Parameter confirmation.
-10001: Authorization failure. Please confirm authorization.
-10002: Failed to get file list. Try again later. If the problem persists, consult [online support](https://andon.tencentcloud.com/online-service?from=doc_614) or [submit a ticket](https://console.cloud.tencent.com/workorder/category?level1_id=83&level2_id=469&source=14&data_title=%E6%97%A5%E5%BF%97%E6%9C%8D%E5%8A%A1&step=1) to fix it.
-10003: No corresponding prefix files in the bucket. Use the correct bucket, file prefix, and compression method.
-10004: File download failed. Try again later. If the problem persists, consult [online support](https://andon.tencentcloud.com/online-service?from=doc_614) or [submit a ticket](https://console.cloud.tencent.com/workorder/category?level1_id=83&level2_id=469&source=14&data_title=%E6%97%A5%E5%BF%97%E6%9C%8D%E5%8A%A1&step=1) to fix it.
-10005: File decompression failed. Select the correct compression method and try again.
-10006: Failed to read file content. Please confirm the file is readable.
-10007: File preview failed, try again later. If the problem persists, consult [online support](https://andon.tencentcloud.com/online-service?from=doc_614) or [submit a ticket](https://console.cloud.tencent.com/workorder/category?level1_id=83&level2_id=469&source=14&data_title=%E6%97%A5%E5%BF%97%E6%9C%8D%E5%8A%A1&step=1) to fix it.
    */
    @SerializedName("Status")
    @Expose
    private Long Status;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get First few lines of data from a certain file under the matched bucket 
     * @return Data First few lines of data from a certain file under the matched bucket
     */
    public String [] getData() {
        return this.Data;
    }

    /**
     * Set First few lines of data from a certain file under the matched bucket
     * @param Data First few lines of data from a certain file under the matched bucket
     */
    public void setData(String [] Data) {
        this.Data = Data;
    }

    /**
     * Get Number of files under the matched bucket 
     * @return Sum Number of files under the matched bucket
     */
    public Long getSum() {
        return this.Sum;
    }

    /**
     * Set Number of files under the matched bucket
     * @param Sum Number of files under the matched bucket
     */
    public void setSum(Long Sum) {
        this.Sum = Sum;
    }

    /**
     * Get Current preview file path 
     * @return Path Current preview file path
     */
    public String getPath() {
        return this.Path;
    }

    /**
     * Set Current preview file path
     * @param Path Current preview file path
     */
    public void setPath(String Path) {
        this.Path = Path;
    }

    /**
     * Get Reason for preview data fetch failure 
     * @return Msg Reason for preview data fetch failure
     */
    public String getMsg() {
        return this.Msg;
    }

    /**
     * Set Reason for preview data fetch failure
     * @param Msg Reason for preview data fetch failure
     */
    public void setMsg(String Msg) {
        this.Msg = Msg;
    }

    /**
     * Get Status.
-0: Success
-10000: Parameter error. Parameter confirmation.
-10001: Authorization failure. Please confirm authorization.
-10002: Failed to get file list. Try again later. If the problem persists, consult [online support](https://andon.tencentcloud.com/online-service?from=doc_614) or [submit a ticket](https://console.cloud.tencent.com/workorder/category?level1_id=83&level2_id=469&source=14&data_title=%E6%97%A5%E5%BF%97%E6%9C%8D%E5%8A%A1&step=1) to fix it.
-10003: No corresponding prefix files in the bucket. Use the correct bucket, file prefix, and compression method.
-10004: File download failed. Try again later. If the problem persists, consult [online support](https://andon.tencentcloud.com/online-service?from=doc_614) or [submit a ticket](https://console.cloud.tencent.com/workorder/category?level1_id=83&level2_id=469&source=14&data_title=%E6%97%A5%E5%BF%97%E6%9C%8D%E5%8A%A1&step=1) to fix it.
-10005: File decompression failed. Select the correct compression method and try again.
-10006: Failed to read file content. Please confirm the file is readable.
-10007: File preview failed, try again later. If the problem persists, consult [online support](https://andon.tencentcloud.com/online-service?from=doc_614) or [submit a ticket](https://console.cloud.tencent.com/workorder/category?level1_id=83&level2_id=469&source=14&data_title=%E6%97%A5%E5%BF%97%E6%9C%8D%E5%8A%A1&step=1) to fix it. 
     * @return Status Status.
-0: Success
-10000: Parameter error. Parameter confirmation.
-10001: Authorization failure. Please confirm authorization.
-10002: Failed to get file list. Try again later. If the problem persists, consult [online support](https://andon.tencentcloud.com/online-service?from=doc_614) or [submit a ticket](https://console.cloud.tencent.com/workorder/category?level1_id=83&level2_id=469&source=14&data_title=%E6%97%A5%E5%BF%97%E6%9C%8D%E5%8A%A1&step=1) to fix it.
-10003: No corresponding prefix files in the bucket. Use the correct bucket, file prefix, and compression method.
-10004: File download failed. Try again later. If the problem persists, consult [online support](https://andon.tencentcloud.com/online-service?from=doc_614) or [submit a ticket](https://console.cloud.tencent.com/workorder/category?level1_id=83&level2_id=469&source=14&data_title=%E6%97%A5%E5%BF%97%E6%9C%8D%E5%8A%A1&step=1) to fix it.
-10005: File decompression failed. Select the correct compression method and try again.
-10006: Failed to read file content. Please confirm the file is readable.
-10007: File preview failed, try again later. If the problem persists, consult [online support](https://andon.tencentcloud.com/online-service?from=doc_614) or [submit a ticket](https://console.cloud.tencent.com/workorder/category?level1_id=83&level2_id=469&source=14&data_title=%E6%97%A5%E5%BF%97%E6%9C%8D%E5%8A%A1&step=1) to fix it.
     */
    public Long getStatus() {
        return this.Status;
    }

    /**
     * Set Status.
-0: Success
-10000: Parameter error. Parameter confirmation.
-10001: Authorization failure. Please confirm authorization.
-10002: Failed to get file list. Try again later. If the problem persists, consult [online support](https://andon.tencentcloud.com/online-service?from=doc_614) or [submit a ticket](https://console.cloud.tencent.com/workorder/category?level1_id=83&level2_id=469&source=14&data_title=%E6%97%A5%E5%BF%97%E6%9C%8D%E5%8A%A1&step=1) to fix it.
-10003: No corresponding prefix files in the bucket. Use the correct bucket, file prefix, and compression method.
-10004: File download failed. Try again later. If the problem persists, consult [online support](https://andon.tencentcloud.com/online-service?from=doc_614) or [submit a ticket](https://console.cloud.tencent.com/workorder/category?level1_id=83&level2_id=469&source=14&data_title=%E6%97%A5%E5%BF%97%E6%9C%8D%E5%8A%A1&step=1) to fix it.
-10005: File decompression failed. Select the correct compression method and try again.
-10006: Failed to read file content. Please confirm the file is readable.
-10007: File preview failed, try again later. If the problem persists, consult [online support](https://andon.tencentcloud.com/online-service?from=doc_614) or [submit a ticket](https://console.cloud.tencent.com/workorder/category?level1_id=83&level2_id=469&source=14&data_title=%E6%97%A5%E5%BF%97%E6%9C%8D%E5%8A%A1&step=1) to fix it.
     * @param Status Status.
-0: Success
-10000: Parameter error. Parameter confirmation.
-10001: Authorization failure. Please confirm authorization.
-10002: Failed to get file list. Try again later. If the problem persists, consult [online support](https://andon.tencentcloud.com/online-service?from=doc_614) or [submit a ticket](https://console.cloud.tencent.com/workorder/category?level1_id=83&level2_id=469&source=14&data_title=%E6%97%A5%E5%BF%97%E6%9C%8D%E5%8A%A1&step=1) to fix it.
-10003: No corresponding prefix files in the bucket. Use the correct bucket, file prefix, and compression method.
-10004: File download failed. Try again later. If the problem persists, consult [online support](https://andon.tencentcloud.com/online-service?from=doc_614) or [submit a ticket](https://console.cloud.tencent.com/workorder/category?level1_id=83&level2_id=469&source=14&data_title=%E6%97%A5%E5%BF%97%E6%9C%8D%E5%8A%A1&step=1) to fix it.
-10005: File decompression failed. Select the correct compression method and try again.
-10006: Failed to read file content. Please confirm the file is readable.
-10007: File preview failed, try again later. If the problem persists, consult [online support](https://andon.tencentcloud.com/online-service?from=doc_614) or [submit a ticket](https://console.cloud.tencent.com/workorder/category?level1_id=83&level2_id=469&source=14&data_title=%E6%97%A5%E5%BF%97%E6%9C%8D%E5%8A%A1&step=1) to fix it.
     */
    public void setStatus(Long Status) {
        this.Status = Status;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public SearchCosRechargeInfoResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public SearchCosRechargeInfoResponse(SearchCosRechargeInfoResponse source) {
        if (source.Data != null) {
            this.Data = new String[source.Data.length];
            for (int i = 0; i < source.Data.length; i++) {
                this.Data[i] = new String(source.Data[i]);
            }
        }
        if (source.Sum != null) {
            this.Sum = new Long(source.Sum);
        }
        if (source.Path != null) {
            this.Path = new String(source.Path);
        }
        if (source.Msg != null) {
            this.Msg = new String(source.Msg);
        }
        if (source.Status != null) {
            this.Status = new Long(source.Status);
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamArraySimple(map, prefix + "Data.", this.Data);
        this.setParamSimple(map, prefix + "Sum", this.Sum);
        this.setParamSimple(map, prefix + "Path", this.Path);
        this.setParamSimple(map, prefix + "Msg", this.Msg);
        this.setParamSimple(map, prefix + "Status", this.Status);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

