/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.cls.v20201016.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class SendConsumerHeartbeatResponse extends AbstractModel {

    /**
    * Consumer group flag corresponding to a log topic.
    */
    @SerializedName("ConsumerGroup")
    @Expose
    private String ConsumerGroup;

    /**
    * Partition information
    */
    @SerializedName("TopicPartitionsInfo")
    @Expose
    private TopicPartitionInfo [] TopicPartitionsInfo;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Consumer group flag corresponding to a log topic. 
     * @return ConsumerGroup Consumer group flag corresponding to a log topic.
     */
    public String getConsumerGroup() {
        return this.ConsumerGroup;
    }

    /**
     * Set Consumer group flag corresponding to a log topic.
     * @param ConsumerGroup Consumer group flag corresponding to a log topic.
     */
    public void setConsumerGroup(String ConsumerGroup) {
        this.ConsumerGroup = ConsumerGroup;
    }

    /**
     * Get Partition information 
     * @return TopicPartitionsInfo Partition information
     */
    public TopicPartitionInfo [] getTopicPartitionsInfo() {
        return this.TopicPartitionsInfo;
    }

    /**
     * Set Partition information
     * @param TopicPartitionsInfo Partition information
     */
    public void setTopicPartitionsInfo(TopicPartitionInfo [] TopicPartitionsInfo) {
        this.TopicPartitionsInfo = TopicPartitionsInfo;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public SendConsumerHeartbeatResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public SendConsumerHeartbeatResponse(SendConsumerHeartbeatResponse source) {
        if (source.ConsumerGroup != null) {
            this.ConsumerGroup = new String(source.ConsumerGroup);
        }
        if (source.TopicPartitionsInfo != null) {
            this.TopicPartitionsInfo = new TopicPartitionInfo[source.TopicPartitionsInfo.length];
            for (int i = 0; i < source.TopicPartitionsInfo.length; i++) {
                this.TopicPartitionsInfo[i] = new TopicPartitionInfo(source.TopicPartitionsInfo[i]);
            }
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "ConsumerGroup", this.ConsumerGroup);
        this.setParamArrayObj(map, prefix + "TopicPartitionsInfo.", this.TopicPartitionsInfo);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

