/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.teo.v20220901.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeSharedCNAMEResponse extends AbstractModel {

    /**
    * Total number of shared CNAMEs that meet filtering criteria.
    */
    @SerializedName("TotalCount")
    @Expose
    private Long TotalCount;

    /**
    * Shared CNAME table detail.
    */
    @SerializedName("SharedCNAMEInfo")
    @Expose
    private SharedCNAMEInfo [] SharedCNAMEInfo;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Total number of shared CNAMEs that meet filtering criteria. 
     * @return TotalCount Total number of shared CNAMEs that meet filtering criteria.
     */
    public Long getTotalCount() {
        return this.TotalCount;
    }

    /**
     * Set Total number of shared CNAMEs that meet filtering criteria.
     * @param TotalCount Total number of shared CNAMEs that meet filtering criteria.
     */
    public void setTotalCount(Long TotalCount) {
        this.TotalCount = TotalCount;
    }

    /**
     * Get Shared CNAME table detail. 
     * @return SharedCNAMEInfo Shared CNAME table detail.
     */
    public SharedCNAMEInfo [] getSharedCNAMEInfo() {
        return this.SharedCNAMEInfo;
    }

    /**
     * Set Shared CNAME table detail.
     * @param SharedCNAMEInfo Shared CNAME table detail.
     */
    public void setSharedCNAMEInfo(SharedCNAMEInfo [] SharedCNAMEInfo) {
        this.SharedCNAMEInfo = SharedCNAMEInfo;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeSharedCNAMEResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeSharedCNAMEResponse(DescribeSharedCNAMEResponse source) {
        if (source.TotalCount != null) {
            this.TotalCount = new Long(source.TotalCount);
        }
        if (source.SharedCNAMEInfo != null) {
            this.SharedCNAMEInfo = new SharedCNAMEInfo[source.SharedCNAMEInfo.length];
            for (int i = 0; i < source.SharedCNAMEInfo.length; i++) {
                this.SharedCNAMEInfo[i] = new SharedCNAMEInfo(source.SharedCNAMEInfo[i]);
            }
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "TotalCount", this.TotalCount);
        this.setParamArrayObj(map, prefix + "SharedCNAMEInfo.", this.SharedCNAMEInfo);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

