/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.teo.v20220901.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeSecurityIPGroupResponse extends AbstractModel {

    /**
    * Detailed configuration information of security IP groups, including the ID, name, and IP/IP range list information of each security IP group.
    */
    @SerializedName("IPGroups")
    @Expose
    private IPGroup [] IPGroups;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Detailed configuration information of security IP groups, including the ID, name, and IP/IP range list information of each security IP group. 
     * @return IPGroups Detailed configuration information of security IP groups, including the ID, name, and IP/IP range list information of each security IP group.
     */
    public IPGroup [] getIPGroups() {
        return this.IPGroups;
    }

    /**
     * Set Detailed configuration information of security IP groups, including the ID, name, and IP/IP range list information of each security IP group.
     * @param IPGroups Detailed configuration information of security IP groups, including the ID, name, and IP/IP range list information of each security IP group.
     */
    public void setIPGroups(IPGroup [] IPGroups) {
        this.IPGroups = IPGroups;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeSecurityIPGroupResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeSecurityIPGroupResponse(DescribeSecurityIPGroupResponse source) {
        if (source.IPGroups != null) {
            this.IPGroups = new IPGroup[source.IPGroups.length];
            for (int i = 0; i < source.IPGroups.length; i++) {
                this.IPGroups[i] = new IPGroup(source.IPGroups[i]);
            }
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamArrayObj(map, prefix + "IPGroups.", this.IPGroups);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

