/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.vod.v20180717.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class ApplyUploadResponse extends AbstractModel {

    /**
    * <p>Bucket for uploading the API URL bucket_name.</p>
    */
    @SerializedName("StorageBucket")
    @Expose
    private String StorageBucket;

    /**
    * <p>Storage campus for uploading the Host Region of the port.</p>
    */
    @SerializedName("StorageRegion")
    @Expose
    private String StorageRegion;

    /**
    * <p>VOD session for confirmation of API parameters VodSessionKey.</p>
    */
    @SerializedName("VodSessionKey")
    @Expose
    private String VodSessionKey;

    /**
    * <p>Media storage path used for the object key (Key) of media stored by the upload API.</p>
    */
    @SerializedName("MediaStoragePath")
    @Expose
    private String MediaStoragePath;

    /**
    * <p>Cover storage path for uploading the object Key of the cover via API.</p>
    */
    @SerializedName("CoverStoragePath")
    @Expose
    private String CoverStoragePath;

    /**
    * <p>Temporary credentials for uploading API access verification.</p>
    */
    @SerializedName("TempCertificate")
    @Expose
    private TempCertificate TempCertificate;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get <p>Bucket for uploading the API URL bucket_name.</p> 
     * @return StorageBucket <p>Bucket for uploading the API URL bucket_name.</p>
     */
    public String getStorageBucket() {
        return this.StorageBucket;
    }

    /**
     * Set <p>Bucket for uploading the API URL bucket_name.</p>
     * @param StorageBucket <p>Bucket for uploading the API URL bucket_name.</p>
     */
    public void setStorageBucket(String StorageBucket) {
        this.StorageBucket = StorageBucket;
    }

    /**
     * Get <p>Storage campus for uploading the Host Region of the port.</p> 
     * @return StorageRegion <p>Storage campus for uploading the Host Region of the port.</p>
     */
    public String getStorageRegion() {
        return this.StorageRegion;
    }

    /**
     * Set <p>Storage campus for uploading the Host Region of the port.</p>
     * @param StorageRegion <p>Storage campus for uploading the Host Region of the port.</p>
     */
    public void setStorageRegion(String StorageRegion) {
        this.StorageRegion = StorageRegion;
    }

    /**
     * Get <p>VOD session for confirmation of API parameters VodSessionKey.</p> 
     * @return VodSessionKey <p>VOD session for confirmation of API parameters VodSessionKey.</p>
     */
    public String getVodSessionKey() {
        return this.VodSessionKey;
    }

    /**
     * Set <p>VOD session for confirmation of API parameters VodSessionKey.</p>
     * @param VodSessionKey <p>VOD session for confirmation of API parameters VodSessionKey.</p>
     */
    public void setVodSessionKey(String VodSessionKey) {
        this.VodSessionKey = VodSessionKey;
    }

    /**
     * Get <p>Media storage path used for the object key (Key) of media stored by the upload API.</p> 
     * @return MediaStoragePath <p>Media storage path used for the object key (Key) of media stored by the upload API.</p>
     */
    public String getMediaStoragePath() {
        return this.MediaStoragePath;
    }

    /**
     * Set <p>Media storage path used for the object key (Key) of media stored by the upload API.</p>
     * @param MediaStoragePath <p>Media storage path used for the object key (Key) of media stored by the upload API.</p>
     */
    public void setMediaStoragePath(String MediaStoragePath) {
        this.MediaStoragePath = MediaStoragePath;
    }

    /**
     * Get <p>Cover storage path for uploading the object Key of the cover via API.</p> 
     * @return CoverStoragePath <p>Cover storage path for uploading the object Key of the cover via API.</p>
     */
    public String getCoverStoragePath() {
        return this.CoverStoragePath;
    }

    /**
     * Set <p>Cover storage path for uploading the object Key of the cover via API.</p>
     * @param CoverStoragePath <p>Cover storage path for uploading the object Key of the cover via API.</p>
     */
    public void setCoverStoragePath(String CoverStoragePath) {
        this.CoverStoragePath = CoverStoragePath;
    }

    /**
     * Get <p>Temporary credentials for uploading API access verification.</p> 
     * @return TempCertificate <p>Temporary credentials for uploading API access verification.</p>
     */
    public TempCertificate getTempCertificate() {
        return this.TempCertificate;
    }

    /**
     * Set <p>Temporary credentials for uploading API access verification.</p>
     * @param TempCertificate <p>Temporary credentials for uploading API access verification.</p>
     */
    public void setTempCertificate(TempCertificate TempCertificate) {
        this.TempCertificate = TempCertificate;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public ApplyUploadResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public ApplyUploadResponse(ApplyUploadResponse source) {
        if (source.StorageBucket != null) {
            this.StorageBucket = new String(source.StorageBucket);
        }
        if (source.StorageRegion != null) {
            this.StorageRegion = new String(source.StorageRegion);
        }
        if (source.VodSessionKey != null) {
            this.VodSessionKey = new String(source.VodSessionKey);
        }
        if (source.MediaStoragePath != null) {
            this.MediaStoragePath = new String(source.MediaStoragePath);
        }
        if (source.CoverStoragePath != null) {
            this.CoverStoragePath = new String(source.CoverStoragePath);
        }
        if (source.TempCertificate != null) {
            this.TempCertificate = new TempCertificate(source.TempCertificate);
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "StorageBucket", this.StorageBucket);
        this.setParamSimple(map, prefix + "StorageRegion", this.StorageRegion);
        this.setParamSimple(map, prefix + "VodSessionKey", this.VodSessionKey);
        this.setParamSimple(map, prefix + "MediaStoragePath", this.MediaStoragePath);
        this.setParamSimple(map, prefix + "CoverStoragePath", this.CoverStoragePath);
        this.setParamObj(map, prefix + "TempCertificate.", this.TempCertificate);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

