/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.cfg.v20210820.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeTaskPolicyTriggerLogResponse extends AbstractModel {

    /**
    * Triggering log
Note: This field may return null, indicating that no valid values can be obtained.
    */
    @SerializedName("TriggerLogs")
    @Expose
    private PolicyTriggerLog [] TriggerLogs;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Triggering log
Note: This field may return null, indicating that no valid values can be obtained. 
     * @return TriggerLogs Triggering log
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public PolicyTriggerLog [] getTriggerLogs() {
        return this.TriggerLogs;
    }

    /**
     * Set Triggering log
Note: This field may return null, indicating that no valid values can be obtained.
     * @param TriggerLogs Triggering log
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public void setTriggerLogs(PolicyTriggerLog [] TriggerLogs) {
        this.TriggerLogs = TriggerLogs;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeTaskPolicyTriggerLogResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeTaskPolicyTriggerLogResponse(DescribeTaskPolicyTriggerLogResponse source) {
        if (source.TriggerLogs != null) {
            this.TriggerLogs = new PolicyTriggerLog[source.TriggerLogs.length];
            for (int i = 0; i < source.TriggerLogs.length; i++) {
                this.TriggerLogs[i] = new PolicyTriggerLog(source.TriggerLogs[i]);
            }
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamArrayObj(map, prefix + "TriggerLogs.", this.TriggerLogs);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

