/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.trocket.v20230308.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeConsumerClientResponse extends AbstractModel {

    /**
    * Client details

Note: This field may return null, indicating that no valid values can be obtained.
    */
    @SerializedName("Client")
    @Expose
    private ConsumerClient Client;

    /**
    * Topic consumption information

Note: This field may return null, indicating that no valid values can be obtained.
    */
    @SerializedName("TopicList")
    @Expose
    private TopicConsumeStats [] TopicList;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Client details

Note: This field may return null, indicating that no valid values can be obtained. 
     * @return Client Client details

Note: This field may return null, indicating that no valid values can be obtained.
     */
    public ConsumerClient getClient() {
        return this.Client;
    }

    /**
     * Set Client details

Note: This field may return null, indicating that no valid values can be obtained.
     * @param Client Client details

Note: This field may return null, indicating that no valid values can be obtained.
     */
    public void setClient(ConsumerClient Client) {
        this.Client = Client;
    }

    /**
     * Get Topic consumption information

Note: This field may return null, indicating that no valid values can be obtained. 
     * @return TopicList Topic consumption information

Note: This field may return null, indicating that no valid values can be obtained.
     */
    public TopicConsumeStats [] getTopicList() {
        return this.TopicList;
    }

    /**
     * Set Topic consumption information

Note: This field may return null, indicating that no valid values can be obtained.
     * @param TopicList Topic consumption information

Note: This field may return null, indicating that no valid values can be obtained.
     */
    public void setTopicList(TopicConsumeStats [] TopicList) {
        this.TopicList = TopicList;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeConsumerClientResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeConsumerClientResponse(DescribeConsumerClientResponse source) {
        if (source.Client != null) {
            this.Client = new ConsumerClient(source.Client);
        }
        if (source.TopicList != null) {
            this.TopicList = new TopicConsumeStats[source.TopicList.length];
            for (int i = 0; i < source.TopicList.length; i++) {
                this.TopicList[i] = new TopicConsumeStats(source.TopicList[i]);
            }
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamObj(map, prefix + "Client.", this.Client);
        this.setParamArrayObj(map, prefix + "TopicList.", this.TopicList);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

