/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.tcss.v20201101.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeSecLogJoinObjectListResponse extends AbstractModel {

    /**
    * Total number
    */
    @SerializedName("TotalCount")
    @Expose
    private Long TotalCount;

    /**
    * List of accessed objects
    */
    @SerializedName("List")
    @Expose
    private SecLogJoinObjectInfo [] List;

    /**
    * Log node scope type. 0: specified; 1: all.
    */
    @SerializedName("RangeType")
    @Expose
    private Long RangeType;

    /**
    * Whether new assets are accessed automatically. This parameter is valid only when the node scope involves all nodes.
    */
    @SerializedName("AutoJoin")
    @Expose
    private Boolean AutoJoin;

    /**
    * Number of excluded nodes.
    */
    @SerializedName("ExcludedCount")
    @Expose
    private Long ExcludedCount;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Total number 
     * @return TotalCount Total number
     */
    public Long getTotalCount() {
        return this.TotalCount;
    }

    /**
     * Set Total number
     * @param TotalCount Total number
     */
    public void setTotalCount(Long TotalCount) {
        this.TotalCount = TotalCount;
    }

    /**
     * Get List of accessed objects 
     * @return List List of accessed objects
     */
    public SecLogJoinObjectInfo [] getList() {
        return this.List;
    }

    /**
     * Set List of accessed objects
     * @param List List of accessed objects
     */
    public void setList(SecLogJoinObjectInfo [] List) {
        this.List = List;
    }

    /**
     * Get Log node scope type. 0: specified; 1: all. 
     * @return RangeType Log node scope type. 0: specified; 1: all.
     */
    public Long getRangeType() {
        return this.RangeType;
    }

    /**
     * Set Log node scope type. 0: specified; 1: all.
     * @param RangeType Log node scope type. 0: specified; 1: all.
     */
    public void setRangeType(Long RangeType) {
        this.RangeType = RangeType;
    }

    /**
     * Get Whether new assets are accessed automatically. This parameter is valid only when the node scope involves all nodes. 
     * @return AutoJoin Whether new assets are accessed automatically. This parameter is valid only when the node scope involves all nodes.
     */
    public Boolean getAutoJoin() {
        return this.AutoJoin;
    }

    /**
     * Set Whether new assets are accessed automatically. This parameter is valid only when the node scope involves all nodes.
     * @param AutoJoin Whether new assets are accessed automatically. This parameter is valid only when the node scope involves all nodes.
     */
    public void setAutoJoin(Boolean AutoJoin) {
        this.AutoJoin = AutoJoin;
    }

    /**
     * Get Number of excluded nodes. 
     * @return ExcludedCount Number of excluded nodes.
     */
    public Long getExcludedCount() {
        return this.ExcludedCount;
    }

    /**
     * Set Number of excluded nodes.
     * @param ExcludedCount Number of excluded nodes.
     */
    public void setExcludedCount(Long ExcludedCount) {
        this.ExcludedCount = ExcludedCount;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeSecLogJoinObjectListResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeSecLogJoinObjectListResponse(DescribeSecLogJoinObjectListResponse source) {
        if (source.TotalCount != null) {
            this.TotalCount = new Long(source.TotalCount);
        }
        if (source.List != null) {
            this.List = new SecLogJoinObjectInfo[source.List.length];
            for (int i = 0; i < source.List.length; i++) {
                this.List[i] = new SecLogJoinObjectInfo(source.List[i]);
            }
        }
        if (source.RangeType != null) {
            this.RangeType = new Long(source.RangeType);
        }
        if (source.AutoJoin != null) {
            this.AutoJoin = new Boolean(source.AutoJoin);
        }
        if (source.ExcludedCount != null) {
            this.ExcludedCount = new Long(source.ExcludedCount);
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "TotalCount", this.TotalCount);
        this.setParamArrayObj(map, prefix + "List.", this.List);
        this.setParamSimple(map, prefix + "RangeType", this.RangeType);
        this.setParamSimple(map, prefix + "AutoJoin", this.AutoJoin);
        this.setParamSimple(map, prefix + "ExcludedCount", this.ExcludedCount);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

