/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.tcss.v20201101.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeAssetSyncLastTimeResponse extends AbstractModel {

    /**
    * Last asset sync time
    */
    @SerializedName("AssetSyncLastTime")
    @Expose
    private String AssetSyncLastTime;

    /**
    * 
    */
    @SerializedName("TaskStatus")
    @Expose
    private String TaskStatus;

    /**
    * 
    */
    @SerializedName("TaskProcess")
    @Expose
    private Long TaskProcess;

    /**
    * Number of failed hosts.
    */
    @SerializedName("FailedHostCount")
    @Expose
    private Long FailedHostCount;

    /**
    * Task ID.
    */
    @SerializedName("TaskId")
    @Expose
    private Long TaskId;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Last asset sync time 
     * @return AssetSyncLastTime Last asset sync time
     */
    public String getAssetSyncLastTime() {
        return this.AssetSyncLastTime;
    }

    /**
     * Set Last asset sync time
     * @param AssetSyncLastTime Last asset sync time
     */
    public void setAssetSyncLastTime(String AssetSyncLastTime) {
        this.AssetSyncLastTime = AssetSyncLastTime;
    }

    /**
     * Get  
     * @return TaskStatus 
     */
    public String getTaskStatus() {
        return this.TaskStatus;
    }

    /**
     * Set 
     * @param TaskStatus 
     */
    public void setTaskStatus(String TaskStatus) {
        this.TaskStatus = TaskStatus;
    }

    /**
     * Get  
     * @return TaskProcess 
     */
    public Long getTaskProcess() {
        return this.TaskProcess;
    }

    /**
     * Set 
     * @param TaskProcess 
     */
    public void setTaskProcess(Long TaskProcess) {
        this.TaskProcess = TaskProcess;
    }

    /**
     * Get Number of failed hosts. 
     * @return FailedHostCount Number of failed hosts.
     */
    public Long getFailedHostCount() {
        return this.FailedHostCount;
    }

    /**
     * Set Number of failed hosts.
     * @param FailedHostCount Number of failed hosts.
     */
    public void setFailedHostCount(Long FailedHostCount) {
        this.FailedHostCount = FailedHostCount;
    }

    /**
     * Get Task ID. 
     * @return TaskId Task ID.
     */
    public Long getTaskId() {
        return this.TaskId;
    }

    /**
     * Set Task ID.
     * @param TaskId Task ID.
     */
    public void setTaskId(Long TaskId) {
        this.TaskId = TaskId;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeAssetSyncLastTimeResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeAssetSyncLastTimeResponse(DescribeAssetSyncLastTimeResponse source) {
        if (source.AssetSyncLastTime != null) {
            this.AssetSyncLastTime = new String(source.AssetSyncLastTime);
        }
        if (source.TaskStatus != null) {
            this.TaskStatus = new String(source.TaskStatus);
        }
        if (source.TaskProcess != null) {
            this.TaskProcess = new Long(source.TaskProcess);
        }
        if (source.FailedHostCount != null) {
            this.FailedHostCount = new Long(source.FailedHostCount);
        }
        if (source.TaskId != null) {
            this.TaskId = new Long(source.TaskId);
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "AssetSyncLastTime", this.AssetSyncLastTime);
        this.setParamSimple(map, prefix + "TaskStatus", this.TaskStatus);
        this.setParamSimple(map, prefix + "TaskProcess", this.TaskProcess);
        this.setParamSimple(map, prefix + "FailedHostCount", this.FailedHostCount);
        this.setParamSimple(map, prefix + "TaskId", this.TaskId);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

