/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.lkeap.v20240522.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class ChatCompletionsResponse extends SSEResponseModel {

    /**
    * Unix timestamp, in seconds.
    */
    @SerializedName("Created")
    @Expose
    private Long Created;

    /**
    * Token statistical information.
Charges are based on the total Token quantity.
    */
    @SerializedName("Usage")
    @Expose
    private ChatUsage Usage;

    /**
    * RequestId for this request.
    */
    @SerializedName("Id")
    @Expose
    private String Id;

    /**
    * Response content.
    */
    @SerializedName("Choices")
    @Expose
    private Choice [] Choices;

    /**
    * Model name.
    */
    @SerializedName("Model")
    @Expose
    private String Model;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. As a streaming response API, when the request is successfully completed, the RequestId will be placed in the Header "X-TC-RequestId" of the HTTP response.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Unix timestamp, in seconds. 
     * @return Created Unix timestamp, in seconds.
     */
    public Long getCreated() {
        return this.Created;
    }

    /**
     * Set Unix timestamp, in seconds.
     * @param Created Unix timestamp, in seconds.
     */
    public void setCreated(Long Created) {
        this.Created = Created;
    }

    /**
     * Get Token statistical information.
Charges are based on the total Token quantity. 
     * @return Usage Token statistical information.
Charges are based on the total Token quantity.
     */
    public ChatUsage getUsage() {
        return this.Usage;
    }

    /**
     * Set Token statistical information.
Charges are based on the total Token quantity.
     * @param Usage Token statistical information.
Charges are based on the total Token quantity.
     */
    public void setUsage(ChatUsage Usage) {
        this.Usage = Usage;
    }

    /**
     * Get RequestId for this request. 
     * @return Id RequestId for this request.
     */
    public String getId() {
        return this.Id;
    }

    /**
     * Set RequestId for this request.
     * @param Id RequestId for this request.
     */
    public void setId(String Id) {
        this.Id = Id;
    }

    /**
     * Get Response content. 
     * @return Choices Response content.
     */
    public Choice [] getChoices() {
        return this.Choices;
    }

    /**
     * Set Response content.
     * @param Choices Response content.
     */
    public void setChoices(Choice [] Choices) {
        this.Choices = Choices;
    }

    /**
     * Get Model name. 
     * @return Model Model name.
     */
    public String getModel() {
        return this.Model;
    }

    /**
     * Set Model name.
     * @param Model Model name.
     */
    public void setModel(String Model) {
        this.Model = Model;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. As a streaming response API, when the request is successfully completed, the RequestId will be placed in the Header "X-TC-RequestId" of the HTTP response. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. As a streaming response API, when the request is successfully completed, the RequestId will be placed in the Header "X-TC-RequestId" of the HTTP response.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. As a streaming response API, when the request is successfully completed, the RequestId will be placed in the Header "X-TC-RequestId" of the HTTP response.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. As a streaming response API, when the request is successfully completed, the RequestId will be placed in the Header "X-TC-RequestId" of the HTTP response.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public ChatCompletionsResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public ChatCompletionsResponse(ChatCompletionsResponse source) {
        if (source.Created != null) {
            this.Created = new Long(source.Created);
        }
        if (source.Usage != null) {
            this.Usage = new ChatUsage(source.Usage);
        }
        if (source.Id != null) {
            this.Id = new String(source.Id);
        }
        if (source.Choices != null) {
            this.Choices = new Choice[source.Choices.length];
            for (int i = 0; i < source.Choices.length; i++) {
                this.Choices[i] = new Choice(source.Choices[i]);
            }
        }
        if (source.Model != null) {
            this.Model = new String(source.Model);
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "Created", this.Created);
        this.setParamObj(map, prefix + "Usage.", this.Usage);
        this.setParamSimple(map, prefix + "Id", this.Id);
        this.setParamArrayObj(map, prefix + "Choices.", this.Choices);
        this.setParamSimple(map, prefix + "Model", this.Model);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

