/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.batch.v20170312.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeJobMonitorDataResponse extends AbstractModel {

    /**
    * Monitoring data granularity, measurement unit: second. Time granularity changes with the query time range. The smaller the query time range, the smaller the time granularity.
    */
    @SerializedName("Period")
    @Expose
    private Long Period;

    /**
    * The collected data is monitored. Timestamps and corresponding values have a one-to-one relationship. If the querying task retries and the collection time period involves multiple instances, values during specific periods are null, indicating no instance existence at the corresponding time and no corresponding monitoring data. The maximum number of null values between adjacent monitoring time periods is 10.
    */
    @SerializedName("DataPoints")
    @Expose
    private DataPointView DataPoints;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Monitoring data granularity, measurement unit: second. Time granularity changes with the query time range. The smaller the query time range, the smaller the time granularity. 
     * @return Period Monitoring data granularity, measurement unit: second. Time granularity changes with the query time range. The smaller the query time range, the smaller the time granularity.
     */
    public Long getPeriod() {
        return this.Period;
    }

    /**
     * Set Monitoring data granularity, measurement unit: second. Time granularity changes with the query time range. The smaller the query time range, the smaller the time granularity.
     * @param Period Monitoring data granularity, measurement unit: second. Time granularity changes with the query time range. The smaller the query time range, the smaller the time granularity.
     */
    public void setPeriod(Long Period) {
        this.Period = Period;
    }

    /**
     * Get The collected data is monitored. Timestamps and corresponding values have a one-to-one relationship. If the querying task retries and the collection time period involves multiple instances, values during specific periods are null, indicating no instance existence at the corresponding time and no corresponding monitoring data. The maximum number of null values between adjacent monitoring time periods is 10. 
     * @return DataPoints The collected data is monitored. Timestamps and corresponding values have a one-to-one relationship. If the querying task retries and the collection time period involves multiple instances, values during specific periods are null, indicating no instance existence at the corresponding time and no corresponding monitoring data. The maximum number of null values between adjacent monitoring time periods is 10.
     */
    public DataPointView getDataPoints() {
        return this.DataPoints;
    }

    /**
     * Set The collected data is monitored. Timestamps and corresponding values have a one-to-one relationship. If the querying task retries and the collection time period involves multiple instances, values during specific periods are null, indicating no instance existence at the corresponding time and no corresponding monitoring data. The maximum number of null values between adjacent monitoring time periods is 10.
     * @param DataPoints The collected data is monitored. Timestamps and corresponding values have a one-to-one relationship. If the querying task retries and the collection time period involves multiple instances, values during specific periods are null, indicating no instance existence at the corresponding time and no corresponding monitoring data. The maximum number of null values between adjacent monitoring time periods is 10.
     */
    public void setDataPoints(DataPointView DataPoints) {
        this.DataPoints = DataPoints;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeJobMonitorDataResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeJobMonitorDataResponse(DescribeJobMonitorDataResponse source) {
        if (source.Period != null) {
            this.Period = new Long(source.Period);
        }
        if (source.DataPoints != null) {
            this.DataPoints = new DataPointView(source.DataPoints);
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "Period", this.Period);
        this.setParamObj(map, prefix + "DataPoints.", this.DataPoints);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

