/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.monitor.v20230616.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class ListAIWorkbenchResourceInstancesResponse extends AbstractModel {

    /**
    * <p>Resource instance list</p>
    */
    @SerializedName("Instances")
    @Expose
    private ResourceInstance [] Instances;

    /**
    * <p>Pagination result</p>
    */
    @SerializedName("PageResult")
    @Expose
    private PageByNumResult PageResult;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get <p>Resource instance list</p> 
     * @return Instances <p>Resource instance list</p>
     */
    public ResourceInstance [] getInstances() {
        return this.Instances;
    }

    /**
     * Set <p>Resource instance list</p>
     * @param Instances <p>Resource instance list</p>
     */
    public void setInstances(ResourceInstance [] Instances) {
        this.Instances = Instances;
    }

    /**
     * Get <p>Pagination result</p> 
     * @return PageResult <p>Pagination result</p>
     */
    public PageByNumResult getPageResult() {
        return this.PageResult;
    }

    /**
     * Set <p>Pagination result</p>
     * @param PageResult <p>Pagination result</p>
     */
    public void setPageResult(PageByNumResult PageResult) {
        this.PageResult = PageResult;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public ListAIWorkbenchResourceInstancesResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public ListAIWorkbenchResourceInstancesResponse(ListAIWorkbenchResourceInstancesResponse source) {
        if (source.Instances != null) {
            this.Instances = new ResourceInstance[source.Instances.length];
            for (int i = 0; i < source.Instances.length; i++) {
                this.Instances[i] = new ResourceInstance(source.Instances[i]);
            }
        }
        if (source.PageResult != null) {
            this.PageResult = new PageByNumResult(source.PageResult);
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamArrayObj(map, prefix + "Instances.", this.Instances);
        this.setParamObj(map, prefix + "PageResult.", this.PageResult);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

