/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.mps.v20190612.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeAigcAudioTaskResponse extends AbstractModel {

    /**
    * <p>Current task status. WAIT: waiting. RUN: running. FAIL: failed. DONE: successful.</p>
    */
    @SerializedName("Status")
    @Expose
    private String Status;

    /**
    * <p>If the task status is FAIL, the failure information is returned.</p>
    */
    @SerializedName("Message")
    @Expose
    private String Message;

    /**
    * <p>Output audio information.</p>
    */
    @SerializedName("AudioInfos")
    @Expose
    private AigcAudioOutputAudioInfo [] AudioInfos;

    /**
    * <p>Output video information, which is only available for scenarios such as video dubbing.</p>
    */
    @SerializedName("VideoInfos")
    @Expose
    private AigcAudioOutputVideoInfo [] VideoInfos;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get <p>Current task status. WAIT: waiting. RUN: running. FAIL: failed. DONE: successful.</p> 
     * @return Status <p>Current task status. WAIT: waiting. RUN: running. FAIL: failed. DONE: successful.</p>
     */
    public String getStatus() {
        return this.Status;
    }

    /**
     * Set <p>Current task status. WAIT: waiting. RUN: running. FAIL: failed. DONE: successful.</p>
     * @param Status <p>Current task status. WAIT: waiting. RUN: running. FAIL: failed. DONE: successful.</p>
     */
    public void setStatus(String Status) {
        this.Status = Status;
    }

    /**
     * Get <p>If the task status is FAIL, the failure information is returned.</p> 
     * @return Message <p>If the task status is FAIL, the failure information is returned.</p>
     */
    public String getMessage() {
        return this.Message;
    }

    /**
     * Set <p>If the task status is FAIL, the failure information is returned.</p>
     * @param Message <p>If the task status is FAIL, the failure information is returned.</p>
     */
    public void setMessage(String Message) {
        this.Message = Message;
    }

    /**
     * Get <p>Output audio information.</p> 
     * @return AudioInfos <p>Output audio information.</p>
     */
    public AigcAudioOutputAudioInfo [] getAudioInfos() {
        return this.AudioInfos;
    }

    /**
     * Set <p>Output audio information.</p>
     * @param AudioInfos <p>Output audio information.</p>
     */
    public void setAudioInfos(AigcAudioOutputAudioInfo [] AudioInfos) {
        this.AudioInfos = AudioInfos;
    }

    /**
     * Get <p>Output video information, which is only available for scenarios such as video dubbing.</p> 
     * @return VideoInfos <p>Output video information, which is only available for scenarios such as video dubbing.</p>
     */
    public AigcAudioOutputVideoInfo [] getVideoInfos() {
        return this.VideoInfos;
    }

    /**
     * Set <p>Output video information, which is only available for scenarios such as video dubbing.</p>
     * @param VideoInfos <p>Output video information, which is only available for scenarios such as video dubbing.</p>
     */
    public void setVideoInfos(AigcAudioOutputVideoInfo [] VideoInfos) {
        this.VideoInfos = VideoInfos;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeAigcAudioTaskResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeAigcAudioTaskResponse(DescribeAigcAudioTaskResponse source) {
        if (source.Status != null) {
            this.Status = new String(source.Status);
        }
        if (source.Message != null) {
            this.Message = new String(source.Message);
        }
        if (source.AudioInfos != null) {
            this.AudioInfos = new AigcAudioOutputAudioInfo[source.AudioInfos.length];
            for (int i = 0; i < source.AudioInfos.length; i++) {
                this.AudioInfos[i] = new AigcAudioOutputAudioInfo(source.AudioInfos[i]);
            }
        }
        if (source.VideoInfos != null) {
            this.VideoInfos = new AigcAudioOutputVideoInfo[source.VideoInfos.length];
            for (int i = 0; i < source.VideoInfos.length; i++) {
                this.VideoInfos[i] = new AigcAudioOutputVideoInfo(source.VideoInfos[i]);
            }
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "Status", this.Status);
        this.setParamSimple(map, prefix + "Message", this.Message);
        this.setParamArrayObj(map, prefix + "AudioInfos.", this.AudioInfos);
        this.setParamArrayObj(map, prefix + "VideoInfos.", this.VideoInfos);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

