/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.mps.v20190612.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DetectVideoSubtitleAreaResponse extends AbstractModel {

    /**
    * <p>Video width.</p><p>Unit: px.</p>
    */
    @SerializedName("Width")
    @Expose
    private Long Width;

    /**
    * <p>Video height.</p><p>Unit: px.</p>
    */
    @SerializedName("Height")
    @Expose
    private Long Height;

    /**
    * <p>Detected subtitle box. If nothing is detected, the value is empty.</p>
    */
    @SerializedName("Result")
    @Expose
    private SubtitleArea [] Result;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get <p>Video width.</p><p>Unit: px.</p> 
     * @return Width <p>Video width.</p><p>Unit: px.</p>
     */
    public Long getWidth() {
        return this.Width;
    }

    /**
     * Set <p>Video width.</p><p>Unit: px.</p>
     * @param Width <p>Video width.</p><p>Unit: px.</p>
     */
    public void setWidth(Long Width) {
        this.Width = Width;
    }

    /**
     * Get <p>Video height.</p><p>Unit: px.</p> 
     * @return Height <p>Video height.</p><p>Unit: px.</p>
     */
    public Long getHeight() {
        return this.Height;
    }

    /**
     * Set <p>Video height.</p><p>Unit: px.</p>
     * @param Height <p>Video height.</p><p>Unit: px.</p>
     */
    public void setHeight(Long Height) {
        this.Height = Height;
    }

    /**
     * Get <p>Detected subtitle box. If nothing is detected, the value is empty.</p> 
     * @return Result <p>Detected subtitle box. If nothing is detected, the value is empty.</p>
     */
    public SubtitleArea [] getResult() {
        return this.Result;
    }

    /**
     * Set <p>Detected subtitle box. If nothing is detected, the value is empty.</p>
     * @param Result <p>Detected subtitle box. If nothing is detected, the value is empty.</p>
     */
    public void setResult(SubtitleArea [] Result) {
        this.Result = Result;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DetectVideoSubtitleAreaResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DetectVideoSubtitleAreaResponse(DetectVideoSubtitleAreaResponse source) {
        if (source.Width != null) {
            this.Width = new Long(source.Width);
        }
        if (source.Height != null) {
            this.Height = new Long(source.Height);
        }
        if (source.Result != null) {
            this.Result = new SubtitleArea[source.Result.length];
            for (int i = 0; i < source.Result.length; i++) {
                this.Result[i] = new SubtitleArea(source.Result[i]);
            }
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "Width", this.Width);
        this.setParamSimple(map, prefix + "Height", this.Height);
        this.setParamArrayObj(map, prefix + "Result.", this.Result);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

