/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.mps.v20190612.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class EmbeddingDataResponse extends AbstractModel {

    /**
    * <p>Embedding result</p>
    */
    @SerializedName("Data")
    @Expose
    private EmbeddingResultItem [] Data;

    /**
    * <p>Token usage of the embedding</p>
    */
    @SerializedName("Usage")
    @Expose
    private TokensUsage Usage;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get <p>Embedding result</p> 
     * @return Data <p>Embedding result</p>
     */
    public EmbeddingResultItem [] getData() {
        return this.Data;
    }

    /**
     * Set <p>Embedding result</p>
     * @param Data <p>Embedding result</p>
     */
    public void setData(EmbeddingResultItem [] Data) {
        this.Data = Data;
    }

    /**
     * Get <p>Token usage of the embedding</p> 
     * @return Usage <p>Token usage of the embedding</p>
     */
    public TokensUsage getUsage() {
        return this.Usage;
    }

    /**
     * Set <p>Token usage of the embedding</p>
     * @param Usage <p>Token usage of the embedding</p>
     */
    public void setUsage(TokensUsage Usage) {
        this.Usage = Usage;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public EmbeddingDataResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public EmbeddingDataResponse(EmbeddingDataResponse source) {
        if (source.Data != null) {
            this.Data = new EmbeddingResultItem[source.Data.length];
            for (int i = 0; i < source.Data.length; i++) {
                this.Data[i] = new EmbeddingResultItem(source.Data[i]);
            }
        }
        if (source.Usage != null) {
            this.Usage = new TokensUsage(source.Usage);
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamArrayObj(map, prefix + "Data.", this.Data);
        this.setParamObj(map, prefix + "Usage.", this.Usage);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

