/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.mps.v20190612.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class SyncDubbingResponse extends AbstractModel {

    /**
    * Error code. 0 is returned if the request is successful.
    */
    @SerializedName("ErrorCode")
    @Expose
    private Long ErrorCode;

    /**
    * Error message. success is returned if the request is successful.
    */
    @SerializedName("Msg")
    @Expose
    private String Msg;

    /**
    * Synthetic audio in Base64 encoding and WAV format.
Note: This field may return null, indicating that no valid values can be obtained.
    */
    @SerializedName("AudioData")
    @Expose
    private String AudioData;

    /**
    * 
    */
    @SerializedName("AudioUrl")
    @Expose
    private String AudioUrl;

    /**
    * Cloned voice type ID.
Note: This field may return null, indicating that no valid values can be obtained.
    */
    @SerializedName("VoiceId")
    @Expose
    private String VoiceId;

    /**
    * 
    */
    @SerializedName("ExtInfo")
    @Expose
    private String ExtInfo;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Error code. 0 is returned if the request is successful. 
     * @return ErrorCode Error code. 0 is returned if the request is successful.
     */
    public Long getErrorCode() {
        return this.ErrorCode;
    }

    /**
     * Set Error code. 0 is returned if the request is successful.
     * @param ErrorCode Error code. 0 is returned if the request is successful.
     */
    public void setErrorCode(Long ErrorCode) {
        this.ErrorCode = ErrorCode;
    }

    /**
     * Get Error message. success is returned if the request is successful. 
     * @return Msg Error message. success is returned if the request is successful.
     */
    public String getMsg() {
        return this.Msg;
    }

    /**
     * Set Error message. success is returned if the request is successful.
     * @param Msg Error message. success is returned if the request is successful.
     */
    public void setMsg(String Msg) {
        this.Msg = Msg;
    }

    /**
     * Get Synthetic audio in Base64 encoding and WAV format.
Note: This field may return null, indicating that no valid values can be obtained. 
     * @return AudioData Synthetic audio in Base64 encoding and WAV format.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public String getAudioData() {
        return this.AudioData;
    }

    /**
     * Set Synthetic audio in Base64 encoding and WAV format.
Note: This field may return null, indicating that no valid values can be obtained.
     * @param AudioData Synthetic audio in Base64 encoding and WAV format.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public void setAudioData(String AudioData) {
        this.AudioData = AudioData;
    }

    /**
     * Get  
     * @return AudioUrl 
     */
    public String getAudioUrl() {
        return this.AudioUrl;
    }

    /**
     * Set 
     * @param AudioUrl 
     */
    public void setAudioUrl(String AudioUrl) {
        this.AudioUrl = AudioUrl;
    }

    /**
     * Get Cloned voice type ID.
Note: This field may return null, indicating that no valid values can be obtained. 
     * @return VoiceId Cloned voice type ID.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public String getVoiceId() {
        return this.VoiceId;
    }

    /**
     * Set Cloned voice type ID.
Note: This field may return null, indicating that no valid values can be obtained.
     * @param VoiceId Cloned voice type ID.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public void setVoiceId(String VoiceId) {
        this.VoiceId = VoiceId;
    }

    /**
     * Get  
     * @return ExtInfo 
     */
    public String getExtInfo() {
        return this.ExtInfo;
    }

    /**
     * Set 
     * @param ExtInfo 
     */
    public void setExtInfo(String ExtInfo) {
        this.ExtInfo = ExtInfo;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public SyncDubbingResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public SyncDubbingResponse(SyncDubbingResponse source) {
        if (source.ErrorCode != null) {
            this.ErrorCode = new Long(source.ErrorCode);
        }
        if (source.Msg != null) {
            this.Msg = new String(source.Msg);
        }
        if (source.AudioData != null) {
            this.AudioData = new String(source.AudioData);
        }
        if (source.AudioUrl != null) {
            this.AudioUrl = new String(source.AudioUrl);
        }
        if (source.VoiceId != null) {
            this.VoiceId = new String(source.VoiceId);
        }
        if (source.ExtInfo != null) {
            this.ExtInfo = new String(source.ExtInfo);
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "ErrorCode", this.ErrorCode);
        this.setParamSimple(map, prefix + "Msg", this.Msg);
        this.setParamSimple(map, prefix + "AudioData", this.AudioData);
        this.setParamSimple(map, prefix + "AudioUrl", this.AudioUrl);
        this.setParamSimple(map, prefix + "VoiceId", this.VoiceId);
        this.setParamSimple(map, prefix + "ExtInfo", this.ExtInfo);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

