/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.apm.v20210622.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeApmSampleConfigResponse extends AbstractModel {

    /**
    * Sampling configuration list
Note: This field may return null, indicating that no valid values can be obtained.
    */
    @SerializedName("ApmSampleConfigs")
    @Expose
    private ApmSampleConfig [] ApmSampleConfigs;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Sampling configuration list
Note: This field may return null, indicating that no valid values can be obtained. 
     * @return ApmSampleConfigs Sampling configuration list
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public ApmSampleConfig [] getApmSampleConfigs() {
        return this.ApmSampleConfigs;
    }

    /**
     * Set Sampling configuration list
Note: This field may return null, indicating that no valid values can be obtained.
     * @param ApmSampleConfigs Sampling configuration list
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public void setApmSampleConfigs(ApmSampleConfig [] ApmSampleConfigs) {
        this.ApmSampleConfigs = ApmSampleConfigs;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeApmSampleConfigResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeApmSampleConfigResponse(DescribeApmSampleConfigResponse source) {
        if (source.ApmSampleConfigs != null) {
            this.ApmSampleConfigs = new ApmSampleConfig[source.ApmSampleConfigs.length];
            for (int i = 0; i < source.ApmSampleConfigs.length; i++) {
                this.ApmSampleConfigs[i] = new ApmSampleConfig(source.ApmSampleConfigs[i]);
            }
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamArrayObj(map, prefix + "ApmSampleConfigs.", this.ApmSampleConfigs);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

