/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.live.v20180801.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribePushBandwidthAndFluxListResponse extends AbstractModel {

    /**
    * Peak bandwidth timestamp, using UTC time format, e.g., 2019-01-08T10:00:00Z. Note: Beijing time value equals UTC time value + 8 hours, expressed in ISO 8601 standard format. For details, refer to ISO Date Format Description.(https://cloud.tencent.com/document/product/266/11732#I)
    */
    @SerializedName("PeakBandwidthTime")
    @Expose
    private String PeakBandwidthTime;

    /**
    * Peak bandwidth, measured in Mbps.
    */
    @SerializedName("PeakBandwidth")
    @Expose
    private Float PeakBandwidth;

    /**
    * 95th percentile peak bandwidth timestamp, using UTC time format, e.g., 2019-01-08T10:00:00Z. Note: Beijing time value equals UTC time value + 8 hours, expressed in ISO 8601 standard format. For details, refer to ISO Date Format Description.(https://cloud.tencent.com/document/product/266/11732#I).
    */
    @SerializedName("P95PeakBandwidthTime")
    @Expose
    private String P95PeakBandwidthTime;

    /**
    * 95th percentile peak bandwidth, measured in Mbps.
    */
    @SerializedName("P95PeakBandwidth")
    @Expose
    private Float P95PeakBandwidth;

    /**
    * Total traffic, measured in MB.
    */
    @SerializedName("SumFlux")
    @Expose
    private Float SumFlux;

    /**
    * Detailed data information.
    */
    @SerializedName("DataInfoList")
    @Expose
    private BillDataInfo [] DataInfoList;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Peak bandwidth timestamp, using UTC time format, e.g., 2019-01-08T10:00:00Z. Note: Beijing time value equals UTC time value + 8 hours, expressed in ISO 8601 standard format. For details, refer to ISO Date Format Description.(https://cloud.tencent.com/document/product/266/11732#I) 
     * @return PeakBandwidthTime Peak bandwidth timestamp, using UTC time format, e.g., 2019-01-08T10:00:00Z. Note: Beijing time value equals UTC time value + 8 hours, expressed in ISO 8601 standard format. For details, refer to ISO Date Format Description.(https://cloud.tencent.com/document/product/266/11732#I)
     */
    public String getPeakBandwidthTime() {
        return this.PeakBandwidthTime;
    }

    /**
     * Set Peak bandwidth timestamp, using UTC time format, e.g., 2019-01-08T10:00:00Z. Note: Beijing time value equals UTC time value + 8 hours, expressed in ISO 8601 standard format. For details, refer to ISO Date Format Description.(https://cloud.tencent.com/document/product/266/11732#I)
     * @param PeakBandwidthTime Peak bandwidth timestamp, using UTC time format, e.g., 2019-01-08T10:00:00Z. Note: Beijing time value equals UTC time value + 8 hours, expressed in ISO 8601 standard format. For details, refer to ISO Date Format Description.(https://cloud.tencent.com/document/product/266/11732#I)
     */
    public void setPeakBandwidthTime(String PeakBandwidthTime) {
        this.PeakBandwidthTime = PeakBandwidthTime;
    }

    /**
     * Get Peak bandwidth, measured in Mbps. 
     * @return PeakBandwidth Peak bandwidth, measured in Mbps.
     */
    public Float getPeakBandwidth() {
        return this.PeakBandwidth;
    }

    /**
     * Set Peak bandwidth, measured in Mbps.
     * @param PeakBandwidth Peak bandwidth, measured in Mbps.
     */
    public void setPeakBandwidth(Float PeakBandwidth) {
        this.PeakBandwidth = PeakBandwidth;
    }

    /**
     * Get 95th percentile peak bandwidth timestamp, using UTC time format, e.g., 2019-01-08T10:00:00Z. Note: Beijing time value equals UTC time value + 8 hours, expressed in ISO 8601 standard format. For details, refer to ISO Date Format Description.(https://cloud.tencent.com/document/product/266/11732#I). 
     * @return P95PeakBandwidthTime 95th percentile peak bandwidth timestamp, using UTC time format, e.g., 2019-01-08T10:00:00Z. Note: Beijing time value equals UTC time value + 8 hours, expressed in ISO 8601 standard format. For details, refer to ISO Date Format Description.(https://cloud.tencent.com/document/product/266/11732#I).
     */
    public String getP95PeakBandwidthTime() {
        return this.P95PeakBandwidthTime;
    }

    /**
     * Set 95th percentile peak bandwidth timestamp, using UTC time format, e.g., 2019-01-08T10:00:00Z. Note: Beijing time value equals UTC time value + 8 hours, expressed in ISO 8601 standard format. For details, refer to ISO Date Format Description.(https://cloud.tencent.com/document/product/266/11732#I).
     * @param P95PeakBandwidthTime 95th percentile peak bandwidth timestamp, using UTC time format, e.g., 2019-01-08T10:00:00Z. Note: Beijing time value equals UTC time value + 8 hours, expressed in ISO 8601 standard format. For details, refer to ISO Date Format Description.(https://cloud.tencent.com/document/product/266/11732#I).
     */
    public void setP95PeakBandwidthTime(String P95PeakBandwidthTime) {
        this.P95PeakBandwidthTime = P95PeakBandwidthTime;
    }

    /**
     * Get 95th percentile peak bandwidth, measured in Mbps. 
     * @return P95PeakBandwidth 95th percentile peak bandwidth, measured in Mbps.
     */
    public Float getP95PeakBandwidth() {
        return this.P95PeakBandwidth;
    }

    /**
     * Set 95th percentile peak bandwidth, measured in Mbps.
     * @param P95PeakBandwidth 95th percentile peak bandwidth, measured in Mbps.
     */
    public void setP95PeakBandwidth(Float P95PeakBandwidth) {
        this.P95PeakBandwidth = P95PeakBandwidth;
    }

    /**
     * Get Total traffic, measured in MB. 
     * @return SumFlux Total traffic, measured in MB.
     */
    public Float getSumFlux() {
        return this.SumFlux;
    }

    /**
     * Set Total traffic, measured in MB.
     * @param SumFlux Total traffic, measured in MB.
     */
    public void setSumFlux(Float SumFlux) {
        this.SumFlux = SumFlux;
    }

    /**
     * Get Detailed data information. 
     * @return DataInfoList Detailed data information.
     */
    public BillDataInfo [] getDataInfoList() {
        return this.DataInfoList;
    }

    /**
     * Set Detailed data information.
     * @param DataInfoList Detailed data information.
     */
    public void setDataInfoList(BillDataInfo [] DataInfoList) {
        this.DataInfoList = DataInfoList;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribePushBandwidthAndFluxListResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribePushBandwidthAndFluxListResponse(DescribePushBandwidthAndFluxListResponse source) {
        if (source.PeakBandwidthTime != null) {
            this.PeakBandwidthTime = new String(source.PeakBandwidthTime);
        }
        if (source.PeakBandwidth != null) {
            this.PeakBandwidth = new Float(source.PeakBandwidth);
        }
        if (source.P95PeakBandwidthTime != null) {
            this.P95PeakBandwidthTime = new String(source.P95PeakBandwidthTime);
        }
        if (source.P95PeakBandwidth != null) {
            this.P95PeakBandwidth = new Float(source.P95PeakBandwidth);
        }
        if (source.SumFlux != null) {
            this.SumFlux = new Float(source.SumFlux);
        }
        if (source.DataInfoList != null) {
            this.DataInfoList = new BillDataInfo[source.DataInfoList.length];
            for (int i = 0; i < source.DataInfoList.length; i++) {
                this.DataInfoList[i] = new BillDataInfo(source.DataInfoList[i]);
            }
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "PeakBandwidthTime", this.PeakBandwidthTime);
        this.setParamSimple(map, prefix + "PeakBandwidth", this.PeakBandwidth);
        this.setParamSimple(map, prefix + "P95PeakBandwidthTime", this.P95PeakBandwidthTime);
        this.setParamSimple(map, prefix + "P95PeakBandwidth", this.P95PeakBandwidth);
        this.setParamSimple(map, prefix + "SumFlux", this.SumFlux);
        this.setParamArrayObj(map, prefix + "DataInfoList.", this.DataInfoList);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

