/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.mna.v20210119.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class GetFlowStatisticByRegionResponse extends AbstractModel {

    /**
    * Traffic details
    */
    @SerializedName("NetDetails")
    @Expose
    private NetDetails [] NetDetails;

    /**
    * Search the maximum value of traffic usage in a time period (measurement unit: byte)
    */
    @SerializedName("MaxValue")
    @Expose
    private Float MaxValue;

    /**
    * Search time period traffic usage average (unit: byte)
    */
    @SerializedName("AvgValue")
    @Expose
    private Float AvgValue;

    /**
    * Search total traffic usage in the time period (unit: byte)
    */
    @SerializedName("TotalValue")
    @Expose
    private Float TotalValue;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Traffic details 
     * @return NetDetails Traffic details
     */
    public NetDetails [] getNetDetails() {
        return this.NetDetails;
    }

    /**
     * Set Traffic details
     * @param NetDetails Traffic details
     */
    public void setNetDetails(NetDetails [] NetDetails) {
        this.NetDetails = NetDetails;
    }

    /**
     * Get Search the maximum value of traffic usage in a time period (measurement unit: byte) 
     * @return MaxValue Search the maximum value of traffic usage in a time period (measurement unit: byte)
     */
    public Float getMaxValue() {
        return this.MaxValue;
    }

    /**
     * Set Search the maximum value of traffic usage in a time period (measurement unit: byte)
     * @param MaxValue Search the maximum value of traffic usage in a time period (measurement unit: byte)
     */
    public void setMaxValue(Float MaxValue) {
        this.MaxValue = MaxValue;
    }

    /**
     * Get Search time period traffic usage average (unit: byte) 
     * @return AvgValue Search time period traffic usage average (unit: byte)
     */
    public Float getAvgValue() {
        return this.AvgValue;
    }

    /**
     * Set Search time period traffic usage average (unit: byte)
     * @param AvgValue Search time period traffic usage average (unit: byte)
     */
    public void setAvgValue(Float AvgValue) {
        this.AvgValue = AvgValue;
    }

    /**
     * Get Search total traffic usage in the time period (unit: byte) 
     * @return TotalValue Search total traffic usage in the time period (unit: byte)
     */
    public Float getTotalValue() {
        return this.TotalValue;
    }

    /**
     * Set Search total traffic usage in the time period (unit: byte)
     * @param TotalValue Search total traffic usage in the time period (unit: byte)
     */
    public void setTotalValue(Float TotalValue) {
        this.TotalValue = TotalValue;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public GetFlowStatisticByRegionResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public GetFlowStatisticByRegionResponse(GetFlowStatisticByRegionResponse source) {
        if (source.NetDetails != null) {
            this.NetDetails = new NetDetails[source.NetDetails.length];
            for (int i = 0; i < source.NetDetails.length; i++) {
                this.NetDetails[i] = new NetDetails(source.NetDetails[i]);
            }
        }
        if (source.MaxValue != null) {
            this.MaxValue = new Float(source.MaxValue);
        }
        if (source.AvgValue != null) {
            this.AvgValue = new Float(source.AvgValue);
        }
        if (source.TotalValue != null) {
            this.TotalValue = new Float(source.TotalValue);
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamArrayObj(map, prefix + "NetDetails.", this.NetDetails);
        this.setParamSimple(map, prefix + "MaxValue", this.MaxValue);
        this.setParamSimple(map, prefix + "AvgValue", this.AvgValue);
        this.setParamSimple(map, prefix + "TotalValue", this.TotalValue);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

