/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.es.v20250101.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class GetDocumentParseResultResponse extends AbstractModel {

    /**
    * Task status, -1: failure, 0: running, 1: success.
    */
    @SerializedName("Status")
    @Expose
    private Long Status;

    /**
    * Result file.
    */
    @SerializedName("DocumentParseResultUrl")
    @Expose
    private String DocumentParseResultUrl;

    /**
    * Failed page number.
Note: This field may return null, indicating that no valid values can be obtained.
    */
    @SerializedName("FailedPages")
    @Expose
    private Long [] FailedPages;

    /**
    * Page number consumption
    */
    @SerializedName("Usage")
    @Expose
    private PageUsage Usage;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Task status, -1: failure, 0: running, 1: success. 
     * @return Status Task status, -1: failure, 0: running, 1: success.
     */
    public Long getStatus() {
        return this.Status;
    }

    /**
     * Set Task status, -1: failure, 0: running, 1: success.
     * @param Status Task status, -1: failure, 0: running, 1: success.
     */
    public void setStatus(Long Status) {
        this.Status = Status;
    }

    /**
     * Get Result file. 
     * @return DocumentParseResultUrl Result file.
     */
    public String getDocumentParseResultUrl() {
        return this.DocumentParseResultUrl;
    }

    /**
     * Set Result file.
     * @param DocumentParseResultUrl Result file.
     */
    public void setDocumentParseResultUrl(String DocumentParseResultUrl) {
        this.DocumentParseResultUrl = DocumentParseResultUrl;
    }

    /**
     * Get Failed page number.
Note: This field may return null, indicating that no valid values can be obtained. 
     * @return FailedPages Failed page number.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public Long [] getFailedPages() {
        return this.FailedPages;
    }

    /**
     * Set Failed page number.
Note: This field may return null, indicating that no valid values can be obtained.
     * @param FailedPages Failed page number.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public void setFailedPages(Long [] FailedPages) {
        this.FailedPages = FailedPages;
    }

    /**
     * Get Page number consumption 
     * @return Usage Page number consumption
     */
    public PageUsage getUsage() {
        return this.Usage;
    }

    /**
     * Set Page number consumption
     * @param Usage Page number consumption
     */
    public void setUsage(PageUsage Usage) {
        this.Usage = Usage;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public GetDocumentParseResultResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public GetDocumentParseResultResponse(GetDocumentParseResultResponse source) {
        if (source.Status != null) {
            this.Status = new Long(source.Status);
        }
        if (source.DocumentParseResultUrl != null) {
            this.DocumentParseResultUrl = new String(source.DocumentParseResultUrl);
        }
        if (source.FailedPages != null) {
            this.FailedPages = new Long[source.FailedPages.length];
            for (int i = 0; i < source.FailedPages.length; i++) {
                this.FailedPages[i] = new Long(source.FailedPages[i]);
            }
        }
        if (source.Usage != null) {
            this.Usage = new PageUsage(source.Usage);
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "Status", this.Status);
        this.setParamSimple(map, prefix + "DocumentParseResultUrl", this.DocumentParseResultUrl);
        this.setParamArraySimple(map, prefix + "FailedPages.", this.FailedPages);
        this.setParamObj(map, prefix + "Usage.", this.Usage);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

