/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.faceid.v20180301.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class BankCard4EVerificationResponse extends AbstractModel {

    /**
    * Verification result code.
-Result code for charges
'0': 'Authentication passed'.
'-1': 'Authentication failed'.
'-6': 'Cardholder information is incorrect'.
'-7': 'Cardless payment not enabled'.
'-8': 'Card confiscated'.
'-9': 'Invalid card number'.
'-10': 'No corresponding issuing bank for this card'.
'-11': 'The card is uninitialized or a Sleep Card'.
'-12': 'Cheat card, card confiscation'.
'-13': 'Reported lost'.
'-14': 'The card has expired.'
'-15': 'Restricted card'.
'-16': 'Exceeded the number of password errors'.
'-17': 'Issuer does not support this transaction'.
'-21': 'Card status exception or card number error'.

-Result code with no charge
'-2': 'Name verification failed'.
'-3': 'Identity number error'.
'-4': 'Incorrect bank card number format'.
'-5': 'Invalid phone number'.
'-18': 'Verification Center Service busy'.
'-19': 'Exceeded maximum verification attempts. Please retry the next day.'
'-20': 'The ID number is not currently supported for verification. Currently only support second-generation resident identity card.'
    */
    @SerializedName("Result")
    @Expose
    private String Result;

    /**
    * Business result description.
    */
    @SerializedName("Description")
    @Expose
    private String Description;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Verification result code.
-Result code for charges
'0': 'Authentication passed'.
'-1': 'Authentication failed'.
'-6': 'Cardholder information is incorrect'.
'-7': 'Cardless payment not enabled'.
'-8': 'Card confiscated'.
'-9': 'Invalid card number'.
'-10': 'No corresponding issuing bank for this card'.
'-11': 'The card is uninitialized or a Sleep Card'.
'-12': 'Cheat card, card confiscation'.
'-13': 'Reported lost'.
'-14': 'The card has expired.'
'-15': 'Restricted card'.
'-16': 'Exceeded the number of password errors'.
'-17': 'Issuer does not support this transaction'.
'-21': 'Card status exception or card number error'.

-Result code with no charge
'-2': 'Name verification failed'.
'-3': 'Identity number error'.
'-4': 'Incorrect bank card number format'.
'-5': 'Invalid phone number'.
'-18': 'Verification Center Service busy'.
'-19': 'Exceeded maximum verification attempts. Please retry the next day.'
'-20': 'The ID number is not currently supported for verification. Currently only support second-generation resident identity card.' 
     * @return Result Verification result code.
-Result code for charges
'0': 'Authentication passed'.
'-1': 'Authentication failed'.
'-6': 'Cardholder information is incorrect'.
'-7': 'Cardless payment not enabled'.
'-8': 'Card confiscated'.
'-9': 'Invalid card number'.
'-10': 'No corresponding issuing bank for this card'.
'-11': 'The card is uninitialized or a Sleep Card'.
'-12': 'Cheat card, card confiscation'.
'-13': 'Reported lost'.
'-14': 'The card has expired.'
'-15': 'Restricted card'.
'-16': 'Exceeded the number of password errors'.
'-17': 'Issuer does not support this transaction'.
'-21': 'Card status exception or card number error'.

-Result code with no charge
'-2': 'Name verification failed'.
'-3': 'Identity number error'.
'-4': 'Incorrect bank card number format'.
'-5': 'Invalid phone number'.
'-18': 'Verification Center Service busy'.
'-19': 'Exceeded maximum verification attempts. Please retry the next day.'
'-20': 'The ID number is not currently supported for verification. Currently only support second-generation resident identity card.'
     */
    public String getResult() {
        return this.Result;
    }

    /**
     * Set Verification result code.
-Result code for charges
'0': 'Authentication passed'.
'-1': 'Authentication failed'.
'-6': 'Cardholder information is incorrect'.
'-7': 'Cardless payment not enabled'.
'-8': 'Card confiscated'.
'-9': 'Invalid card number'.
'-10': 'No corresponding issuing bank for this card'.
'-11': 'The card is uninitialized or a Sleep Card'.
'-12': 'Cheat card, card confiscation'.
'-13': 'Reported lost'.
'-14': 'The card has expired.'
'-15': 'Restricted card'.
'-16': 'Exceeded the number of password errors'.
'-17': 'Issuer does not support this transaction'.
'-21': 'Card status exception or card number error'.

-Result code with no charge
'-2': 'Name verification failed'.
'-3': 'Identity number error'.
'-4': 'Incorrect bank card number format'.
'-5': 'Invalid phone number'.
'-18': 'Verification Center Service busy'.
'-19': 'Exceeded maximum verification attempts. Please retry the next day.'
'-20': 'The ID number is not currently supported for verification. Currently only support second-generation resident identity card.'
     * @param Result Verification result code.
-Result code for charges
'0': 'Authentication passed'.
'-1': 'Authentication failed'.
'-6': 'Cardholder information is incorrect'.
'-7': 'Cardless payment not enabled'.
'-8': 'Card confiscated'.
'-9': 'Invalid card number'.
'-10': 'No corresponding issuing bank for this card'.
'-11': 'The card is uninitialized or a Sleep Card'.
'-12': 'Cheat card, card confiscation'.
'-13': 'Reported lost'.
'-14': 'The card has expired.'
'-15': 'Restricted card'.
'-16': 'Exceeded the number of password errors'.
'-17': 'Issuer does not support this transaction'.
'-21': 'Card status exception or card number error'.

-Result code with no charge
'-2': 'Name verification failed'.
'-3': 'Identity number error'.
'-4': 'Incorrect bank card number format'.
'-5': 'Invalid phone number'.
'-18': 'Verification Center Service busy'.
'-19': 'Exceeded maximum verification attempts. Please retry the next day.'
'-20': 'The ID number is not currently supported for verification. Currently only support second-generation resident identity card.'
     */
    public void setResult(String Result) {
        this.Result = Result;
    }

    /**
     * Get Business result description. 
     * @return Description Business result description.
     */
    public String getDescription() {
        return this.Description;
    }

    /**
     * Set Business result description.
     * @param Description Business result description.
     */
    public void setDescription(String Description) {
        this.Description = Description;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public BankCard4EVerificationResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public BankCard4EVerificationResponse(BankCard4EVerificationResponse source) {
        if (source.Result != null) {
            this.Result = new String(source.Result);
        }
        if (source.Description != null) {
            this.Description = new String(source.Description);
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "Result", this.Result);
        this.setParamSimple(map, prefix + "Description", this.Description);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

