/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.faceid.v20180301.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class IdCardOCRVerificationResponse extends AbstractModel {

    /**
    * Verification result code. Billing is as follows.
-Result code for charges
The name and identity card number match.
-Name and ID card number mismatch.
-Result code with no charge
-2: Invalid ID number (incorrect length or check digit).
-3: Invalid name (incorrect length or format).
-4: Document library service exception.
-5: No ID card record found in the document library.
-6: The authoritative comparison system is being upgraded. Try again later.
-7: Authentication attempts exceeded the daily limit.
    */
    @SerializedName("Result")
    @Expose
    private String Result;

    /**
    * Business result description.
    */
    @SerializedName("Description")
    @Expose
    private String Description;

    /**
    * Name to verify.
    */
    @SerializedName("Name")
    @Expose
    private String Name;

    /**
    * Identity card number to verify.
    */
    @SerializedName("IdCard")
    @Expose
    private String IdCard;

    /**
    * Gender obtained by OCR.
Note: This field may return null, indicating that no valid values can be obtained.
    */
    @SerializedName("Sex")
    @Expose
    private String Sex;

    /**
    * Ethnicity obtained by OCR.
Note: This field may return null, indicating that no valid values can be obtained.
    */
    @SerializedName("Nation")
    @Expose
    private String Nation;

    /**
    * Birthday obtained by OCR.
Note: This field may return null, indicating that no valid values can be obtained.
    */
    @SerializedName("Birth")
    @Expose
    private String Birth;

    /**
    * Address obtained by OCR.
Note: This field may return null, indicating that no valid values can be obtained.
    */
    @SerializedName("Address")
    @Expose
    private String Address;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Verification result code. Billing is as follows.
-Result code for charges
The name and identity card number match.
-Name and ID card number mismatch.
-Result code with no charge
-2: Invalid ID number (incorrect length or check digit).
-3: Invalid name (incorrect length or format).
-4: Document library service exception.
-5: No ID card record found in the document library.
-6: The authoritative comparison system is being upgraded. Try again later.
-7: Authentication attempts exceeded the daily limit. 
     * @return Result Verification result code. Billing is as follows.
-Result code for charges
The name and identity card number match.
-Name and ID card number mismatch.
-Result code with no charge
-2: Invalid ID number (incorrect length or check digit).
-3: Invalid name (incorrect length or format).
-4: Document library service exception.
-5: No ID card record found in the document library.
-6: The authoritative comparison system is being upgraded. Try again later.
-7: Authentication attempts exceeded the daily limit.
     */
    public String getResult() {
        return this.Result;
    }

    /**
     * Set Verification result code. Billing is as follows.
-Result code for charges
The name and identity card number match.
-Name and ID card number mismatch.
-Result code with no charge
-2: Invalid ID number (incorrect length or check digit).
-3: Invalid name (incorrect length or format).
-4: Document library service exception.
-5: No ID card record found in the document library.
-6: The authoritative comparison system is being upgraded. Try again later.
-7: Authentication attempts exceeded the daily limit.
     * @param Result Verification result code. Billing is as follows.
-Result code for charges
The name and identity card number match.
-Name and ID card number mismatch.
-Result code with no charge
-2: Invalid ID number (incorrect length or check digit).
-3: Invalid name (incorrect length or format).
-4: Document library service exception.
-5: No ID card record found in the document library.
-6: The authoritative comparison system is being upgraded. Try again later.
-7: Authentication attempts exceeded the daily limit.
     */
    public void setResult(String Result) {
        this.Result = Result;
    }

    /**
     * Get Business result description. 
     * @return Description Business result description.
     */
    public String getDescription() {
        return this.Description;
    }

    /**
     * Set Business result description.
     * @param Description Business result description.
     */
    public void setDescription(String Description) {
        this.Description = Description;
    }

    /**
     * Get Name to verify. 
     * @return Name Name to verify.
     */
    public String getName() {
        return this.Name;
    }

    /**
     * Set Name to verify.
     * @param Name Name to verify.
     */
    public void setName(String Name) {
        this.Name = Name;
    }

    /**
     * Get Identity card number to verify. 
     * @return IdCard Identity card number to verify.
     */
    public String getIdCard() {
        return this.IdCard;
    }

    /**
     * Set Identity card number to verify.
     * @param IdCard Identity card number to verify.
     */
    public void setIdCard(String IdCard) {
        this.IdCard = IdCard;
    }

    /**
     * Get Gender obtained by OCR.
Note: This field may return null, indicating that no valid values can be obtained. 
     * @return Sex Gender obtained by OCR.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public String getSex() {
        return this.Sex;
    }

    /**
     * Set Gender obtained by OCR.
Note: This field may return null, indicating that no valid values can be obtained.
     * @param Sex Gender obtained by OCR.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public void setSex(String Sex) {
        this.Sex = Sex;
    }

    /**
     * Get Ethnicity obtained by OCR.
Note: This field may return null, indicating that no valid values can be obtained. 
     * @return Nation Ethnicity obtained by OCR.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public String getNation() {
        return this.Nation;
    }

    /**
     * Set Ethnicity obtained by OCR.
Note: This field may return null, indicating that no valid values can be obtained.
     * @param Nation Ethnicity obtained by OCR.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public void setNation(String Nation) {
        this.Nation = Nation;
    }

    /**
     * Get Birthday obtained by OCR.
Note: This field may return null, indicating that no valid values can be obtained. 
     * @return Birth Birthday obtained by OCR.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public String getBirth() {
        return this.Birth;
    }

    /**
     * Set Birthday obtained by OCR.
Note: This field may return null, indicating that no valid values can be obtained.
     * @param Birth Birthday obtained by OCR.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public void setBirth(String Birth) {
        this.Birth = Birth;
    }

    /**
     * Get Address obtained by OCR.
Note: This field may return null, indicating that no valid values can be obtained. 
     * @return Address Address obtained by OCR.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public String getAddress() {
        return this.Address;
    }

    /**
     * Set Address obtained by OCR.
Note: This field may return null, indicating that no valid values can be obtained.
     * @param Address Address obtained by OCR.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public void setAddress(String Address) {
        this.Address = Address;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public IdCardOCRVerificationResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public IdCardOCRVerificationResponse(IdCardOCRVerificationResponse source) {
        if (source.Result != null) {
            this.Result = new String(source.Result);
        }
        if (source.Description != null) {
            this.Description = new String(source.Description);
        }
        if (source.Name != null) {
            this.Name = new String(source.Name);
        }
        if (source.IdCard != null) {
            this.IdCard = new String(source.IdCard);
        }
        if (source.Sex != null) {
            this.Sex = new String(source.Sex);
        }
        if (source.Nation != null) {
            this.Nation = new String(source.Nation);
        }
        if (source.Birth != null) {
            this.Birth = new String(source.Birth);
        }
        if (source.Address != null) {
            this.Address = new String(source.Address);
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "Result", this.Result);
        this.setParamSimple(map, prefix + "Description", this.Description);
        this.setParamSimple(map, prefix + "Name", this.Name);
        this.setParamSimple(map, prefix + "IdCard", this.IdCard);
        this.setParamSimple(map, prefix + "Sex", this.Sex);
        this.setParamSimple(map, prefix + "Nation", this.Nation);
        this.setParamSimple(map, prefix + "Birth", this.Birth);
        this.setParamSimple(map, prefix + "Address", this.Address);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

