/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.ssl.v20191205.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class CheckCertificateDomainVerificationResponse extends AbstractModel {

    /**
    * Domain validation result list. If the cert is bound to multiple domain names, the return array contains multiple items.
Note: This field may return null, indicating that no valid values can be obtained.
    */
    @SerializedName("VerificationResults")
    @Expose
    private DomainValidationResult [] VerificationResults;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Domain validation result list. If the cert is bound to multiple domain names, the return array contains multiple items.
Note: This field may return null, indicating that no valid values can be obtained. 
     * @return VerificationResults Domain validation result list. If the cert is bound to multiple domain names, the return array contains multiple items.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public DomainValidationResult [] getVerificationResults() {
        return this.VerificationResults;
    }

    /**
     * Set Domain validation result list. If the cert is bound to multiple domain names, the return array contains multiple items.
Note: This field may return null, indicating that no valid values can be obtained.
     * @param VerificationResults Domain validation result list. If the cert is bound to multiple domain names, the return array contains multiple items.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public void setVerificationResults(DomainValidationResult [] VerificationResults) {
        this.VerificationResults = VerificationResults;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public CheckCertificateDomainVerificationResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public CheckCertificateDomainVerificationResponse(CheckCertificateDomainVerificationResponse source) {
        if (source.VerificationResults != null) {
            this.VerificationResults = new DomainValidationResult[source.VerificationResults.length];
            for (int i = 0; i < source.VerificationResults.length; i++) {
                this.VerificationResults[i] = new DomainValidationResult(source.VerificationResults[i]);
            }
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamArrayObj(map, prefix + "VerificationResults.", this.VerificationResults);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

