/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.alb.v20251030.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeListenerHealthStatusResponse extends AbstractModel {

    /**
    * Listener ID, format: lst- followed by 8 alphanumeric characters.
    */
    @SerializedName("ListenerId")
    @Expose
    private String ListenerId;

    /**
    * Listener port.
    */
    @SerializedName("ListenerPort")
    @Expose
    private String ListenerPort;

    /**
    * Listener protocol.
    */
    @SerializedName("ListenerProtocol")
    @Expose
    private String ListenerProtocol;

    /**
    * Token for the next query. If it is empty, this is the last page.
    */
    @SerializedName("NextToken")
    @Expose
    private String NextToken;

    /**
    * Health status of the forwarding rule.
    */
    @SerializedName("RuleHealthStatusInfos")
    @Expose
    private RuleHealthStatusInfo [] RuleHealthStatusInfos;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Listener ID, format: lst- followed by 8 alphanumeric characters. 
     * @return ListenerId Listener ID, format: lst- followed by 8 alphanumeric characters.
     */
    public String getListenerId() {
        return this.ListenerId;
    }

    /**
     * Set Listener ID, format: lst- followed by 8 alphanumeric characters.
     * @param ListenerId Listener ID, format: lst- followed by 8 alphanumeric characters.
     */
    public void setListenerId(String ListenerId) {
        this.ListenerId = ListenerId;
    }

    /**
     * Get Listener port. 
     * @return ListenerPort Listener port.
     */
    public String getListenerPort() {
        return this.ListenerPort;
    }

    /**
     * Set Listener port.
     * @param ListenerPort Listener port.
     */
    public void setListenerPort(String ListenerPort) {
        this.ListenerPort = ListenerPort;
    }

    /**
     * Get Listener protocol. 
     * @return ListenerProtocol Listener protocol.
     */
    public String getListenerProtocol() {
        return this.ListenerProtocol;
    }

    /**
     * Set Listener protocol.
     * @param ListenerProtocol Listener protocol.
     */
    public void setListenerProtocol(String ListenerProtocol) {
        this.ListenerProtocol = ListenerProtocol;
    }

    /**
     * Get Token for the next query. If it is empty, this is the last page. 
     * @return NextToken Token for the next query. If it is empty, this is the last page.
     */
    public String getNextToken() {
        return this.NextToken;
    }

    /**
     * Set Token for the next query. If it is empty, this is the last page.
     * @param NextToken Token for the next query. If it is empty, this is the last page.
     */
    public void setNextToken(String NextToken) {
        this.NextToken = NextToken;
    }

    /**
     * Get Health status of the forwarding rule. 
     * @return RuleHealthStatusInfos Health status of the forwarding rule.
     */
    public RuleHealthStatusInfo [] getRuleHealthStatusInfos() {
        return this.RuleHealthStatusInfos;
    }

    /**
     * Set Health status of the forwarding rule.
     * @param RuleHealthStatusInfos Health status of the forwarding rule.
     */
    public void setRuleHealthStatusInfos(RuleHealthStatusInfo [] RuleHealthStatusInfos) {
        this.RuleHealthStatusInfos = RuleHealthStatusInfos;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeListenerHealthStatusResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeListenerHealthStatusResponse(DescribeListenerHealthStatusResponse source) {
        if (source.ListenerId != null) {
            this.ListenerId = new String(source.ListenerId);
        }
        if (source.ListenerPort != null) {
            this.ListenerPort = new String(source.ListenerPort);
        }
        if (source.ListenerProtocol != null) {
            this.ListenerProtocol = new String(source.ListenerProtocol);
        }
        if (source.NextToken != null) {
            this.NextToken = new String(source.NextToken);
        }
        if (source.RuleHealthStatusInfos != null) {
            this.RuleHealthStatusInfos = new RuleHealthStatusInfo[source.RuleHealthStatusInfos.length];
            for (int i = 0; i < source.RuleHealthStatusInfos.length; i++) {
                this.RuleHealthStatusInfos[i] = new RuleHealthStatusInfo(source.RuleHealthStatusInfos[i]);
            }
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "ListenerId", this.ListenerId);
        this.setParamSimple(map, prefix + "ListenerPort", this.ListenerPort);
        this.setParamSimple(map, prefix + "ListenerProtocol", this.ListenerProtocol);
        this.setParamSimple(map, prefix + "NextToken", this.NextToken);
        this.setParamArrayObj(map, prefix + "RuleHealthStatusInfos.", this.RuleHealthStatusInfos);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

