/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.cwp.v20180228.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeAssetWebServiceInfoListResponse extends AbstractModel {

    /**
    * List
Note: This field may return null, indicating that no valid values can be obtained.
    */
    @SerializedName("WebServices")
    @Expose
    private AssetWebServiceBaseInfo [] WebServices;

    /**
    * Total number
    */
    @SerializedName("Total")
    @Expose
    private Long Total;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get List
Note: This field may return null, indicating that no valid values can be obtained. 
     * @return WebServices List
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public AssetWebServiceBaseInfo [] getWebServices() {
        return this.WebServices;
    }

    /**
     * Set List
Note: This field may return null, indicating that no valid values can be obtained.
     * @param WebServices List
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public void setWebServices(AssetWebServiceBaseInfo [] WebServices) {
        this.WebServices = WebServices;
    }

    /**
     * Get Total number 
     * @return Total Total number
     */
    public Long getTotal() {
        return this.Total;
    }

    /**
     * Set Total number
     * @param Total Total number
     */
    public void setTotal(Long Total) {
        this.Total = Total;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeAssetWebServiceInfoListResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeAssetWebServiceInfoListResponse(DescribeAssetWebServiceInfoListResponse source) {
        if (source.WebServices != null) {
            this.WebServices = new AssetWebServiceBaseInfo[source.WebServices.length];
            for (int i = 0; i < source.WebServices.length; i++) {
                this.WebServices[i] = new AssetWebServiceBaseInfo(source.WebServices[i]);
            }
        }
        if (source.Total != null) {
            this.Total = new Long(source.Total);
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamArrayObj(map, prefix + "WebServices.", this.WebServices);
        this.setParamSimple(map, prefix + "Total", this.Total);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

