/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.cwp.v20180228.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeReverseShellSystemPolicyConfigResponse extends AbstractModel {

    /**
    * <p>Display intranet alerts</p>
    */
    @SerializedName("InnerNetAlarmShow")
    @Expose
    private Boolean InnerNetAlarmShow;

    /**
    * <p>Display intranet IP addresses</p>
    */
    @SerializedName("InnerIPShow")
    @Expose
    private Boolean InnerIPShow;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get <p>Display intranet alerts</p> 
     * @return InnerNetAlarmShow <p>Display intranet alerts</p>
     */
    public Boolean getInnerNetAlarmShow() {
        return this.InnerNetAlarmShow;
    }

    /**
     * Set <p>Display intranet alerts</p>
     * @param InnerNetAlarmShow <p>Display intranet alerts</p>
     */
    public void setInnerNetAlarmShow(Boolean InnerNetAlarmShow) {
        this.InnerNetAlarmShow = InnerNetAlarmShow;
    }

    /**
     * Get <p>Display intranet IP addresses</p> 
     * @return InnerIPShow <p>Display intranet IP addresses</p>
     */
    public Boolean getInnerIPShow() {
        return this.InnerIPShow;
    }

    /**
     * Set <p>Display intranet IP addresses</p>
     * @param InnerIPShow <p>Display intranet IP addresses</p>
     */
    public void setInnerIPShow(Boolean InnerIPShow) {
        this.InnerIPShow = InnerIPShow;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeReverseShellSystemPolicyConfigResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeReverseShellSystemPolicyConfigResponse(DescribeReverseShellSystemPolicyConfigResponse source) {
        if (source.InnerNetAlarmShow != null) {
            this.InnerNetAlarmShow = new Boolean(source.InnerNetAlarmShow);
        }
        if (source.InnerIPShow != null) {
            this.InnerIPShow = new Boolean(source.InnerIPShow);
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "InnerNetAlarmShow", this.InnerNetAlarmShow);
        this.setParamSimple(map, prefix + "InnerIPShow", this.InnerIPShow);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

