/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.cdb.v20170320.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeAuditConfigResponse extends AbstractModel {

    /**
    * Audit log retention period. Valid values: [0, 7, 30, 180, 365, 1095, 1825].
    */
    @SerializedName("LogExpireDay")
    @Expose
    private Long LogExpireDay;

    /**
    * Audit log storage type. Valid value: "storage" - Storage type.
    */
    @SerializedName("LogType")
    @Expose
    private String LogType;

    /**
    * Whether the audit service is being disabled. Valid values: "false" - No, "true" - Yes.
    */
    @SerializedName("IsClosing")
    @Expose
    private String IsClosing;

    /**
    * Whether the audit service is being enabled. Valid values: "false" - No, "true" - Yes.
    */
    @SerializedName("IsOpening")
    @Expose
    private String IsOpening;

    /**
    * Time when the audit service was activated.
    */
    @SerializedName("CreateTime")
    @Expose
    private String CreateTime;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Audit log retention period. Valid values: [0, 7, 30, 180, 365, 1095, 1825]. 
     * @return LogExpireDay Audit log retention period. Valid values: [0, 7, 30, 180, 365, 1095, 1825].
     */
    public Long getLogExpireDay() {
        return this.LogExpireDay;
    }

    /**
     * Set Audit log retention period. Valid values: [0, 7, 30, 180, 365, 1095, 1825].
     * @param LogExpireDay Audit log retention period. Valid values: [0, 7, 30, 180, 365, 1095, 1825].
     */
    public void setLogExpireDay(Long LogExpireDay) {
        this.LogExpireDay = LogExpireDay;
    }

    /**
     * Get Audit log storage type. Valid value: "storage" - Storage type. 
     * @return LogType Audit log storage type. Valid value: "storage" - Storage type.
     */
    public String getLogType() {
        return this.LogType;
    }

    /**
     * Set Audit log storage type. Valid value: "storage" - Storage type.
     * @param LogType Audit log storage type. Valid value: "storage" - Storage type.
     */
    public void setLogType(String LogType) {
        this.LogType = LogType;
    }

    /**
     * Get Whether the audit service is being disabled. Valid values: "false" - No, "true" - Yes. 
     * @return IsClosing Whether the audit service is being disabled. Valid values: "false" - No, "true" - Yes.
     */
    public String getIsClosing() {
        return this.IsClosing;
    }

    /**
     * Set Whether the audit service is being disabled. Valid values: "false" - No, "true" - Yes.
     * @param IsClosing Whether the audit service is being disabled. Valid values: "false" - No, "true" - Yes.
     */
    public void setIsClosing(String IsClosing) {
        this.IsClosing = IsClosing;
    }

    /**
     * Get Whether the audit service is being enabled. Valid values: "false" - No, "true" - Yes. 
     * @return IsOpening Whether the audit service is being enabled. Valid values: "false" - No, "true" - Yes.
     */
    public String getIsOpening() {
        return this.IsOpening;
    }

    /**
     * Set Whether the audit service is being enabled. Valid values: "false" - No, "true" - Yes.
     * @param IsOpening Whether the audit service is being enabled. Valid values: "false" - No, "true" - Yes.
     */
    public void setIsOpening(String IsOpening) {
        this.IsOpening = IsOpening;
    }

    /**
     * Get Time when the audit service was activated. 
     * @return CreateTime Time when the audit service was activated.
     */
    public String getCreateTime() {
        return this.CreateTime;
    }

    /**
     * Set Time when the audit service was activated.
     * @param CreateTime Time when the audit service was activated.
     */
    public void setCreateTime(String CreateTime) {
        this.CreateTime = CreateTime;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeAuditConfigResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeAuditConfigResponse(DescribeAuditConfigResponse source) {
        if (source.LogExpireDay != null) {
            this.LogExpireDay = new Long(source.LogExpireDay);
        }
        if (source.LogType != null) {
            this.LogType = new String(source.LogType);
        }
        if (source.IsClosing != null) {
            this.IsClosing = new String(source.IsClosing);
        }
        if (source.IsOpening != null) {
            this.IsOpening = new String(source.IsOpening);
        }
        if (source.CreateTime != null) {
            this.CreateTime = new String(source.CreateTime);
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "LogExpireDay", this.LogExpireDay);
        this.setParamSimple(map, prefix + "LogType", this.LogType);
        this.setParamSimple(map, prefix + "IsClosing", this.IsClosing);
        this.setParamSimple(map, prefix + "IsOpening", this.IsOpening);
        this.setParamSimple(map, prefix + "CreateTime", this.CreateTime);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

