/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.cdb.v20170320.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeProxySupportParamResponse extends AbstractModel {

    /**
    * Proxy supports the maximum version
    */
    @SerializedName("ProxyVersion")
    @Expose
    private String ProxyVersion;

    /**
    * Whether connection pool is supported
    */
    @SerializedName("SupportPool")
    @Expose
    private Boolean SupportPool;

    /**
    * Minimum value of the connection pool
    */
    @SerializedName("PoolMin")
    @Expose
    private Long PoolMin;

    /**
    * Maximum value of connection pool
    */
    @SerializedName("PoolMax")
    @Expose
    private Long PoolMax;

    /**
    * Whether transaction split is supported
    */
    @SerializedName("SupportTransSplit")
    @Expose
    private Boolean SupportTransSplit;

    /**
    * Minimum proxy version that supports connection pool
    */
    @SerializedName("SupportPoolMinVersion")
    @Expose
    private String SupportPoolMinVersion;

    /**
    * Minimum proxy version supporting transaction split
    */
    @SerializedName("SupportTransSplitMinVersion")
    @Expose
    private String SupportTransSplitMinVersion;

    /**
    * Whether setting as read-only is supported.
    */
    @SerializedName("SupportReadOnly")
    @Expose
    private Boolean SupportReadOnly;

    /**
    * Whether to automatically balance the load
    */
    @SerializedName("SupportAutoLoadBalance")
    @Expose
    private Boolean SupportAutoLoadBalance;

    /**
    * Whether support access mode
    */
    @SerializedName("SupportAccessMode")
    @Expose
    private Boolean SupportAccessMode;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Proxy supports the maximum version 
     * @return ProxyVersion Proxy supports the maximum version
     */
    public String getProxyVersion() {
        return this.ProxyVersion;
    }

    /**
     * Set Proxy supports the maximum version
     * @param ProxyVersion Proxy supports the maximum version
     */
    public void setProxyVersion(String ProxyVersion) {
        this.ProxyVersion = ProxyVersion;
    }

    /**
     * Get Whether connection pool is supported 
     * @return SupportPool Whether connection pool is supported
     */
    public Boolean getSupportPool() {
        return this.SupportPool;
    }

    /**
     * Set Whether connection pool is supported
     * @param SupportPool Whether connection pool is supported
     */
    public void setSupportPool(Boolean SupportPool) {
        this.SupportPool = SupportPool;
    }

    /**
     * Get Minimum value of the connection pool 
     * @return PoolMin Minimum value of the connection pool
     */
    public Long getPoolMin() {
        return this.PoolMin;
    }

    /**
     * Set Minimum value of the connection pool
     * @param PoolMin Minimum value of the connection pool
     */
    public void setPoolMin(Long PoolMin) {
        this.PoolMin = PoolMin;
    }

    /**
     * Get Maximum value of connection pool 
     * @return PoolMax Maximum value of connection pool
     */
    public Long getPoolMax() {
        return this.PoolMax;
    }

    /**
     * Set Maximum value of connection pool
     * @param PoolMax Maximum value of connection pool
     */
    public void setPoolMax(Long PoolMax) {
        this.PoolMax = PoolMax;
    }

    /**
     * Get Whether transaction split is supported 
     * @return SupportTransSplit Whether transaction split is supported
     */
    public Boolean getSupportTransSplit() {
        return this.SupportTransSplit;
    }

    /**
     * Set Whether transaction split is supported
     * @param SupportTransSplit Whether transaction split is supported
     */
    public void setSupportTransSplit(Boolean SupportTransSplit) {
        this.SupportTransSplit = SupportTransSplit;
    }

    /**
     * Get Minimum proxy version that supports connection pool 
     * @return SupportPoolMinVersion Minimum proxy version that supports connection pool
     */
    public String getSupportPoolMinVersion() {
        return this.SupportPoolMinVersion;
    }

    /**
     * Set Minimum proxy version that supports connection pool
     * @param SupportPoolMinVersion Minimum proxy version that supports connection pool
     */
    public void setSupportPoolMinVersion(String SupportPoolMinVersion) {
        this.SupportPoolMinVersion = SupportPoolMinVersion;
    }

    /**
     * Get Minimum proxy version supporting transaction split 
     * @return SupportTransSplitMinVersion Minimum proxy version supporting transaction split
     */
    public String getSupportTransSplitMinVersion() {
        return this.SupportTransSplitMinVersion;
    }

    /**
     * Set Minimum proxy version supporting transaction split
     * @param SupportTransSplitMinVersion Minimum proxy version supporting transaction split
     */
    public void setSupportTransSplitMinVersion(String SupportTransSplitMinVersion) {
        this.SupportTransSplitMinVersion = SupportTransSplitMinVersion;
    }

    /**
     * Get Whether setting as read-only is supported. 
     * @return SupportReadOnly Whether setting as read-only is supported.
     */
    public Boolean getSupportReadOnly() {
        return this.SupportReadOnly;
    }

    /**
     * Set Whether setting as read-only is supported.
     * @param SupportReadOnly Whether setting as read-only is supported.
     */
    public void setSupportReadOnly(Boolean SupportReadOnly) {
        this.SupportReadOnly = SupportReadOnly;
    }

    /**
     * Get Whether to automatically balance the load 
     * @return SupportAutoLoadBalance Whether to automatically balance the load
     */
    public Boolean getSupportAutoLoadBalance() {
        return this.SupportAutoLoadBalance;
    }

    /**
     * Set Whether to automatically balance the load
     * @param SupportAutoLoadBalance Whether to automatically balance the load
     */
    public void setSupportAutoLoadBalance(Boolean SupportAutoLoadBalance) {
        this.SupportAutoLoadBalance = SupportAutoLoadBalance;
    }

    /**
     * Get Whether support access mode 
     * @return SupportAccessMode Whether support access mode
     */
    public Boolean getSupportAccessMode() {
        return this.SupportAccessMode;
    }

    /**
     * Set Whether support access mode
     * @param SupportAccessMode Whether support access mode
     */
    public void setSupportAccessMode(Boolean SupportAccessMode) {
        this.SupportAccessMode = SupportAccessMode;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeProxySupportParamResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeProxySupportParamResponse(DescribeProxySupportParamResponse source) {
        if (source.ProxyVersion != null) {
            this.ProxyVersion = new String(source.ProxyVersion);
        }
        if (source.SupportPool != null) {
            this.SupportPool = new Boolean(source.SupportPool);
        }
        if (source.PoolMin != null) {
            this.PoolMin = new Long(source.PoolMin);
        }
        if (source.PoolMax != null) {
            this.PoolMax = new Long(source.PoolMax);
        }
        if (source.SupportTransSplit != null) {
            this.SupportTransSplit = new Boolean(source.SupportTransSplit);
        }
        if (source.SupportPoolMinVersion != null) {
            this.SupportPoolMinVersion = new String(source.SupportPoolMinVersion);
        }
        if (source.SupportTransSplitMinVersion != null) {
            this.SupportTransSplitMinVersion = new String(source.SupportTransSplitMinVersion);
        }
        if (source.SupportReadOnly != null) {
            this.SupportReadOnly = new Boolean(source.SupportReadOnly);
        }
        if (source.SupportAutoLoadBalance != null) {
            this.SupportAutoLoadBalance = new Boolean(source.SupportAutoLoadBalance);
        }
        if (source.SupportAccessMode != null) {
            this.SupportAccessMode = new Boolean(source.SupportAccessMode);
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "ProxyVersion", this.ProxyVersion);
        this.setParamSimple(map, prefix + "SupportPool", this.SupportPool);
        this.setParamSimple(map, prefix + "PoolMin", this.PoolMin);
        this.setParamSimple(map, prefix + "PoolMax", this.PoolMax);
        this.setParamSimple(map, prefix + "SupportTransSplit", this.SupportTransSplit);
        this.setParamSimple(map, prefix + "SupportPoolMinVersion", this.SupportPoolMinVersion);
        this.setParamSimple(map, prefix + "SupportTransSplitMinVersion", this.SupportTransSplitMinVersion);
        this.setParamSimple(map, prefix + "SupportReadOnly", this.SupportReadOnly);
        this.setParamSimple(map, prefix + "SupportAutoLoadBalance", this.SupportAutoLoadBalance);
        this.setParamSimple(map, prefix + "SupportAccessMode", this.SupportAccessMode);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

