/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.cdb.v20170320.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeCPUExpandStrategyInfoResponse extends AbstractModel {

    /**
    * Policy type. Output value: auto, manual, timeInterval, period.
Description: 1. auto means auto-scaling. 2. manual means custom scaling with immediate effect. 3. timeInterval means custom scaling by time. 4. period means custom scaling by cycle. 5. If the return is NULL, the elastic expansion strategy is not yet opened.
Note: This field may return null, indicating that no valid values can be obtained.
    */
    @SerializedName("Type")
    @Expose
    private String Type;

    /**
    * Custom expansion with CPU that takes effect immediately. Valid when Type is manual.
Note: This field may return null, indicating that no valid values can be obtained.
    */
    @SerializedName("ExpandCpu")
    @Expose
    private Long ExpandCpu;

    /**
    * Auto scale-out policy. Valid when Type is auto.
Note: This field may return null, indicating that no valid values can be obtained.
    */
    @SerializedName("AutoStrategy")
    @Expose
    private AutoStrategy AutoStrategy;

    /**
    * Scaling policy by cycle. Valid when Type is period.
    */
    @SerializedName("PeriodStrategy")
    @Expose
    private PeriodStrategy PeriodStrategy;

    /**
    * Scaling policy by time period. Valid when Type is timeInterval.
    */
    @SerializedName("TimeIntervalStrategy")
    @Expose
    private TimeIntervalStrategy TimeIntervalStrategy;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Policy type. Output value: auto, manual, timeInterval, period.
Description: 1. auto means auto-scaling. 2. manual means custom scaling with immediate effect. 3. timeInterval means custom scaling by time. 4. period means custom scaling by cycle. 5. If the return is NULL, the elastic expansion strategy is not yet opened.
Note: This field may return null, indicating that no valid values can be obtained. 
     * @return Type Policy type. Output value: auto, manual, timeInterval, period.
Description: 1. auto means auto-scaling. 2. manual means custom scaling with immediate effect. 3. timeInterval means custom scaling by time. 4. period means custom scaling by cycle. 5. If the return is NULL, the elastic expansion strategy is not yet opened.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public String getType() {
        return this.Type;
    }

    /**
     * Set Policy type. Output value: auto, manual, timeInterval, period.
Description: 1. auto means auto-scaling. 2. manual means custom scaling with immediate effect. 3. timeInterval means custom scaling by time. 4. period means custom scaling by cycle. 5. If the return is NULL, the elastic expansion strategy is not yet opened.
Note: This field may return null, indicating that no valid values can be obtained.
     * @param Type Policy type. Output value: auto, manual, timeInterval, period.
Description: 1. auto means auto-scaling. 2. manual means custom scaling with immediate effect. 3. timeInterval means custom scaling by time. 4. period means custom scaling by cycle. 5. If the return is NULL, the elastic expansion strategy is not yet opened.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public void setType(String Type) {
        this.Type = Type;
    }

    /**
     * Get Custom expansion with CPU that takes effect immediately. Valid when Type is manual.
Note: This field may return null, indicating that no valid values can be obtained. 
     * @return ExpandCpu Custom expansion with CPU that takes effect immediately. Valid when Type is manual.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public Long getExpandCpu() {
        return this.ExpandCpu;
    }

    /**
     * Set Custom expansion with CPU that takes effect immediately. Valid when Type is manual.
Note: This field may return null, indicating that no valid values can be obtained.
     * @param ExpandCpu Custom expansion with CPU that takes effect immediately. Valid when Type is manual.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public void setExpandCpu(Long ExpandCpu) {
        this.ExpandCpu = ExpandCpu;
    }

    /**
     * Get Auto scale-out policy. Valid when Type is auto.
Note: This field may return null, indicating that no valid values can be obtained. 
     * @return AutoStrategy Auto scale-out policy. Valid when Type is auto.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public AutoStrategy getAutoStrategy() {
        return this.AutoStrategy;
    }

    /**
     * Set Auto scale-out policy. Valid when Type is auto.
Note: This field may return null, indicating that no valid values can be obtained.
     * @param AutoStrategy Auto scale-out policy. Valid when Type is auto.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public void setAutoStrategy(AutoStrategy AutoStrategy) {
        this.AutoStrategy = AutoStrategy;
    }

    /**
     * Get Scaling policy by cycle. Valid when Type is period. 
     * @return PeriodStrategy Scaling policy by cycle. Valid when Type is period.
     */
    public PeriodStrategy getPeriodStrategy() {
        return this.PeriodStrategy;
    }

    /**
     * Set Scaling policy by cycle. Valid when Type is period.
     * @param PeriodStrategy Scaling policy by cycle. Valid when Type is period.
     */
    public void setPeriodStrategy(PeriodStrategy PeriodStrategy) {
        this.PeriodStrategy = PeriodStrategy;
    }

    /**
     * Get Scaling policy by time period. Valid when Type is timeInterval. 
     * @return TimeIntervalStrategy Scaling policy by time period. Valid when Type is timeInterval.
     */
    public TimeIntervalStrategy getTimeIntervalStrategy() {
        return this.TimeIntervalStrategy;
    }

    /**
     * Set Scaling policy by time period. Valid when Type is timeInterval.
     * @param TimeIntervalStrategy Scaling policy by time period. Valid when Type is timeInterval.
     */
    public void setTimeIntervalStrategy(TimeIntervalStrategy TimeIntervalStrategy) {
        this.TimeIntervalStrategy = TimeIntervalStrategy;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeCPUExpandStrategyInfoResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeCPUExpandStrategyInfoResponse(DescribeCPUExpandStrategyInfoResponse source) {
        if (source.Type != null) {
            this.Type = new String(source.Type);
        }
        if (source.ExpandCpu != null) {
            this.ExpandCpu = new Long(source.ExpandCpu);
        }
        if (source.AutoStrategy != null) {
            this.AutoStrategy = new AutoStrategy(source.AutoStrategy);
        }
        if (source.PeriodStrategy != null) {
            this.PeriodStrategy = new PeriodStrategy(source.PeriodStrategy);
        }
        if (source.TimeIntervalStrategy != null) {
            this.TimeIntervalStrategy = new TimeIntervalStrategy(source.TimeIntervalStrategy);
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "Type", this.Type);
        this.setParamSimple(map, prefix + "ExpandCpu", this.ExpandCpu);
        this.setParamObj(map, prefix + "AutoStrategy.", this.AutoStrategy);
        this.setParamObj(map, prefix + "PeriodStrategy.", this.PeriodStrategy);
        this.setParamObj(map, prefix + "TimeIntervalStrategy.", this.TimeIntervalStrategy);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

