/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.cbs.v20170312.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeSnapshotOverviewResponse extends AbstractModel {

    /**
    * Current number of valid snapshots.
    */
    @SerializedName("TotalNums")
    @Expose
    private Long TotalNums;

    /**
    * Total used snapshot capacity. unit: GiB.
    */
    @SerializedName("TotalSize")
    @Expose
    private Float TotalSize;

    /**
    * Snapshot free quota size in GiB.
    */
    @SerializedName("FreeQuota")
    @Expose
    private Float FreeQuota;

    /**
    * Snapshot actual cost of total capacity in GiB.
    */
    @SerializedName("RealTradeSize")
    @Expose
    private Float RealTradeSize;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Current number of valid snapshots. 
     * @return TotalNums Current number of valid snapshots.
     */
    public Long getTotalNums() {
        return this.TotalNums;
    }

    /**
     * Set Current number of valid snapshots.
     * @param TotalNums Current number of valid snapshots.
     */
    public void setTotalNums(Long TotalNums) {
        this.TotalNums = TotalNums;
    }

    /**
     * Get Total used snapshot capacity. unit: GiB. 
     * @return TotalSize Total used snapshot capacity. unit: GiB.
     */
    public Float getTotalSize() {
        return this.TotalSize;
    }

    /**
     * Set Total used snapshot capacity. unit: GiB.
     * @param TotalSize Total used snapshot capacity. unit: GiB.
     */
    public void setTotalSize(Float TotalSize) {
        this.TotalSize = TotalSize;
    }

    /**
     * Get Snapshot free quota size in GiB. 
     * @return FreeQuota Snapshot free quota size in GiB.
     */
    public Float getFreeQuota() {
        return this.FreeQuota;
    }

    /**
     * Set Snapshot free quota size in GiB.
     * @param FreeQuota Snapshot free quota size in GiB.
     */
    public void setFreeQuota(Float FreeQuota) {
        this.FreeQuota = FreeQuota;
    }

    /**
     * Get Snapshot actual cost of total capacity in GiB. 
     * @return RealTradeSize Snapshot actual cost of total capacity in GiB.
     */
    public Float getRealTradeSize() {
        return this.RealTradeSize;
    }

    /**
     * Set Snapshot actual cost of total capacity in GiB.
     * @param RealTradeSize Snapshot actual cost of total capacity in GiB.
     */
    public void setRealTradeSize(Float RealTradeSize) {
        this.RealTradeSize = RealTradeSize;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeSnapshotOverviewResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeSnapshotOverviewResponse(DescribeSnapshotOverviewResponse source) {
        if (source.TotalNums != null) {
            this.TotalNums = new Long(source.TotalNums);
        }
        if (source.TotalSize != null) {
            this.TotalSize = new Float(source.TotalSize);
        }
        if (source.FreeQuota != null) {
            this.FreeQuota = new Float(source.FreeQuota);
        }
        if (source.RealTradeSize != null) {
            this.RealTradeSize = new Float(source.RealTradeSize);
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "TotalNums", this.TotalNums);
        this.setParamSimple(map, prefix + "TotalSize", this.TotalSize);
        this.setParamSimple(map, prefix + "FreeQuota", this.FreeQuota);
        this.setParamSimple(map, prefix + "RealTradeSize", this.RealTradeSize);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

