/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.edgezone.v20260401.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribePrivateNetworkInstancesResponse extends AbstractModel {

    /**
    * Total number of private network instances
    */
    @SerializedName("TotalCount")
    @Expose
    private Long TotalCount;

    /**
    * Private network instance set
    */
    @SerializedName("PrivateNetworkInstanceSet")
    @Expose
    private PrivateNetworkInstanceInfo [] PrivateNetworkInstanceSet;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Total number of private network instances 
     * @return TotalCount Total number of private network instances
     */
    public Long getTotalCount() {
        return this.TotalCount;
    }

    /**
     * Set Total number of private network instances
     * @param TotalCount Total number of private network instances
     */
    public void setTotalCount(Long TotalCount) {
        this.TotalCount = TotalCount;
    }

    /**
     * Get Private network instance set 
     * @return PrivateNetworkInstanceSet Private network instance set
     */
    public PrivateNetworkInstanceInfo [] getPrivateNetworkInstanceSet() {
        return this.PrivateNetworkInstanceSet;
    }

    /**
     * Set Private network instance set
     * @param PrivateNetworkInstanceSet Private network instance set
     */
    public void setPrivateNetworkInstanceSet(PrivateNetworkInstanceInfo [] PrivateNetworkInstanceSet) {
        this.PrivateNetworkInstanceSet = PrivateNetworkInstanceSet;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribePrivateNetworkInstancesResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribePrivateNetworkInstancesResponse(DescribePrivateNetworkInstancesResponse source) {
        if (source.TotalCount != null) {
            this.TotalCount = new Long(source.TotalCount);
        }
        if (source.PrivateNetworkInstanceSet != null) {
            this.PrivateNetworkInstanceSet = new PrivateNetworkInstanceInfo[source.PrivateNetworkInstanceSet.length];
            for (int i = 0; i < source.PrivateNetworkInstanceSet.length; i++) {
                this.PrivateNetworkInstanceSet[i] = new PrivateNetworkInstanceInfo(source.PrivateNetworkInstanceSet[i]);
            }
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "TotalCount", this.TotalCount);
        this.setParamArrayObj(map, prefix + "PrivateNetworkInstanceSet.", this.PrivateNetworkInstanceSet);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

