/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.edgezone.v20260401.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class TerminateInstancesResponse extends AbstractModel {

    /**
    * List of instance IDs successfully terminated.
    */
    @SerializedName("InstanceIdSet")
    @Expose
    private String [] InstanceIdSet;

    /**
    * List of instances with termination failed (returned when partially successful).
Note: This field may return null, indicating that no valid values can be obtained.
    */
    @SerializedName("FailedInstanceSet")
    @Expose
    private FailedInstance [] FailedInstanceSet;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get List of instance IDs successfully terminated. 
     * @return InstanceIdSet List of instance IDs successfully terminated.
     */
    public String [] getInstanceIdSet() {
        return this.InstanceIdSet;
    }

    /**
     * Set List of instance IDs successfully terminated.
     * @param InstanceIdSet List of instance IDs successfully terminated.
     */
    public void setInstanceIdSet(String [] InstanceIdSet) {
        this.InstanceIdSet = InstanceIdSet;
    }

    /**
     * Get List of instances with termination failed (returned when partially successful).
Note: This field may return null, indicating that no valid values can be obtained. 
     * @return FailedInstanceSet List of instances with termination failed (returned when partially successful).
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public FailedInstance [] getFailedInstanceSet() {
        return this.FailedInstanceSet;
    }

    /**
     * Set List of instances with termination failed (returned when partially successful).
Note: This field may return null, indicating that no valid values can be obtained.
     * @param FailedInstanceSet List of instances with termination failed (returned when partially successful).
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public void setFailedInstanceSet(FailedInstance [] FailedInstanceSet) {
        this.FailedInstanceSet = FailedInstanceSet;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public TerminateInstancesResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public TerminateInstancesResponse(TerminateInstancesResponse source) {
        if (source.InstanceIdSet != null) {
            this.InstanceIdSet = new String[source.InstanceIdSet.length];
            for (int i = 0; i < source.InstanceIdSet.length; i++) {
                this.InstanceIdSet[i] = new String(source.InstanceIdSet[i]);
            }
        }
        if (source.FailedInstanceSet != null) {
            this.FailedInstanceSet = new FailedInstance[source.FailedInstanceSet.length];
            for (int i = 0; i < source.FailedInstanceSet.length; i++) {
                this.FailedInstanceSet[i] = new FailedInstance(source.FailedInstanceSet[i]);
            }
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamArraySimple(map, prefix + "InstanceIdSet.", this.InstanceIdSet);
        this.setParamArrayObj(map, prefix + "FailedInstanceSet.", this.FailedInstanceSet);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

