/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.ocr.v20181119.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class PermitOCRResponse extends AbstractModel {

    /**
    * Name in Chinese
    */
    @SerializedName("Name")
    @Expose
    private String Name;

    /**
    * English name
    */
    @SerializedName("EnglishName")
    @Expose
    private String EnglishName;

    /**
    * ID number
    */
    @SerializedName("Number")
    @Expose
    private String Number;

    /**
    * Gender
    */
    @SerializedName("Sex")
    @Expose
    private String Sex;

    /**
    * Validity period
    */
    @SerializedName("ValidDate")
    @Expose
    private String ValidDate;

    /**
    * Issuing authority
    */
    @SerializedName("IssueAuthority")
    @Expose
    private String IssueAuthority;

    /**
    * Place of issue
    */
    @SerializedName("IssueAddress")
    @Expose
    private String IssueAddress;

    /**
    * Date of birth
    */
    @SerializedName("Birthday")
    @Expose
    private String Birthday;

    /**
    * Base64-encoded profile photo of the document holder.
    */
    @SerializedName("PortraitImage")
    @Expose
    private String PortraitImage;

    /**
    * Document type, such as: Exit-Entry Permit for Travelling to and from Hong Kong and Macao, or Exit-Entry Permit for Travelling to and from Taiwan.
    */
    @SerializedName("Type")
    @Expose
    private String Type;

    /**
    * Warning information for the document. This field is only valid for international site requests. Warning codes:
-9101: Incomplete card border warning
-9102: Photocopied card warning
-9103: Recaptured card warning
-9104: Photoshopped card warning
-9107: Reflective card warning
-9108: Blurry image warning
-9109: Warning capability not enabled
    */
    @SerializedName("WarnCardInfos")
    @Expose
    private Long [] WarnCardInfos;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Name in Chinese 
     * @return Name Name in Chinese
     */
    public String getName() {
        return this.Name;
    }

    /**
     * Set Name in Chinese
     * @param Name Name in Chinese
     */
    public void setName(String Name) {
        this.Name = Name;
    }

    /**
     * Get English name 
     * @return EnglishName English name
     */
    public String getEnglishName() {
        return this.EnglishName;
    }

    /**
     * Set English name
     * @param EnglishName English name
     */
    public void setEnglishName(String EnglishName) {
        this.EnglishName = EnglishName;
    }

    /**
     * Get ID number 
     * @return Number ID number
     */
    public String getNumber() {
        return this.Number;
    }

    /**
     * Set ID number
     * @param Number ID number
     */
    public void setNumber(String Number) {
        this.Number = Number;
    }

    /**
     * Get Gender 
     * @return Sex Gender
     */
    public String getSex() {
        return this.Sex;
    }

    /**
     * Set Gender
     * @param Sex Gender
     */
    public void setSex(String Sex) {
        this.Sex = Sex;
    }

    /**
     * Get Validity period 
     * @return ValidDate Validity period
     */
    public String getValidDate() {
        return this.ValidDate;
    }

    /**
     * Set Validity period
     * @param ValidDate Validity period
     */
    public void setValidDate(String ValidDate) {
        this.ValidDate = ValidDate;
    }

    /**
     * Get Issuing authority 
     * @return IssueAuthority Issuing authority
     */
    public String getIssueAuthority() {
        return this.IssueAuthority;
    }

    /**
     * Set Issuing authority
     * @param IssueAuthority Issuing authority
     */
    public void setIssueAuthority(String IssueAuthority) {
        this.IssueAuthority = IssueAuthority;
    }

    /**
     * Get Place of issue 
     * @return IssueAddress Place of issue
     */
    public String getIssueAddress() {
        return this.IssueAddress;
    }

    /**
     * Set Place of issue
     * @param IssueAddress Place of issue
     */
    public void setIssueAddress(String IssueAddress) {
        this.IssueAddress = IssueAddress;
    }

    /**
     * Get Date of birth 
     * @return Birthday Date of birth
     */
    public String getBirthday() {
        return this.Birthday;
    }

    /**
     * Set Date of birth
     * @param Birthday Date of birth
     */
    public void setBirthday(String Birthday) {
        this.Birthday = Birthday;
    }

    /**
     * Get Base64-encoded profile photo of the document holder. 
     * @return PortraitImage Base64-encoded profile photo of the document holder.
     */
    public String getPortraitImage() {
        return this.PortraitImage;
    }

    /**
     * Set Base64-encoded profile photo of the document holder.
     * @param PortraitImage Base64-encoded profile photo of the document holder.
     */
    public void setPortraitImage(String PortraitImage) {
        this.PortraitImage = PortraitImage;
    }

    /**
     * Get Document type, such as: Exit-Entry Permit for Travelling to and from Hong Kong and Macao, or Exit-Entry Permit for Travelling to and from Taiwan. 
     * @return Type Document type, such as: Exit-Entry Permit for Travelling to and from Hong Kong and Macao, or Exit-Entry Permit for Travelling to and from Taiwan.
     */
    public String getType() {
        return this.Type;
    }

    /**
     * Set Document type, such as: Exit-Entry Permit for Travelling to and from Hong Kong and Macao, or Exit-Entry Permit for Travelling to and from Taiwan.
     * @param Type Document type, such as: Exit-Entry Permit for Travelling to and from Hong Kong and Macao, or Exit-Entry Permit for Travelling to and from Taiwan.
     */
    public void setType(String Type) {
        this.Type = Type;
    }

    /**
     * Get Warning information for the document. This field is only valid for international site requests. Warning codes:
-9101: Incomplete card border warning
-9102: Photocopied card warning
-9103: Recaptured card warning
-9104: Photoshopped card warning
-9107: Reflective card warning
-9108: Blurry image warning
-9109: Warning capability not enabled 
     * @return WarnCardInfos Warning information for the document. This field is only valid for international site requests. Warning codes:
-9101: Incomplete card border warning
-9102: Photocopied card warning
-9103: Recaptured card warning
-9104: Photoshopped card warning
-9107: Reflective card warning
-9108: Blurry image warning
-9109: Warning capability not enabled
     */
    public Long [] getWarnCardInfos() {
        return this.WarnCardInfos;
    }

    /**
     * Set Warning information for the document. This field is only valid for international site requests. Warning codes:
-9101: Incomplete card border warning
-9102: Photocopied card warning
-9103: Recaptured card warning
-9104: Photoshopped card warning
-9107: Reflective card warning
-9108: Blurry image warning
-9109: Warning capability not enabled
     * @param WarnCardInfos Warning information for the document. This field is only valid for international site requests. Warning codes:
-9101: Incomplete card border warning
-9102: Photocopied card warning
-9103: Recaptured card warning
-9104: Photoshopped card warning
-9107: Reflective card warning
-9108: Blurry image warning
-9109: Warning capability not enabled
     */
    public void setWarnCardInfos(Long [] WarnCardInfos) {
        this.WarnCardInfos = WarnCardInfos;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public PermitOCRResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public PermitOCRResponse(PermitOCRResponse source) {
        if (source.Name != null) {
            this.Name = new String(source.Name);
        }
        if (source.EnglishName != null) {
            this.EnglishName = new String(source.EnglishName);
        }
        if (source.Number != null) {
            this.Number = new String(source.Number);
        }
        if (source.Sex != null) {
            this.Sex = new String(source.Sex);
        }
        if (source.ValidDate != null) {
            this.ValidDate = new String(source.ValidDate);
        }
        if (source.IssueAuthority != null) {
            this.IssueAuthority = new String(source.IssueAuthority);
        }
        if (source.IssueAddress != null) {
            this.IssueAddress = new String(source.IssueAddress);
        }
        if (source.Birthday != null) {
            this.Birthday = new String(source.Birthday);
        }
        if (source.PortraitImage != null) {
            this.PortraitImage = new String(source.PortraitImage);
        }
        if (source.Type != null) {
            this.Type = new String(source.Type);
        }
        if (source.WarnCardInfos != null) {
            this.WarnCardInfos = new Long[source.WarnCardInfos.length];
            for (int i = 0; i < source.WarnCardInfos.length; i++) {
                this.WarnCardInfos[i] = new Long(source.WarnCardInfos[i]);
            }
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "Name", this.Name);
        this.setParamSimple(map, prefix + "EnglishName", this.EnglishName);
        this.setParamSimple(map, prefix + "Number", this.Number);
        this.setParamSimple(map, prefix + "Sex", this.Sex);
        this.setParamSimple(map, prefix + "ValidDate", this.ValidDate);
        this.setParamSimple(map, prefix + "IssueAuthority", this.IssueAuthority);
        this.setParamSimple(map, prefix + "IssueAddress", this.IssueAddress);
        this.setParamSimple(map, prefix + "Birthday", this.Birthday);
        this.setParamSimple(map, prefix + "PortraitImage", this.PortraitImage);
        this.setParamSimple(map, prefix + "Type", this.Type);
        this.setParamArraySimple(map, prefix + "WarnCardInfos.", this.WarnCardInfos);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

