/*
 * Copyright (c) 2017-2018 THL A29 Limited, a Tencent company. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.pts.v20210728.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeErrorSummaryResponse extends AbstractModel {

    /**
    * Error summary information.

Note: This field may return null, indicating that no valid value is found.
    */
    @SerializedName("ErrorSummarySet")
    @Expose
    private ErrorSummary [] ErrorSummarySet;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Error summary information.

Note: This field may return null, indicating that no valid value is found. 
     * @return ErrorSummarySet Error summary information.

Note: This field may return null, indicating that no valid value is found.
     */
    public ErrorSummary [] getErrorSummarySet() {
        return this.ErrorSummarySet;
    }

    /**
     * Set Error summary information.

Note: This field may return null, indicating that no valid value is found.
     * @param ErrorSummarySet Error summary information.

Note: This field may return null, indicating that no valid value is found.
     */
    public void setErrorSummarySet(ErrorSummary [] ErrorSummarySet) {
        this.ErrorSummarySet = ErrorSummarySet;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeErrorSummaryResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeErrorSummaryResponse(DescribeErrorSummaryResponse source) {
        if (source.ErrorSummarySet != null) {
            this.ErrorSummarySet = new ErrorSummary[source.ErrorSummarySet.length];
            for (int i = 0; i < source.ErrorSummarySet.length; i++) {
                this.ErrorSummarySet[i] = new ErrorSummary(source.ErrorSummarySet[i]);
            }
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamArrayObj(map, prefix + "ErrorSummarySet.", this.ErrorSummarySet);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

