/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.tat.v20201028.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeRegisterInstancesResponse extends AbstractModel {

    /**
    * The total number of registration codes registered by the instance.
    */
    @SerializedName("TotalCount")
    @Expose
    private Long TotalCount;

    /**
    * List of managed instance information.
    */
    @SerializedName("RegisterInstanceSet")
    @Expose
    private RegisterInstanceInfo [] RegisterInstanceSet;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get The total number of registration codes registered by the instance. 
     * @return TotalCount The total number of registration codes registered by the instance.
     */
    public Long getTotalCount() {
        return this.TotalCount;
    }

    /**
     * Set The total number of registration codes registered by the instance.
     * @param TotalCount The total number of registration codes registered by the instance.
     */
    public void setTotalCount(Long TotalCount) {
        this.TotalCount = TotalCount;
    }

    /**
     * Get List of managed instance information. 
     * @return RegisterInstanceSet List of managed instance information.
     */
    public RegisterInstanceInfo [] getRegisterInstanceSet() {
        return this.RegisterInstanceSet;
    }

    /**
     * Set List of managed instance information.
     * @param RegisterInstanceSet List of managed instance information.
     */
    public void setRegisterInstanceSet(RegisterInstanceInfo [] RegisterInstanceSet) {
        this.RegisterInstanceSet = RegisterInstanceSet;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeRegisterInstancesResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeRegisterInstancesResponse(DescribeRegisterInstancesResponse source) {
        if (source.TotalCount != null) {
            this.TotalCount = new Long(source.TotalCount);
        }
        if (source.RegisterInstanceSet != null) {
            this.RegisterInstanceSet = new RegisterInstanceInfo[source.RegisterInstanceSet.length];
            for (int i = 0; i < source.RegisterInstanceSet.length; i++) {
                this.RegisterInstanceSet[i] = new RegisterInstanceInfo(source.RegisterInstanceSet[i]);
            }
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "TotalCount", this.TotalCount);
        this.setParamArrayObj(map, prefix + "RegisterInstanceSet.", this.RegisterInstanceSet);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

