/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.billing.v20180709.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class CreateInstanceRequest extends AbstractModel {

    /**
    * ClientToken is an unique, case-sensitive string generated by the client with no more than 64 ASCII characters. for example, ClientToken=123e4567-e89b-12d3-a456-42665544****.
    */
    @SerializedName("ClientToken")
    @Expose
    private String ClientToken;

    /**
    * Product code.
    */
    @SerializedName("ProductCode")
    @Expose
    private String ProductCode;

    /**
    * Sub-product code.
    */
    @SerializedName("SubProductCode")
    @Expose
    private String SubProductCode;

    /**
    * Region code.
    */
    @SerializedName("RegionCode")
    @Expose
    private String RegionCode;

    /**
    * Availability zone code.
    */
    @SerializedName("ZoneCode")
    @Expose
    private String ZoneCode;

    /**
    * Payment mode. Available values: PrePay: upfront charge.
    */
    @SerializedName("PayMode")
    @Expose
    private String PayMode;

    /**
    * Product detailed information.
    */
    @SerializedName("Parameter")
    @Expose
    private String Parameter;

    /**
    * Product quantity, default value is 1.
    */
    @SerializedName("Quantity")
    @Expose
    private Long Quantity;

    /**
    * Project id, default value is 0.
    */
    @SerializedName("ProjectId")
    @Expose
    private Long ProjectId;

    /**
    * Purchase duration, max number is 36, default value is 1.
    */
    @SerializedName("Period")
    @Expose
    private Long Period;

    /**
    * Purchase duration unit. valid values: 
m: month,
y: year. 
default value is: m.
    */
    @SerializedName("PeriodUnit")
    @Expose
    private String PeriodUnit;

    /**
    * Auto-renewal flag. valid values: NOTIFY_AND_MANUAL_RENEW: manually renew, NOTIFY_AND_AUTO_RENEW: automatically renew, DISABLE_NOTIFY_AND_MANUAL_RENEW: renewal is disabled. 
default value is NOTIFY_AND_MANUAL_RENEW.
    */
    @SerializedName("RenewFlag")
    @Expose
    private String RenewFlag;

    /**
     * Get ClientToken is an unique, case-sensitive string generated by the client with no more than 64 ASCII characters. for example, ClientToken=123e4567-e89b-12d3-a456-42665544****. 
     * @return ClientToken ClientToken is an unique, case-sensitive string generated by the client with no more than 64 ASCII characters. for example, ClientToken=123e4567-e89b-12d3-a456-42665544****.
     */
    public String getClientToken() {
        return this.ClientToken;
    }

    /**
     * Set ClientToken is an unique, case-sensitive string generated by the client with no more than 64 ASCII characters. for example, ClientToken=123e4567-e89b-12d3-a456-42665544****.
     * @param ClientToken ClientToken is an unique, case-sensitive string generated by the client with no more than 64 ASCII characters. for example, ClientToken=123e4567-e89b-12d3-a456-42665544****.
     */
    public void setClientToken(String ClientToken) {
        this.ClientToken = ClientToken;
    }

    /**
     * Get Product code. 
     * @return ProductCode Product code.
     */
    public String getProductCode() {
        return this.ProductCode;
    }

    /**
     * Set Product code.
     * @param ProductCode Product code.
     */
    public void setProductCode(String ProductCode) {
        this.ProductCode = ProductCode;
    }

    /**
     * Get Sub-product code. 
     * @return SubProductCode Sub-product code.
     */
    public String getSubProductCode() {
        return this.SubProductCode;
    }

    /**
     * Set Sub-product code.
     * @param SubProductCode Sub-product code.
     */
    public void setSubProductCode(String SubProductCode) {
        this.SubProductCode = SubProductCode;
    }

    /**
     * Get Region code. 
     * @return RegionCode Region code.
     */
    public String getRegionCode() {
        return this.RegionCode;
    }

    /**
     * Set Region code.
     * @param RegionCode Region code.
     */
    public void setRegionCode(String RegionCode) {
        this.RegionCode = RegionCode;
    }

    /**
     * Get Availability zone code. 
     * @return ZoneCode Availability zone code.
     */
    public String getZoneCode() {
        return this.ZoneCode;
    }

    /**
     * Set Availability zone code.
     * @param ZoneCode Availability zone code.
     */
    public void setZoneCode(String ZoneCode) {
        this.ZoneCode = ZoneCode;
    }

    /**
     * Get Payment mode. Available values: PrePay: upfront charge. 
     * @return PayMode Payment mode. Available values: PrePay: upfront charge.
     */
    public String getPayMode() {
        return this.PayMode;
    }

    /**
     * Set Payment mode. Available values: PrePay: upfront charge.
     * @param PayMode Payment mode. Available values: PrePay: upfront charge.
     */
    public void setPayMode(String PayMode) {
        this.PayMode = PayMode;
    }

    /**
     * Get Product detailed information. 
     * @return Parameter Product detailed information.
     */
    public String getParameter() {
        return this.Parameter;
    }

    /**
     * Set Product detailed information.
     * @param Parameter Product detailed information.
     */
    public void setParameter(String Parameter) {
        this.Parameter = Parameter;
    }

    /**
     * Get Product quantity, default value is 1. 
     * @return Quantity Product quantity, default value is 1.
     */
    public Long getQuantity() {
        return this.Quantity;
    }

    /**
     * Set Product quantity, default value is 1.
     * @param Quantity Product quantity, default value is 1.
     */
    public void setQuantity(Long Quantity) {
        this.Quantity = Quantity;
    }

    /**
     * Get Project id, default value is 0. 
     * @return ProjectId Project id, default value is 0.
     */
    public Long getProjectId() {
        return this.ProjectId;
    }

    /**
     * Set Project id, default value is 0.
     * @param ProjectId Project id, default value is 0.
     */
    public void setProjectId(Long ProjectId) {
        this.ProjectId = ProjectId;
    }

    /**
     * Get Purchase duration, max number is 36, default value is 1. 
     * @return Period Purchase duration, max number is 36, default value is 1.
     */
    public Long getPeriod() {
        return this.Period;
    }

    /**
     * Set Purchase duration, max number is 36, default value is 1.
     * @param Period Purchase duration, max number is 36, default value is 1.
     */
    public void setPeriod(Long Period) {
        this.Period = Period;
    }

    /**
     * Get Purchase duration unit. valid values: 
m: month,
y: year. 
default value is: m. 
     * @return PeriodUnit Purchase duration unit. valid values: 
m: month,
y: year. 
default value is: m.
     */
    public String getPeriodUnit() {
        return this.PeriodUnit;
    }

    /**
     * Set Purchase duration unit. valid values: 
m: month,
y: year. 
default value is: m.
     * @param PeriodUnit Purchase duration unit. valid values: 
m: month,
y: year. 
default value is: m.
     */
    public void setPeriodUnit(String PeriodUnit) {
        this.PeriodUnit = PeriodUnit;
    }

    /**
     * Get Auto-renewal flag. valid values: NOTIFY_AND_MANUAL_RENEW: manually renew, NOTIFY_AND_AUTO_RENEW: automatically renew, DISABLE_NOTIFY_AND_MANUAL_RENEW: renewal is disabled. 
default value is NOTIFY_AND_MANUAL_RENEW. 
     * @return RenewFlag Auto-renewal flag. valid values: NOTIFY_AND_MANUAL_RENEW: manually renew, NOTIFY_AND_AUTO_RENEW: automatically renew, DISABLE_NOTIFY_AND_MANUAL_RENEW: renewal is disabled. 
default value is NOTIFY_AND_MANUAL_RENEW.
     */
    public String getRenewFlag() {
        return this.RenewFlag;
    }

    /**
     * Set Auto-renewal flag. valid values: NOTIFY_AND_MANUAL_RENEW: manually renew, NOTIFY_AND_AUTO_RENEW: automatically renew, DISABLE_NOTIFY_AND_MANUAL_RENEW: renewal is disabled. 
default value is NOTIFY_AND_MANUAL_RENEW.
     * @param RenewFlag Auto-renewal flag. valid values: NOTIFY_AND_MANUAL_RENEW: manually renew, NOTIFY_AND_AUTO_RENEW: automatically renew, DISABLE_NOTIFY_AND_MANUAL_RENEW: renewal is disabled. 
default value is NOTIFY_AND_MANUAL_RENEW.
     */
    public void setRenewFlag(String RenewFlag) {
        this.RenewFlag = RenewFlag;
    }

    public CreateInstanceRequest() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public CreateInstanceRequest(CreateInstanceRequest source) {
        if (source.ClientToken != null) {
            this.ClientToken = new String(source.ClientToken);
        }
        if (source.ProductCode != null) {
            this.ProductCode = new String(source.ProductCode);
        }
        if (source.SubProductCode != null) {
            this.SubProductCode = new String(source.SubProductCode);
        }
        if (source.RegionCode != null) {
            this.RegionCode = new String(source.RegionCode);
        }
        if (source.ZoneCode != null) {
            this.ZoneCode = new String(source.ZoneCode);
        }
        if (source.PayMode != null) {
            this.PayMode = new String(source.PayMode);
        }
        if (source.Parameter != null) {
            this.Parameter = new String(source.Parameter);
        }
        if (source.Quantity != null) {
            this.Quantity = new Long(source.Quantity);
        }
        if (source.ProjectId != null) {
            this.ProjectId = new Long(source.ProjectId);
        }
        if (source.Period != null) {
            this.Period = new Long(source.Period);
        }
        if (source.PeriodUnit != null) {
            this.PeriodUnit = new String(source.PeriodUnit);
        }
        if (source.RenewFlag != null) {
            this.RenewFlag = new String(source.RenewFlag);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "ClientToken", this.ClientToken);
        this.setParamSimple(map, prefix + "ProductCode", this.ProductCode);
        this.setParamSimple(map, prefix + "SubProductCode", this.SubProductCode);
        this.setParamSimple(map, prefix + "RegionCode", this.RegionCode);
        this.setParamSimple(map, prefix + "ZoneCode", this.ZoneCode);
        this.setParamSimple(map, prefix + "PayMode", this.PayMode);
        this.setParamSimple(map, prefix + "Parameter", this.Parameter);
        this.setParamSimple(map, prefix + "Quantity", this.Quantity);
        this.setParamSimple(map, prefix + "ProjectId", this.ProjectId);
        this.setParamSimple(map, prefix + "Period", this.Period);
        this.setParamSimple(map, prefix + "PeriodUnit", this.PeriodUnit);
        this.setParamSimple(map, prefix + "RenewFlag", this.RenewFlag);

    }
}

