/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.billing.v20180709.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeAllocateConditionsResponse extends AbstractModel {

    /**
    * Product filter list
    */
    @SerializedName("Business")
    @Expose
    private BillBusinessLink [] Business;

    /**
    * Subproduct filter list
    */
    @SerializedName("Product")
    @Expose
    private BillProduct [] Product;

    /**
    * Component name filter list
    */
    @SerializedName("Item")
    @Expose
    private BillItem [] Item;

    /**
    * Region filter list
    */
    @SerializedName("Region")
    @Expose
    private BillRegion [] Region;

    /**
    * Instance type filter list
    */
    @SerializedName("InstanceType")
    @Expose
    private BillInstanceType [] InstanceType;

    /**
    * Billing mode filter list
    */
    @SerializedName("PayMode")
    @Expose
    private BillPayMode [] PayMode;

    /**
    * Project filter list
    */
    @SerializedName("Project")
    @Expose
    private BillProject [] Project;

    /**
    * Tag filter list
    */
    @SerializedName("Tag")
    @Expose
    private BillTag [] Tag;

    /**
    * User UIN filter list
    */
    @SerializedName("OwnerUin")
    @Expose
    private BillOwnerUin [] OwnerUin;

    /**
    * Operator UIN filter list
    */
    @SerializedName("OperateUin")
    @Expose
    private BillOperateUin [] OperateUin;

    /**
    * Transaction type filter list
    */
    @SerializedName("ActionType")
    @Expose
    private BillActionType [] ActionType;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Product filter list 
     * @return Business Product filter list
     */
    public BillBusinessLink [] getBusiness() {
        return this.Business;
    }

    /**
     * Set Product filter list
     * @param Business Product filter list
     */
    public void setBusiness(BillBusinessLink [] Business) {
        this.Business = Business;
    }

    /**
     * Get Subproduct filter list 
     * @return Product Subproduct filter list
     */
    public BillProduct [] getProduct() {
        return this.Product;
    }

    /**
     * Set Subproduct filter list
     * @param Product Subproduct filter list
     */
    public void setProduct(BillProduct [] Product) {
        this.Product = Product;
    }

    /**
     * Get Component name filter list 
     * @return Item Component name filter list
     */
    public BillItem [] getItem() {
        return this.Item;
    }

    /**
     * Set Component name filter list
     * @param Item Component name filter list
     */
    public void setItem(BillItem [] Item) {
        this.Item = Item;
    }

    /**
     * Get Region filter list 
     * @return Region Region filter list
     */
    public BillRegion [] getRegion() {
        return this.Region;
    }

    /**
     * Set Region filter list
     * @param Region Region filter list
     */
    public void setRegion(BillRegion [] Region) {
        this.Region = Region;
    }

    /**
     * Get Instance type filter list 
     * @return InstanceType Instance type filter list
     */
    public BillInstanceType [] getInstanceType() {
        return this.InstanceType;
    }

    /**
     * Set Instance type filter list
     * @param InstanceType Instance type filter list
     */
    public void setInstanceType(BillInstanceType [] InstanceType) {
        this.InstanceType = InstanceType;
    }

    /**
     * Get Billing mode filter list 
     * @return PayMode Billing mode filter list
     */
    public BillPayMode [] getPayMode() {
        return this.PayMode;
    }

    /**
     * Set Billing mode filter list
     * @param PayMode Billing mode filter list
     */
    public void setPayMode(BillPayMode [] PayMode) {
        this.PayMode = PayMode;
    }

    /**
     * Get Project filter list 
     * @return Project Project filter list
     */
    public BillProject [] getProject() {
        return this.Project;
    }

    /**
     * Set Project filter list
     * @param Project Project filter list
     */
    public void setProject(BillProject [] Project) {
        this.Project = Project;
    }

    /**
     * Get Tag filter list 
     * @return Tag Tag filter list
     */
    public BillTag [] getTag() {
        return this.Tag;
    }

    /**
     * Set Tag filter list
     * @param Tag Tag filter list
     */
    public void setTag(BillTag [] Tag) {
        this.Tag = Tag;
    }

    /**
     * Get User UIN filter list 
     * @return OwnerUin User UIN filter list
     */
    public BillOwnerUin [] getOwnerUin() {
        return this.OwnerUin;
    }

    /**
     * Set User UIN filter list
     * @param OwnerUin User UIN filter list
     */
    public void setOwnerUin(BillOwnerUin [] OwnerUin) {
        this.OwnerUin = OwnerUin;
    }

    /**
     * Get Operator UIN filter list 
     * @return OperateUin Operator UIN filter list
     */
    public BillOperateUin [] getOperateUin() {
        return this.OperateUin;
    }

    /**
     * Set Operator UIN filter list
     * @param OperateUin Operator UIN filter list
     */
    public void setOperateUin(BillOperateUin [] OperateUin) {
        this.OperateUin = OperateUin;
    }

    /**
     * Get Transaction type filter list 
     * @return ActionType Transaction type filter list
     */
    public BillActionType [] getActionType() {
        return this.ActionType;
    }

    /**
     * Set Transaction type filter list
     * @param ActionType Transaction type filter list
     */
    public void setActionType(BillActionType [] ActionType) {
        this.ActionType = ActionType;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeAllocateConditionsResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeAllocateConditionsResponse(DescribeAllocateConditionsResponse source) {
        if (source.Business != null) {
            this.Business = new BillBusinessLink[source.Business.length];
            for (int i = 0; i < source.Business.length; i++) {
                this.Business[i] = new BillBusinessLink(source.Business[i]);
            }
        }
        if (source.Product != null) {
            this.Product = new BillProduct[source.Product.length];
            for (int i = 0; i < source.Product.length; i++) {
                this.Product[i] = new BillProduct(source.Product[i]);
            }
        }
        if (source.Item != null) {
            this.Item = new BillItem[source.Item.length];
            for (int i = 0; i < source.Item.length; i++) {
                this.Item[i] = new BillItem(source.Item[i]);
            }
        }
        if (source.Region != null) {
            this.Region = new BillRegion[source.Region.length];
            for (int i = 0; i < source.Region.length; i++) {
                this.Region[i] = new BillRegion(source.Region[i]);
            }
        }
        if (source.InstanceType != null) {
            this.InstanceType = new BillInstanceType[source.InstanceType.length];
            for (int i = 0; i < source.InstanceType.length; i++) {
                this.InstanceType[i] = new BillInstanceType(source.InstanceType[i]);
            }
        }
        if (source.PayMode != null) {
            this.PayMode = new BillPayMode[source.PayMode.length];
            for (int i = 0; i < source.PayMode.length; i++) {
                this.PayMode[i] = new BillPayMode(source.PayMode[i]);
            }
        }
        if (source.Project != null) {
            this.Project = new BillProject[source.Project.length];
            for (int i = 0; i < source.Project.length; i++) {
                this.Project[i] = new BillProject(source.Project[i]);
            }
        }
        if (source.Tag != null) {
            this.Tag = new BillTag[source.Tag.length];
            for (int i = 0; i < source.Tag.length; i++) {
                this.Tag[i] = new BillTag(source.Tag[i]);
            }
        }
        if (source.OwnerUin != null) {
            this.OwnerUin = new BillOwnerUin[source.OwnerUin.length];
            for (int i = 0; i < source.OwnerUin.length; i++) {
                this.OwnerUin[i] = new BillOwnerUin(source.OwnerUin[i]);
            }
        }
        if (source.OperateUin != null) {
            this.OperateUin = new BillOperateUin[source.OperateUin.length];
            for (int i = 0; i < source.OperateUin.length; i++) {
                this.OperateUin[i] = new BillOperateUin(source.OperateUin[i]);
            }
        }
        if (source.ActionType != null) {
            this.ActionType = new BillActionType[source.ActionType.length];
            for (int i = 0; i < source.ActionType.length; i++) {
                this.ActionType[i] = new BillActionType(source.ActionType[i]);
            }
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamArrayObj(map, prefix + "Business.", this.Business);
        this.setParamArrayObj(map, prefix + "Product.", this.Product);
        this.setParamArrayObj(map, prefix + "Item.", this.Item);
        this.setParamArrayObj(map, prefix + "Region.", this.Region);
        this.setParamArrayObj(map, prefix + "InstanceType.", this.InstanceType);
        this.setParamArrayObj(map, prefix + "PayMode.", this.PayMode);
        this.setParamArrayObj(map, prefix + "Project.", this.Project);
        this.setParamArrayObj(map, prefix + "Tag.", this.Tag);
        this.setParamArrayObj(map, prefix + "OwnerUin.", this.OwnerUin);
        this.setParamArrayObj(map, prefix + "OperateUin.", this.OperateUin);
        this.setParamArrayObj(map, prefix + "ActionType.", this.ActionType);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

