/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.billing.v20180709.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeAllocationBillDetailResponse extends AbstractModel {

    /**
    * Total quantity.
    */
    @SerializedName("RecordNum")
    @Expose
    private Long RecordNum;

    /**
    * Total amount of a cost allocation bill
    */
    @SerializedName("Total")
    @Expose
    private AllocationOverviewTotal Total;

    /**
    * Details of a cost allocation bill
    */
    @SerializedName("Detail")
    @Expose
    private AllocationDetail [] Detail;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Total quantity. 
     * @return RecordNum Total quantity.
     */
    public Long getRecordNum() {
        return this.RecordNum;
    }

    /**
     * Set Total quantity.
     * @param RecordNum Total quantity.
     */
    public void setRecordNum(Long RecordNum) {
        this.RecordNum = RecordNum;
    }

    /**
     * Get Total amount of a cost allocation bill 
     * @return Total Total amount of a cost allocation bill
     */
    public AllocationOverviewTotal getTotal() {
        return this.Total;
    }

    /**
     * Set Total amount of a cost allocation bill
     * @param Total Total amount of a cost allocation bill
     */
    public void setTotal(AllocationOverviewTotal Total) {
        this.Total = Total;
    }

    /**
     * Get Details of a cost allocation bill 
     * @return Detail Details of a cost allocation bill
     */
    public AllocationDetail [] getDetail() {
        return this.Detail;
    }

    /**
     * Set Details of a cost allocation bill
     * @param Detail Details of a cost allocation bill
     */
    public void setDetail(AllocationDetail [] Detail) {
        this.Detail = Detail;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeAllocationBillDetailResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeAllocationBillDetailResponse(DescribeAllocationBillDetailResponse source) {
        if (source.RecordNum != null) {
            this.RecordNum = new Long(source.RecordNum);
        }
        if (source.Total != null) {
            this.Total = new AllocationOverviewTotal(source.Total);
        }
        if (source.Detail != null) {
            this.Detail = new AllocationDetail[source.Detail.length];
            for (int i = 0; i < source.Detail.length; i++) {
                this.Detail[i] = new AllocationDetail(source.Detail[i]);
            }
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "RecordNum", this.RecordNum);
        this.setParamObj(map, prefix + "Total.", this.Total);
        this.setParamArrayObj(map, prefix + "Detail.", this.Detail);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

