/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.ga2.v20250115.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeGlobalAcceleratorAclPoliciesResponse extends AbstractModel {

    /**
    * <p>Access control policy information.</p>
    */
    @SerializedName("GlobalAcceleratorAclPolicySet")
    @Expose
    private GlobalAcceleratorAclPolicies [] GlobalAcceleratorAclPolicySet;

    /**
    * <p>Total number of instances that meet the criteria.</p>
    */
    @SerializedName("TotalCount")
    @Expose
    private Long TotalCount;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get <p>Access control policy information.</p> 
     * @return GlobalAcceleratorAclPolicySet <p>Access control policy information.</p>
     */
    public GlobalAcceleratorAclPolicies [] getGlobalAcceleratorAclPolicySet() {
        return this.GlobalAcceleratorAclPolicySet;
    }

    /**
     * Set <p>Access control policy information.</p>
     * @param GlobalAcceleratorAclPolicySet <p>Access control policy information.</p>
     */
    public void setGlobalAcceleratorAclPolicySet(GlobalAcceleratorAclPolicies [] GlobalAcceleratorAclPolicySet) {
        this.GlobalAcceleratorAclPolicySet = GlobalAcceleratorAclPolicySet;
    }

    /**
     * Get <p>Total number of instances that meet the criteria.</p> 
     * @return TotalCount <p>Total number of instances that meet the criteria.</p>
     */
    public Long getTotalCount() {
        return this.TotalCount;
    }

    /**
     * Set <p>Total number of instances that meet the criteria.</p>
     * @param TotalCount <p>Total number of instances that meet the criteria.</p>
     */
    public void setTotalCount(Long TotalCount) {
        this.TotalCount = TotalCount;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeGlobalAcceleratorAclPoliciesResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeGlobalAcceleratorAclPoliciesResponse(DescribeGlobalAcceleratorAclPoliciesResponse source) {
        if (source.GlobalAcceleratorAclPolicySet != null) {
            this.GlobalAcceleratorAclPolicySet = new GlobalAcceleratorAclPolicies[source.GlobalAcceleratorAclPolicySet.length];
            for (int i = 0; i < source.GlobalAcceleratorAclPolicySet.length; i++) {
                this.GlobalAcceleratorAclPolicySet[i] = new GlobalAcceleratorAclPolicies(source.GlobalAcceleratorAclPolicySet[i]);
            }
        }
        if (source.TotalCount != null) {
            this.TotalCount = new Long(source.TotalCount);
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamArrayObj(map, prefix + "GlobalAcceleratorAclPolicySet.", this.GlobalAcceleratorAclPolicySet);
        this.setParamSimple(map, prefix + "TotalCount", this.TotalCount);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

