/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.trtc.v20190722.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class TextToSpeechResponse extends AbstractModel {

    /**
    * Base64-Encoded audio data.
    */
    @SerializedName("Audio")
    @Expose
    private String Audio;

    /**
    * 
    */
    @SerializedName("Alignments")
    @Expose
    private AlignmentItem [] Alignments;

    /**
    * 
    */
    @SerializedName("TotalDurationMs")
    @Expose
    private Long TotalDurationMs;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Base64-Encoded audio data. 
     * @return Audio Base64-Encoded audio data.
     */
    public String getAudio() {
        return this.Audio;
    }

    /**
     * Set Base64-Encoded audio data.
     * @param Audio Base64-Encoded audio data.
     */
    public void setAudio(String Audio) {
        this.Audio = Audio;
    }

    /**
     * Get  
     * @return Alignments 
     */
    public AlignmentItem [] getAlignments() {
        return this.Alignments;
    }

    /**
     * Set 
     * @param Alignments 
     */
    public void setAlignments(AlignmentItem [] Alignments) {
        this.Alignments = Alignments;
    }

    /**
     * Get  
     * @return TotalDurationMs 
     */
    public Long getTotalDurationMs() {
        return this.TotalDurationMs;
    }

    /**
     * Set 
     * @param TotalDurationMs 
     */
    public void setTotalDurationMs(Long TotalDurationMs) {
        this.TotalDurationMs = TotalDurationMs;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public TextToSpeechResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public TextToSpeechResponse(TextToSpeechResponse source) {
        if (source.Audio != null) {
            this.Audio = new String(source.Audio);
        }
        if (source.Alignments != null) {
            this.Alignments = new AlignmentItem[source.Alignments.length];
            for (int i = 0; i < source.Alignments.length; i++) {
                this.Alignments[i] = new AlignmentItem(source.Alignments[i]);
            }
        }
        if (source.TotalDurationMs != null) {
            this.TotalDurationMs = new Long(source.TotalDurationMs);
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "Audio", this.Audio);
        this.setParamArrayObj(map, prefix + "Alignments.", this.Alignments);
        this.setParamSimple(map, prefix + "TotalDurationMs", this.TotalDurationMs);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

