/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.mongodb.v20190725.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeAuditConfigResponse extends AbstractModel {

    /**
    * Instance ID.
Note: This field may return null, indicating that no valid values can be obtained.
    */
    @SerializedName("InstanceId")
    @Expose
    private String InstanceId;

    /**
    * Instance name.
Note: This field may return null, indicating that no valid values can be obtained.
    */
    @SerializedName("InstanceName")
    @Expose
    private String InstanceName;

    /**
    * true indicates full audit, false indicates rule audit
Note: This field may return null, indicating that no valid values can be obtained.
    */
    @SerializedName("AuditAll")
    @Expose
    private Boolean AuditAll;

    /**
    * The time when the instance enables database audit.
    */
    @SerializedName("CreateTime")
    @Expose
    private String CreateTime;

    /**
    * Audit log retention period.
Unit: day. Currently supports retention duration including 0, 30, 180, 365, 1095, 1825.
Note: This field may return null, indicating that no valid values can be obtained.
    */
    @SerializedName("LogExpireDay")
    @Expose
    private Long LogExpireDay;

    /**
    * Audit log storage type. Currently only support "storage": Storage type.
    */
    @SerializedName("LogType")
    @Expose
    private String LogType;

    /**
    * Whether the auditing feature is being disabled.
<ul><li>true: Yes.</li><li>false: No.</li></ul>
    */
    @SerializedName("IsClosing")
    @Expose
    private String IsClosing;

    /**
    * Whether the audit feature is being enabled.<ul><li>true: Yes.</li><li>false: No.</li></ul>
    */
    @SerializedName("IsOpening")
    @Expose
    private String IsOpening;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Instance ID.
Note: This field may return null, indicating that no valid values can be obtained. 
     * @return InstanceId Instance ID.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public String getInstanceId() {
        return this.InstanceId;
    }

    /**
     * Set Instance ID.
Note: This field may return null, indicating that no valid values can be obtained.
     * @param InstanceId Instance ID.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public void setInstanceId(String InstanceId) {
        this.InstanceId = InstanceId;
    }

    /**
     * Get Instance name.
Note: This field may return null, indicating that no valid values can be obtained. 
     * @return InstanceName Instance name.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public String getInstanceName() {
        return this.InstanceName;
    }

    /**
     * Set Instance name.
Note: This field may return null, indicating that no valid values can be obtained.
     * @param InstanceName Instance name.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public void setInstanceName(String InstanceName) {
        this.InstanceName = InstanceName;
    }

    /**
     * Get true indicates full audit, false indicates rule audit
Note: This field may return null, indicating that no valid values can be obtained. 
     * @return AuditAll true indicates full audit, false indicates rule audit
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public Boolean getAuditAll() {
        return this.AuditAll;
    }

    /**
     * Set true indicates full audit, false indicates rule audit
Note: This field may return null, indicating that no valid values can be obtained.
     * @param AuditAll true indicates full audit, false indicates rule audit
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public void setAuditAll(Boolean AuditAll) {
        this.AuditAll = AuditAll;
    }

    /**
     * Get The time when the instance enables database audit. 
     * @return CreateTime The time when the instance enables database audit.
     */
    public String getCreateTime() {
        return this.CreateTime;
    }

    /**
     * Set The time when the instance enables database audit.
     * @param CreateTime The time when the instance enables database audit.
     */
    public void setCreateTime(String CreateTime) {
        this.CreateTime = CreateTime;
    }

    /**
     * Get Audit log retention period.
Unit: day. Currently supports retention duration including 0, 30, 180, 365, 1095, 1825.
Note: This field may return null, indicating that no valid values can be obtained. 
     * @return LogExpireDay Audit log retention period.
Unit: day. Currently supports retention duration including 0, 30, 180, 365, 1095, 1825.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public Long getLogExpireDay() {
        return this.LogExpireDay;
    }

    /**
     * Set Audit log retention period.
Unit: day. Currently supports retention duration including 0, 30, 180, 365, 1095, 1825.
Note: This field may return null, indicating that no valid values can be obtained.
     * @param LogExpireDay Audit log retention period.
Unit: day. Currently supports retention duration including 0, 30, 180, 365, 1095, 1825.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public void setLogExpireDay(Long LogExpireDay) {
        this.LogExpireDay = LogExpireDay;
    }

    /**
     * Get Audit log storage type. Currently only support "storage": Storage type. 
     * @return LogType Audit log storage type. Currently only support "storage": Storage type.
     */
    public String getLogType() {
        return this.LogType;
    }

    /**
     * Set Audit log storage type. Currently only support "storage": Storage type.
     * @param LogType Audit log storage type. Currently only support "storage": Storage type.
     */
    public void setLogType(String LogType) {
        this.LogType = LogType;
    }

    /**
     * Get Whether the auditing feature is being disabled.
<ul><li>true: Yes.</li><li>false: No.</li></ul> 
     * @return IsClosing Whether the auditing feature is being disabled.
<ul><li>true: Yes.</li><li>false: No.</li></ul>
     */
    public String getIsClosing() {
        return this.IsClosing;
    }

    /**
     * Set Whether the auditing feature is being disabled.
<ul><li>true: Yes.</li><li>false: No.</li></ul>
     * @param IsClosing Whether the auditing feature is being disabled.
<ul><li>true: Yes.</li><li>false: No.</li></ul>
     */
    public void setIsClosing(String IsClosing) {
        this.IsClosing = IsClosing;
    }

    /**
     * Get Whether the audit feature is being enabled.<ul><li>true: Yes.</li><li>false: No.</li></ul> 
     * @return IsOpening Whether the audit feature is being enabled.<ul><li>true: Yes.</li><li>false: No.</li></ul>
     */
    public String getIsOpening() {
        return this.IsOpening;
    }

    /**
     * Set Whether the audit feature is being enabled.<ul><li>true: Yes.</li><li>false: No.</li></ul>
     * @param IsOpening Whether the audit feature is being enabled.<ul><li>true: Yes.</li><li>false: No.</li></ul>
     */
    public void setIsOpening(String IsOpening) {
        this.IsOpening = IsOpening;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeAuditConfigResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeAuditConfigResponse(DescribeAuditConfigResponse source) {
        if (source.InstanceId != null) {
            this.InstanceId = new String(source.InstanceId);
        }
        if (source.InstanceName != null) {
            this.InstanceName = new String(source.InstanceName);
        }
        if (source.AuditAll != null) {
            this.AuditAll = new Boolean(source.AuditAll);
        }
        if (source.CreateTime != null) {
            this.CreateTime = new String(source.CreateTime);
        }
        if (source.LogExpireDay != null) {
            this.LogExpireDay = new Long(source.LogExpireDay);
        }
        if (source.LogType != null) {
            this.LogType = new String(source.LogType);
        }
        if (source.IsClosing != null) {
            this.IsClosing = new String(source.IsClosing);
        }
        if (source.IsOpening != null) {
            this.IsOpening = new String(source.IsOpening);
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "InstanceId", this.InstanceId);
        this.setParamSimple(map, prefix + "InstanceName", this.InstanceName);
        this.setParamSimple(map, prefix + "AuditAll", this.AuditAll);
        this.setParamSimple(map, prefix + "CreateTime", this.CreateTime);
        this.setParamSimple(map, prefix + "LogExpireDay", this.LogExpireDay);
        this.setParamSimple(map, prefix + "LogType", this.LogType);
        this.setParamSimple(map, prefix + "IsClosing", this.IsClosing);
        this.setParamSimple(map, prefix + "IsOpening", this.IsOpening);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

