/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.tokenhub.v20260322.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class CreateTokenPlanApiKeysResponse extends AbstractModel {

    /**
    * Item list of successful creation.
    */
    @SerializedName("Items")
    @Expose
    private CreateApiKeysResultItem [] Items;

    /**
    * Item list that failed to be created.
    */
    @SerializedName("FailedItems")
    @Expose
    private BatchCreateFailedItem [] FailedItems;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Item list of successful creation. 
     * @return Items Item list of successful creation.
     */
    public CreateApiKeysResultItem [] getItems() {
        return this.Items;
    }

    /**
     * Set Item list of successful creation.
     * @param Items Item list of successful creation.
     */
    public void setItems(CreateApiKeysResultItem [] Items) {
        this.Items = Items;
    }

    /**
     * Get Item list that failed to be created. 
     * @return FailedItems Item list that failed to be created.
     */
    public BatchCreateFailedItem [] getFailedItems() {
        return this.FailedItems;
    }

    /**
     * Set Item list that failed to be created.
     * @param FailedItems Item list that failed to be created.
     */
    public void setFailedItems(BatchCreateFailedItem [] FailedItems) {
        this.FailedItems = FailedItems;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public CreateTokenPlanApiKeysResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public CreateTokenPlanApiKeysResponse(CreateTokenPlanApiKeysResponse source) {
        if (source.Items != null) {
            this.Items = new CreateApiKeysResultItem[source.Items.length];
            for (int i = 0; i < source.Items.length; i++) {
                this.Items[i] = new CreateApiKeysResultItem(source.Items[i]);
            }
        }
        if (source.FailedItems != null) {
            this.FailedItems = new BatchCreateFailedItem[source.FailedItems.length];
            for (int i = 0; i < source.FailedItems.length; i++) {
                this.FailedItems[i] = new BatchCreateFailedItem(source.FailedItems[i]);
            }
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamArrayObj(map, prefix + "Items.", this.Items);
        this.setParamArrayObj(map, prefix + "FailedItems.", this.FailedItems);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

