/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.tokenhub.v20260322.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeUsageRankListResponse extends AbstractModel {

    /**
    * <p>Statistical dimension of the backfill request.</p>
    */
    @SerializedName("Dimension")
    @Expose
    private String Dimension;

    /**
    * <p>Metrics family of the backfill request: tokens / search.</p>
    */
    @SerializedName("MetricType")
    @Expose
    private String MetricType;

    /**
    * <p>List of metric keys actually included in Stats / Series / PageStats / TotalStats in this response, case-sensitive by MetricType: tokens=[Total,Input,Output,Cache], search=[SearchRequestCount,SearchCount]</p>
    */
    @SerializedName("MetricKeys")
    @Expose
    private String [] MetricKeys;

    /**
    * <p>View (data source)</p>
    */
    @SerializedName("ViewName")
    @Expose
    private String ViewName;

    /**
    * <p>Statistical granularity (in seconds) of the backfill request. It is 0 when ShowAll=true.</p>
    */
    @SerializedName("Period")
    @Expose
    private Long Period;

    /**
    * <p>Backfill the start time of the request.</p>
    */
    @SerializedName("StartTime")
    @Expose
    private String StartTime;

    /**
    * <p>End time of the backfill request.</p>
    */
    @SerializedName("EndTime")
    @Expose
    private String EndTime;

    /**
    * <p>Total number of objects.</p>
    */
    @SerializedName("Total")
    @Expose
    private Long Total;

    /**
    * <p>Backfill the pagination starting point of the request. It is 0 when ShowAll=true.</p>
    */
    @SerializedName("Offset")
    @Expose
    private Long Offset;

    /**
    * <p>Page size. It is always 10. When ShowAll=true, it is Total.</p>
    */
    @SerializedName("Limit")
    @Expose
    private Long Limit;

    /**
    * <p>Timestamp sequence corresponding to the Series array (Unix seconds). Empty array when ShowAll=true.</p>
    */
    @SerializedName("Timestamps")
    @Expose
    private Long [] Timestamps;

    /**
    * <p>Object ranking list, sorted by <code>MetricKeys[0]</code> in descending order. When ShowAll=false, it is the 10 objects on the current page (including Series); when ShowAll=true, it is all objects (excluding Series, used for CSV export).</p>
    */
    @SerializedName("TopList")
    @Expose
    private UsageRankItem [] TopList;

    /**
    * <p>Pagination statistics result</p>
    */
    @SerializedName("PageStats")
    @Expose
    private UsageStats PageStats;

    /**
    * <p>Total statistics result</p>
    */
    @SerializedName("TotalStats")
    @Expose
    private UsageStats TotalStats;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get <p>Statistical dimension of the backfill request.</p> 
     * @return Dimension <p>Statistical dimension of the backfill request.</p>
     */
    public String getDimension() {
        return this.Dimension;
    }

    /**
     * Set <p>Statistical dimension of the backfill request.</p>
     * @param Dimension <p>Statistical dimension of the backfill request.</p>
     */
    public void setDimension(String Dimension) {
        this.Dimension = Dimension;
    }

    /**
     * Get <p>Metrics family of the backfill request: tokens / search.</p> 
     * @return MetricType <p>Metrics family of the backfill request: tokens / search.</p>
     */
    public String getMetricType() {
        return this.MetricType;
    }

    /**
     * Set <p>Metrics family of the backfill request: tokens / search.</p>
     * @param MetricType <p>Metrics family of the backfill request: tokens / search.</p>
     */
    public void setMetricType(String MetricType) {
        this.MetricType = MetricType;
    }

    /**
     * Get <p>List of metric keys actually included in Stats / Series / PageStats / TotalStats in this response, case-sensitive by MetricType: tokens=[Total,Input,Output,Cache], search=[SearchRequestCount,SearchCount]</p> 
     * @return MetricKeys <p>List of metric keys actually included in Stats / Series / PageStats / TotalStats in this response, case-sensitive by MetricType: tokens=[Total,Input,Output,Cache], search=[SearchRequestCount,SearchCount]</p>
     */
    public String [] getMetricKeys() {
        return this.MetricKeys;
    }

    /**
     * Set <p>List of metric keys actually included in Stats / Series / PageStats / TotalStats in this response, case-sensitive by MetricType: tokens=[Total,Input,Output,Cache], search=[SearchRequestCount,SearchCount]</p>
     * @param MetricKeys <p>List of metric keys actually included in Stats / Series / PageStats / TotalStats in this response, case-sensitive by MetricType: tokens=[Total,Input,Output,Cache], search=[SearchRequestCount,SearchCount]</p>
     */
    public void setMetricKeys(String [] MetricKeys) {
        this.MetricKeys = MetricKeys;
    }

    /**
     * Get <p>View (data source)</p> 
     * @return ViewName <p>View (data source)</p>
     */
    public String getViewName() {
        return this.ViewName;
    }

    /**
     * Set <p>View (data source)</p>
     * @param ViewName <p>View (data source)</p>
     */
    public void setViewName(String ViewName) {
        this.ViewName = ViewName;
    }

    /**
     * Get <p>Statistical granularity (in seconds) of the backfill request. It is 0 when ShowAll=true.</p> 
     * @return Period <p>Statistical granularity (in seconds) of the backfill request. It is 0 when ShowAll=true.</p>
     */
    public Long getPeriod() {
        return this.Period;
    }

    /**
     * Set <p>Statistical granularity (in seconds) of the backfill request. It is 0 when ShowAll=true.</p>
     * @param Period <p>Statistical granularity (in seconds) of the backfill request. It is 0 when ShowAll=true.</p>
     */
    public void setPeriod(Long Period) {
        this.Period = Period;
    }

    /**
     * Get <p>Backfill the start time of the request.</p> 
     * @return StartTime <p>Backfill the start time of the request.</p>
     */
    public String getStartTime() {
        return this.StartTime;
    }

    /**
     * Set <p>Backfill the start time of the request.</p>
     * @param StartTime <p>Backfill the start time of the request.</p>
     */
    public void setStartTime(String StartTime) {
        this.StartTime = StartTime;
    }

    /**
     * Get <p>End time of the backfill request.</p> 
     * @return EndTime <p>End time of the backfill request.</p>
     */
    public String getEndTime() {
        return this.EndTime;
    }

    /**
     * Set <p>End time of the backfill request.</p>
     * @param EndTime <p>End time of the backfill request.</p>
     */
    public void setEndTime(String EndTime) {
        this.EndTime = EndTime;
    }

    /**
     * Get <p>Total number of objects.</p> 
     * @return Total <p>Total number of objects.</p>
     */
    public Long getTotal() {
        return this.Total;
    }

    /**
     * Set <p>Total number of objects.</p>
     * @param Total <p>Total number of objects.</p>
     */
    public void setTotal(Long Total) {
        this.Total = Total;
    }

    /**
     * Get <p>Backfill the pagination starting point of the request. It is 0 when ShowAll=true.</p> 
     * @return Offset <p>Backfill the pagination starting point of the request. It is 0 when ShowAll=true.</p>
     */
    public Long getOffset() {
        return this.Offset;
    }

    /**
     * Set <p>Backfill the pagination starting point of the request. It is 0 when ShowAll=true.</p>
     * @param Offset <p>Backfill the pagination starting point of the request. It is 0 when ShowAll=true.</p>
     */
    public void setOffset(Long Offset) {
        this.Offset = Offset;
    }

    /**
     * Get <p>Page size. It is always 10. When ShowAll=true, it is Total.</p> 
     * @return Limit <p>Page size. It is always 10. When ShowAll=true, it is Total.</p>
     */
    public Long getLimit() {
        return this.Limit;
    }

    /**
     * Set <p>Page size. It is always 10. When ShowAll=true, it is Total.</p>
     * @param Limit <p>Page size. It is always 10. When ShowAll=true, it is Total.</p>
     */
    public void setLimit(Long Limit) {
        this.Limit = Limit;
    }

    /**
     * Get <p>Timestamp sequence corresponding to the Series array (Unix seconds). Empty array when ShowAll=true.</p> 
     * @return Timestamps <p>Timestamp sequence corresponding to the Series array (Unix seconds). Empty array when ShowAll=true.</p>
     */
    public Long [] getTimestamps() {
        return this.Timestamps;
    }

    /**
     * Set <p>Timestamp sequence corresponding to the Series array (Unix seconds). Empty array when ShowAll=true.</p>
     * @param Timestamps <p>Timestamp sequence corresponding to the Series array (Unix seconds). Empty array when ShowAll=true.</p>
     */
    public void setTimestamps(Long [] Timestamps) {
        this.Timestamps = Timestamps;
    }

    /**
     * Get <p>Object ranking list, sorted by <code>MetricKeys[0]</code> in descending order. When ShowAll=false, it is the 10 objects on the current page (including Series); when ShowAll=true, it is all objects (excluding Series, used for CSV export).</p> 
     * @return TopList <p>Object ranking list, sorted by <code>MetricKeys[0]</code> in descending order. When ShowAll=false, it is the 10 objects on the current page (including Series); when ShowAll=true, it is all objects (excluding Series, used for CSV export).</p>
     */
    public UsageRankItem [] getTopList() {
        return this.TopList;
    }

    /**
     * Set <p>Object ranking list, sorted by <code>MetricKeys[0]</code> in descending order. When ShowAll=false, it is the 10 objects on the current page (including Series); when ShowAll=true, it is all objects (excluding Series, used for CSV export).</p>
     * @param TopList <p>Object ranking list, sorted by <code>MetricKeys[0]</code> in descending order. When ShowAll=false, it is the 10 objects on the current page (including Series); when ShowAll=true, it is all objects (excluding Series, used for CSV export).</p>
     */
    public void setTopList(UsageRankItem [] TopList) {
        this.TopList = TopList;
    }

    /**
     * Get <p>Pagination statistics result</p> 
     * @return PageStats <p>Pagination statistics result</p>
     */
    public UsageStats getPageStats() {
        return this.PageStats;
    }

    /**
     * Set <p>Pagination statistics result</p>
     * @param PageStats <p>Pagination statistics result</p>
     */
    public void setPageStats(UsageStats PageStats) {
        this.PageStats = PageStats;
    }

    /**
     * Get <p>Total statistics result</p> 
     * @return TotalStats <p>Total statistics result</p>
     */
    public UsageStats getTotalStats() {
        return this.TotalStats;
    }

    /**
     * Set <p>Total statistics result</p>
     * @param TotalStats <p>Total statistics result</p>
     */
    public void setTotalStats(UsageStats TotalStats) {
        this.TotalStats = TotalStats;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeUsageRankListResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeUsageRankListResponse(DescribeUsageRankListResponse source) {
        if (source.Dimension != null) {
            this.Dimension = new String(source.Dimension);
        }
        if (source.MetricType != null) {
            this.MetricType = new String(source.MetricType);
        }
        if (source.MetricKeys != null) {
            this.MetricKeys = new String[source.MetricKeys.length];
            for (int i = 0; i < source.MetricKeys.length; i++) {
                this.MetricKeys[i] = new String(source.MetricKeys[i]);
            }
        }
        if (source.ViewName != null) {
            this.ViewName = new String(source.ViewName);
        }
        if (source.Period != null) {
            this.Period = new Long(source.Period);
        }
        if (source.StartTime != null) {
            this.StartTime = new String(source.StartTime);
        }
        if (source.EndTime != null) {
            this.EndTime = new String(source.EndTime);
        }
        if (source.Total != null) {
            this.Total = new Long(source.Total);
        }
        if (source.Offset != null) {
            this.Offset = new Long(source.Offset);
        }
        if (source.Limit != null) {
            this.Limit = new Long(source.Limit);
        }
        if (source.Timestamps != null) {
            this.Timestamps = new Long[source.Timestamps.length];
            for (int i = 0; i < source.Timestamps.length; i++) {
                this.Timestamps[i] = new Long(source.Timestamps[i]);
            }
        }
        if (source.TopList != null) {
            this.TopList = new UsageRankItem[source.TopList.length];
            for (int i = 0; i < source.TopList.length; i++) {
                this.TopList[i] = new UsageRankItem(source.TopList[i]);
            }
        }
        if (source.PageStats != null) {
            this.PageStats = new UsageStats(source.PageStats);
        }
        if (source.TotalStats != null) {
            this.TotalStats = new UsageStats(source.TotalStats);
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "Dimension", this.Dimension);
        this.setParamSimple(map, prefix + "MetricType", this.MetricType);
        this.setParamArraySimple(map, prefix + "MetricKeys.", this.MetricKeys);
        this.setParamSimple(map, prefix + "ViewName", this.ViewName);
        this.setParamSimple(map, prefix + "Period", this.Period);
        this.setParamSimple(map, prefix + "StartTime", this.StartTime);
        this.setParamSimple(map, prefix + "EndTime", this.EndTime);
        this.setParamSimple(map, prefix + "Total", this.Total);
        this.setParamSimple(map, prefix + "Offset", this.Offset);
        this.setParamSimple(map, prefix + "Limit", this.Limit);
        this.setParamArraySimple(map, prefix + "Timestamps.", this.Timestamps);
        this.setParamArrayObj(map, prefix + "TopList.", this.TopList);
        this.setParamObj(map, prefix + "PageStats.", this.PageStats);
        this.setParamObj(map, prefix + "TotalStats.", this.TotalStats);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

