/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.tokenhub.v20260322.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeTokenPlanResponse extends AbstractModel {

    /**
    * Package ID
    */
    @SerializedName("TeamId")
    @Expose
    private String TeamId;

    /**
    * Package name.
    */
    @SerializedName("Name")
    @Expose
    private String Name;

    /**
    * Root account APP ID.
    */
    @SerializedName("AppId")
    @Expose
    private String AppId;

    /**
    * Main account UIN.
    */
    @SerializedName("Uin")
    @Expose
    private String Uin;

    /**
    * Status. Valid values: enable, disable.
    */
    @SerializedName("Status")
    @Expose
    private String Status;

    /**
    * Disablement reason. Value: NORMAL, ISOLATED, FROZEN, EXHAUSTED, DESTROYED.
    */
    @SerializedName("StopReason")
    @Expose
    private String StopReason;

    /**
    * Maximum number of API Keys that can be created.
    */
    @SerializedName("ApiKeyMax")
    @Expose
    private Long ApiKeyMax;

    /**
    * Cloud billing prepaid resource package ID.
    */
    @SerializedName("PrepayResourceID")
    @Expose
    private String PrepayResourceID;

    /**
    * Creator. Packages created by a sub-account show the sub-account UIN.
    */
    @SerializedName("Creator")
    @Expose
    private String Creator;

    /**
    * Creation time.
    */
    @SerializedName("CreatedAt")
    @Expose
    private String CreatedAt;

    /**
    * Update time.
    */
    @SerializedName("UpdatedAt")
    @Expose
    private String UpdatedAt;

    /**
    * Basic information of the package.
    */
    @SerializedName("PackageInfo")
    @Expose
    private TokenPlanPackageInfo PackageInfo;

    /**
    * Auto-renewal flag. Value: 0 (manual renewal), 1 (auto renewal), 2 (no automatic renewal). It is not returned if not bound to a prepaid resource.
    */
    @SerializedName("AutoRenewFlag")
    @Expose
    private Long AutoRenewFlag;

    /**
    * Current number of created API Keys.
    */
    @SerializedName("ApiKeyCount")
    @Expose
    private Long ApiKeyCount;

    /**
    * Token usage details in the current cycle
    */
    @SerializedName("TokenSummary")
    @Expose
    private TokenSummary TokenSummary;

    /**
    * Package type. Values: enterprise (Enterprise Professional package), enterprise-auto (Enterprise Light package)
    */
    @SerializedName("ProductType")
    @Expose
    private String ProductType;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Package ID 
     * @return TeamId Package ID
     */
    public String getTeamId() {
        return this.TeamId;
    }

    /**
     * Set Package ID
     * @param TeamId Package ID
     */
    public void setTeamId(String TeamId) {
        this.TeamId = TeamId;
    }

    /**
     * Get Package name. 
     * @return Name Package name.
     */
    public String getName() {
        return this.Name;
    }

    /**
     * Set Package name.
     * @param Name Package name.
     */
    public void setName(String Name) {
        this.Name = Name;
    }

    /**
     * Get Root account APP ID. 
     * @return AppId Root account APP ID.
     */
    public String getAppId() {
        return this.AppId;
    }

    /**
     * Set Root account APP ID.
     * @param AppId Root account APP ID.
     */
    public void setAppId(String AppId) {
        this.AppId = AppId;
    }

    /**
     * Get Main account UIN. 
     * @return Uin Main account UIN.
     */
    public String getUin() {
        return this.Uin;
    }

    /**
     * Set Main account UIN.
     * @param Uin Main account UIN.
     */
    public void setUin(String Uin) {
        this.Uin = Uin;
    }

    /**
     * Get Status. Valid values: enable, disable. 
     * @return Status Status. Valid values: enable, disable.
     */
    public String getStatus() {
        return this.Status;
    }

    /**
     * Set Status. Valid values: enable, disable.
     * @param Status Status. Valid values: enable, disable.
     */
    public void setStatus(String Status) {
        this.Status = Status;
    }

    /**
     * Get Disablement reason. Value: NORMAL, ISOLATED, FROZEN, EXHAUSTED, DESTROYED. 
     * @return StopReason Disablement reason. Value: NORMAL, ISOLATED, FROZEN, EXHAUSTED, DESTROYED.
     */
    public String getStopReason() {
        return this.StopReason;
    }

    /**
     * Set Disablement reason. Value: NORMAL, ISOLATED, FROZEN, EXHAUSTED, DESTROYED.
     * @param StopReason Disablement reason. Value: NORMAL, ISOLATED, FROZEN, EXHAUSTED, DESTROYED.
     */
    public void setStopReason(String StopReason) {
        this.StopReason = StopReason;
    }

    /**
     * Get Maximum number of API Keys that can be created. 
     * @return ApiKeyMax Maximum number of API Keys that can be created.
     */
    public Long getApiKeyMax() {
        return this.ApiKeyMax;
    }

    /**
     * Set Maximum number of API Keys that can be created.
     * @param ApiKeyMax Maximum number of API Keys that can be created.
     */
    public void setApiKeyMax(Long ApiKeyMax) {
        this.ApiKeyMax = ApiKeyMax;
    }

    /**
     * Get Cloud billing prepaid resource package ID. 
     * @return PrepayResourceID Cloud billing prepaid resource package ID.
     */
    public String getPrepayResourceID() {
        return this.PrepayResourceID;
    }

    /**
     * Set Cloud billing prepaid resource package ID.
     * @param PrepayResourceID Cloud billing prepaid resource package ID.
     */
    public void setPrepayResourceID(String PrepayResourceID) {
        this.PrepayResourceID = PrepayResourceID;
    }

    /**
     * Get Creator. Packages created by a sub-account show the sub-account UIN. 
     * @return Creator Creator. Packages created by a sub-account show the sub-account UIN.
     */
    public String getCreator() {
        return this.Creator;
    }

    /**
     * Set Creator. Packages created by a sub-account show the sub-account UIN.
     * @param Creator Creator. Packages created by a sub-account show the sub-account UIN.
     */
    public void setCreator(String Creator) {
        this.Creator = Creator;
    }

    /**
     * Get Creation time. 
     * @return CreatedAt Creation time.
     */
    public String getCreatedAt() {
        return this.CreatedAt;
    }

    /**
     * Set Creation time.
     * @param CreatedAt Creation time.
     */
    public void setCreatedAt(String CreatedAt) {
        this.CreatedAt = CreatedAt;
    }

    /**
     * Get Update time. 
     * @return UpdatedAt Update time.
     */
    public String getUpdatedAt() {
        return this.UpdatedAt;
    }

    /**
     * Set Update time.
     * @param UpdatedAt Update time.
     */
    public void setUpdatedAt(String UpdatedAt) {
        this.UpdatedAt = UpdatedAt;
    }

    /**
     * Get Basic information of the package. 
     * @return PackageInfo Basic information of the package.
     */
    public TokenPlanPackageInfo getPackageInfo() {
        return this.PackageInfo;
    }

    /**
     * Set Basic information of the package.
     * @param PackageInfo Basic information of the package.
     */
    public void setPackageInfo(TokenPlanPackageInfo PackageInfo) {
        this.PackageInfo = PackageInfo;
    }

    /**
     * Get Auto-renewal flag. Value: 0 (manual renewal), 1 (auto renewal), 2 (no automatic renewal). It is not returned if not bound to a prepaid resource. 
     * @return AutoRenewFlag Auto-renewal flag. Value: 0 (manual renewal), 1 (auto renewal), 2 (no automatic renewal). It is not returned if not bound to a prepaid resource.
     */
    public Long getAutoRenewFlag() {
        return this.AutoRenewFlag;
    }

    /**
     * Set Auto-renewal flag. Value: 0 (manual renewal), 1 (auto renewal), 2 (no automatic renewal). It is not returned if not bound to a prepaid resource.
     * @param AutoRenewFlag Auto-renewal flag. Value: 0 (manual renewal), 1 (auto renewal), 2 (no automatic renewal). It is not returned if not bound to a prepaid resource.
     */
    public void setAutoRenewFlag(Long AutoRenewFlag) {
        this.AutoRenewFlag = AutoRenewFlag;
    }

    /**
     * Get Current number of created API Keys. 
     * @return ApiKeyCount Current number of created API Keys.
     */
    public Long getApiKeyCount() {
        return this.ApiKeyCount;
    }

    /**
     * Set Current number of created API Keys.
     * @param ApiKeyCount Current number of created API Keys.
     */
    public void setApiKeyCount(Long ApiKeyCount) {
        this.ApiKeyCount = ApiKeyCount;
    }

    /**
     * Get Token usage details in the current cycle 
     * @return TokenSummary Token usage details in the current cycle
     */
    public TokenSummary getTokenSummary() {
        return this.TokenSummary;
    }

    /**
     * Set Token usage details in the current cycle
     * @param TokenSummary Token usage details in the current cycle
     */
    public void setTokenSummary(TokenSummary TokenSummary) {
        this.TokenSummary = TokenSummary;
    }

    /**
     * Get Package type. Values: enterprise (Enterprise Professional package), enterprise-auto (Enterprise Light package) 
     * @return ProductType Package type. Values: enterprise (Enterprise Professional package), enterprise-auto (Enterprise Light package)
     */
    public String getProductType() {
        return this.ProductType;
    }

    /**
     * Set Package type. Values: enterprise (Enterprise Professional package), enterprise-auto (Enterprise Light package)
     * @param ProductType Package type. Values: enterprise (Enterprise Professional package), enterprise-auto (Enterprise Light package)
     */
    public void setProductType(String ProductType) {
        this.ProductType = ProductType;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeTokenPlanResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeTokenPlanResponse(DescribeTokenPlanResponse source) {
        if (source.TeamId != null) {
            this.TeamId = new String(source.TeamId);
        }
        if (source.Name != null) {
            this.Name = new String(source.Name);
        }
        if (source.AppId != null) {
            this.AppId = new String(source.AppId);
        }
        if (source.Uin != null) {
            this.Uin = new String(source.Uin);
        }
        if (source.Status != null) {
            this.Status = new String(source.Status);
        }
        if (source.StopReason != null) {
            this.StopReason = new String(source.StopReason);
        }
        if (source.ApiKeyMax != null) {
            this.ApiKeyMax = new Long(source.ApiKeyMax);
        }
        if (source.PrepayResourceID != null) {
            this.PrepayResourceID = new String(source.PrepayResourceID);
        }
        if (source.Creator != null) {
            this.Creator = new String(source.Creator);
        }
        if (source.CreatedAt != null) {
            this.CreatedAt = new String(source.CreatedAt);
        }
        if (source.UpdatedAt != null) {
            this.UpdatedAt = new String(source.UpdatedAt);
        }
        if (source.PackageInfo != null) {
            this.PackageInfo = new TokenPlanPackageInfo(source.PackageInfo);
        }
        if (source.AutoRenewFlag != null) {
            this.AutoRenewFlag = new Long(source.AutoRenewFlag);
        }
        if (source.ApiKeyCount != null) {
            this.ApiKeyCount = new Long(source.ApiKeyCount);
        }
        if (source.TokenSummary != null) {
            this.TokenSummary = new TokenSummary(source.TokenSummary);
        }
        if (source.ProductType != null) {
            this.ProductType = new String(source.ProductType);
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "TeamId", this.TeamId);
        this.setParamSimple(map, prefix + "Name", this.Name);
        this.setParamSimple(map, prefix + "AppId", this.AppId);
        this.setParamSimple(map, prefix + "Uin", this.Uin);
        this.setParamSimple(map, prefix + "Status", this.Status);
        this.setParamSimple(map, prefix + "StopReason", this.StopReason);
        this.setParamSimple(map, prefix + "ApiKeyMax", this.ApiKeyMax);
        this.setParamSimple(map, prefix + "PrepayResourceID", this.PrepayResourceID);
        this.setParamSimple(map, prefix + "Creator", this.Creator);
        this.setParamSimple(map, prefix + "CreatedAt", this.CreatedAt);
        this.setParamSimple(map, prefix + "UpdatedAt", this.UpdatedAt);
        this.setParamObj(map, prefix + "PackageInfo.", this.PackageInfo);
        this.setParamSimple(map, prefix + "AutoRenewFlag", this.AutoRenewFlag);
        this.setParamSimple(map, prefix + "ApiKeyCount", this.ApiKeyCount);
        this.setParamObj(map, prefix + "TokenSummary.", this.TokenSummary);
        this.setParamSimple(map, prefix + "ProductType", this.ProductType);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

