/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.tokenhub.v20260322.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeTokenPlanApiKeyResponse extends AbstractModel {

    /**
    * API Key details.
    */
    @SerializedName("ApiKey")
    @Expose
    private TokenPlanApiKeyInfo ApiKey;

    /**
    * API Key limit and usage information.
    */
    @SerializedName("Balance")
    @Expose
    private SubPackageBalance Balance;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get API Key details. 
     * @return ApiKey API Key details.
     */
    public TokenPlanApiKeyInfo getApiKey() {
        return this.ApiKey;
    }

    /**
     * Set API Key details.
     * @param ApiKey API Key details.
     */
    public void setApiKey(TokenPlanApiKeyInfo ApiKey) {
        this.ApiKey = ApiKey;
    }

    /**
     * Get API Key limit and usage information. 
     * @return Balance API Key limit and usage information.
     */
    public SubPackageBalance getBalance() {
        return this.Balance;
    }

    /**
     * Set API Key limit and usage information.
     * @param Balance API Key limit and usage information.
     */
    public void setBalance(SubPackageBalance Balance) {
        this.Balance = Balance;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeTokenPlanApiKeyResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeTokenPlanApiKeyResponse(DescribeTokenPlanApiKeyResponse source) {
        if (source.ApiKey != null) {
            this.ApiKey = new TokenPlanApiKeyInfo(source.ApiKey);
        }
        if (source.Balance != null) {
            this.Balance = new SubPackageBalance(source.Balance);
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamObj(map, prefix + "ApiKey.", this.ApiKey);
        this.setParamObj(map, prefix + "Balance.", this.Balance);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

