/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.csip.v20221121.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribePublicCloudAssetsResponse extends AbstractModel {

    /**
    * Number of assets
    */
    @SerializedName("TotalCount")
    @Expose
    private Long TotalCount;

    /**
    * Asset collection
    */
    @SerializedName("Assets")
    @Expose
    private PublicAssetInfo [] Assets;

    /**
    * Asset type collection
    */
    @SerializedName("AssetTypeList")
    @Expose
    private AttributeOptionSet [] AssetTypeList;

    /**
    * Region collection
    */
    @SerializedName("RegionList")
    @Expose
    private AttributeOptionSet [] RegionList;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Number of assets 
     * @return TotalCount Number of assets
     */
    public Long getTotalCount() {
        return this.TotalCount;
    }

    /**
     * Set Number of assets
     * @param TotalCount Number of assets
     */
    public void setTotalCount(Long TotalCount) {
        this.TotalCount = TotalCount;
    }

    /**
     * Get Asset collection 
     * @return Assets Asset collection
     */
    public PublicAssetInfo [] getAssets() {
        return this.Assets;
    }

    /**
     * Set Asset collection
     * @param Assets Asset collection
     */
    public void setAssets(PublicAssetInfo [] Assets) {
        this.Assets = Assets;
    }

    /**
     * Get Asset type collection 
     * @return AssetTypeList Asset type collection
     */
    public AttributeOptionSet [] getAssetTypeList() {
        return this.AssetTypeList;
    }

    /**
     * Set Asset type collection
     * @param AssetTypeList Asset type collection
     */
    public void setAssetTypeList(AttributeOptionSet [] AssetTypeList) {
        this.AssetTypeList = AssetTypeList;
    }

    /**
     * Get Region collection 
     * @return RegionList Region collection
     */
    public AttributeOptionSet [] getRegionList() {
        return this.RegionList;
    }

    /**
     * Set Region collection
     * @param RegionList Region collection
     */
    public void setRegionList(AttributeOptionSet [] RegionList) {
        this.RegionList = RegionList;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribePublicCloudAssetsResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribePublicCloudAssetsResponse(DescribePublicCloudAssetsResponse source) {
        if (source.TotalCount != null) {
            this.TotalCount = new Long(source.TotalCount);
        }
        if (source.Assets != null) {
            this.Assets = new PublicAssetInfo[source.Assets.length];
            for (int i = 0; i < source.Assets.length; i++) {
                this.Assets[i] = new PublicAssetInfo(source.Assets[i]);
            }
        }
        if (source.AssetTypeList != null) {
            this.AssetTypeList = new AttributeOptionSet[source.AssetTypeList.length];
            for (int i = 0; i < source.AssetTypeList.length; i++) {
                this.AssetTypeList[i] = new AttributeOptionSet(source.AssetTypeList[i]);
            }
        }
        if (source.RegionList != null) {
            this.RegionList = new AttributeOptionSet[source.RegionList.length];
            for (int i = 0; i < source.RegionList.length; i++) {
                this.RegionList[i] = new AttributeOptionSet(source.RegionList[i]);
            }
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "TotalCount", this.TotalCount);
        this.setParamArrayObj(map, prefix + "Assets.", this.Assets);
        this.setParamArrayObj(map, prefix + "AssetTypeList.", this.AssetTypeList);
        this.setParamArrayObj(map, prefix + "RegionList.", this.RegionList);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

