/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.csip.v20221121.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeSecurityScoreOverviewResponse extends AbstractModel {

    /**
    * <p>Security score<br>Value range: [0, 100]</p>
    */
    @SerializedName("Score")
    @Expose
    private Long Score;

    /**
    * <p>Security level<br>Enumeration values:<br>safe: safe (90-100 points)<br>good: good (70-89 points)<br>medium: general (40-69 points)<br>danger: dangerous (0-39 points)</p>
    */
    @SerializedName("Level")
    @Expose
    private String Level;

    /**
    * <p>Score status<br>Enumeration values:<br>success: All data sources are normal<br>partial_error: Some data sources used cache<br>stale: Used the last complete snapshot<br>error: Unable to calculate</p>
    */
    @SerializedName("ScoreStatus")
    @Expose
    private String ScoreStatus;

    /**
    * <p>Initial score<br>Default value: 100</p>
    */
    @SerializedName("InitialScore")
    @Expose
    private Long InitialScore;

    /**
    * <p>Number of categories with risks (it is advisable to process category X risks as soon as possible)</p>
    */
    @SerializedName("RiskCategoryCount")
    @Expose
    private Long RiskCategoryCount;

    /**
    * <p>Total point deduction.</p>
    */
    @SerializedName("DeductScore")
    @Expose
    private Long DeductScore;

    /**
    * <p>Calculation time<br>Parameter format: YYYY-MM-DDTHH:mm:ss+08:00</p>
    */
    @SerializedName("CalculatedAt")
    @Expose
    private String CalculatedAt;

    /**
    * <p>Dimension details, including sub-item point deductions and to-do items</p>
    */
    @SerializedName("Dimensions")
    @Expose
    private DimensionItem [] Dimensions;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get <p>Security score<br>Value range: [0, 100]</p> 
     * @return Score <p>Security score<br>Value range: [0, 100]</p>
     */
    public Long getScore() {
        return this.Score;
    }

    /**
     * Set <p>Security score<br>Value range: [0, 100]</p>
     * @param Score <p>Security score<br>Value range: [0, 100]</p>
     */
    public void setScore(Long Score) {
        this.Score = Score;
    }

    /**
     * Get <p>Security level<br>Enumeration values:<br>safe: safe (90-100 points)<br>good: good (70-89 points)<br>medium: general (40-69 points)<br>danger: dangerous (0-39 points)</p> 
     * @return Level <p>Security level<br>Enumeration values:<br>safe: safe (90-100 points)<br>good: good (70-89 points)<br>medium: general (40-69 points)<br>danger: dangerous (0-39 points)</p>
     */
    public String getLevel() {
        return this.Level;
    }

    /**
     * Set <p>Security level<br>Enumeration values:<br>safe: safe (90-100 points)<br>good: good (70-89 points)<br>medium: general (40-69 points)<br>danger: dangerous (0-39 points)</p>
     * @param Level <p>Security level<br>Enumeration values:<br>safe: safe (90-100 points)<br>good: good (70-89 points)<br>medium: general (40-69 points)<br>danger: dangerous (0-39 points)</p>
     */
    public void setLevel(String Level) {
        this.Level = Level;
    }

    /**
     * Get <p>Score status<br>Enumeration values:<br>success: All data sources are normal<br>partial_error: Some data sources used cache<br>stale: Used the last complete snapshot<br>error: Unable to calculate</p> 
     * @return ScoreStatus <p>Score status<br>Enumeration values:<br>success: All data sources are normal<br>partial_error: Some data sources used cache<br>stale: Used the last complete snapshot<br>error: Unable to calculate</p>
     */
    public String getScoreStatus() {
        return this.ScoreStatus;
    }

    /**
     * Set <p>Score status<br>Enumeration values:<br>success: All data sources are normal<br>partial_error: Some data sources used cache<br>stale: Used the last complete snapshot<br>error: Unable to calculate</p>
     * @param ScoreStatus <p>Score status<br>Enumeration values:<br>success: All data sources are normal<br>partial_error: Some data sources used cache<br>stale: Used the last complete snapshot<br>error: Unable to calculate</p>
     */
    public void setScoreStatus(String ScoreStatus) {
        this.ScoreStatus = ScoreStatus;
    }

    /**
     * Get <p>Initial score<br>Default value: 100</p> 
     * @return InitialScore <p>Initial score<br>Default value: 100</p>
     */
    public Long getInitialScore() {
        return this.InitialScore;
    }

    /**
     * Set <p>Initial score<br>Default value: 100</p>
     * @param InitialScore <p>Initial score<br>Default value: 100</p>
     */
    public void setInitialScore(Long InitialScore) {
        this.InitialScore = InitialScore;
    }

    /**
     * Get <p>Number of categories with risks (it is advisable to process category X risks as soon as possible)</p> 
     * @return RiskCategoryCount <p>Number of categories with risks (it is advisable to process category X risks as soon as possible)</p>
     */
    public Long getRiskCategoryCount() {
        return this.RiskCategoryCount;
    }

    /**
     * Set <p>Number of categories with risks (it is advisable to process category X risks as soon as possible)</p>
     * @param RiskCategoryCount <p>Number of categories with risks (it is advisable to process category X risks as soon as possible)</p>
     */
    public void setRiskCategoryCount(Long RiskCategoryCount) {
        this.RiskCategoryCount = RiskCategoryCount;
    }

    /**
     * Get <p>Total point deduction.</p> 
     * @return DeductScore <p>Total point deduction.</p>
     */
    public Long getDeductScore() {
        return this.DeductScore;
    }

    /**
     * Set <p>Total point deduction.</p>
     * @param DeductScore <p>Total point deduction.</p>
     */
    public void setDeductScore(Long DeductScore) {
        this.DeductScore = DeductScore;
    }

    /**
     * Get <p>Calculation time<br>Parameter format: YYYY-MM-DDTHH:mm:ss+08:00</p> 
     * @return CalculatedAt <p>Calculation time<br>Parameter format: YYYY-MM-DDTHH:mm:ss+08:00</p>
     */
    public String getCalculatedAt() {
        return this.CalculatedAt;
    }

    /**
     * Set <p>Calculation time<br>Parameter format: YYYY-MM-DDTHH:mm:ss+08:00</p>
     * @param CalculatedAt <p>Calculation time<br>Parameter format: YYYY-MM-DDTHH:mm:ss+08:00</p>
     */
    public void setCalculatedAt(String CalculatedAt) {
        this.CalculatedAt = CalculatedAt;
    }

    /**
     * Get <p>Dimension details, including sub-item point deductions and to-do items</p> 
     * @return Dimensions <p>Dimension details, including sub-item point deductions and to-do items</p>
     */
    public DimensionItem [] getDimensions() {
        return this.Dimensions;
    }

    /**
     * Set <p>Dimension details, including sub-item point deductions and to-do items</p>
     * @param Dimensions <p>Dimension details, including sub-item point deductions and to-do items</p>
     */
    public void setDimensions(DimensionItem [] Dimensions) {
        this.Dimensions = Dimensions;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeSecurityScoreOverviewResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeSecurityScoreOverviewResponse(DescribeSecurityScoreOverviewResponse source) {
        if (source.Score != null) {
            this.Score = new Long(source.Score);
        }
        if (source.Level != null) {
            this.Level = new String(source.Level);
        }
        if (source.ScoreStatus != null) {
            this.ScoreStatus = new String(source.ScoreStatus);
        }
        if (source.InitialScore != null) {
            this.InitialScore = new Long(source.InitialScore);
        }
        if (source.RiskCategoryCount != null) {
            this.RiskCategoryCount = new Long(source.RiskCategoryCount);
        }
        if (source.DeductScore != null) {
            this.DeductScore = new Long(source.DeductScore);
        }
        if (source.CalculatedAt != null) {
            this.CalculatedAt = new String(source.CalculatedAt);
        }
        if (source.Dimensions != null) {
            this.Dimensions = new DimensionItem[source.Dimensions.length];
            for (int i = 0; i < source.Dimensions.length; i++) {
                this.Dimensions[i] = new DimensionItem(source.Dimensions[i]);
            }
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "Score", this.Score);
        this.setParamSimple(map, prefix + "Level", this.Level);
        this.setParamSimple(map, prefix + "ScoreStatus", this.ScoreStatus);
        this.setParamSimple(map, prefix + "InitialScore", this.InitialScore);
        this.setParamSimple(map, prefix + "RiskCategoryCount", this.RiskCategoryCount);
        this.setParamSimple(map, prefix + "DeductScore", this.DeductScore);
        this.setParamSimple(map, prefix + "CalculatedAt", this.CalculatedAt);
        this.setParamArrayObj(map, prefix + "Dimensions.", this.Dimensions);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

