/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.csip.v20221121.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeLicenseStatusResponse extends AbstractModel {

    /**
    * <p>Authorization status list (flagship edition → pro edition → RASP)</p>
    */
    @SerializedName("List")
    @Expose
    private LicenseStatusItem [] List;

    /**
    * <p>Auto-purchase switch. 0: off; 1: on</p>
    */
    @SerializedName("AutoRepurchaseSwitch")
    @Expose
    private Long AutoRepurchaseSwitch;

    /**
    * <p>Merged unconsumed unbinding count = (Flagship Edition total + Pro Edition total) × 2 - Unbound count in the current month</p>
    */
    @SerializedName("UnbindCountLeft")
    @Expose
    private Long UnbindCountLeft;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get <p>Authorization status list (flagship edition → pro edition → RASP)</p> 
     * @return List <p>Authorization status list (flagship edition → pro edition → RASP)</p>
     */
    public LicenseStatusItem [] getList() {
        return this.List;
    }

    /**
     * Set <p>Authorization status list (flagship edition → pro edition → RASP)</p>
     * @param List <p>Authorization status list (flagship edition → pro edition → RASP)</p>
     */
    public void setList(LicenseStatusItem [] List) {
        this.List = List;
    }

    /**
     * Get <p>Auto-purchase switch. 0: off; 1: on</p> 
     * @return AutoRepurchaseSwitch <p>Auto-purchase switch. 0: off; 1: on</p>
     */
    public Long getAutoRepurchaseSwitch() {
        return this.AutoRepurchaseSwitch;
    }

    /**
     * Set <p>Auto-purchase switch. 0: off; 1: on</p>
     * @param AutoRepurchaseSwitch <p>Auto-purchase switch. 0: off; 1: on</p>
     */
    public void setAutoRepurchaseSwitch(Long AutoRepurchaseSwitch) {
        this.AutoRepurchaseSwitch = AutoRepurchaseSwitch;
    }

    /**
     * Get <p>Merged unconsumed unbinding count = (Flagship Edition total + Pro Edition total) × 2 - Unbound count in the current month</p> 
     * @return UnbindCountLeft <p>Merged unconsumed unbinding count = (Flagship Edition total + Pro Edition total) × 2 - Unbound count in the current month</p>
     */
    public Long getUnbindCountLeft() {
        return this.UnbindCountLeft;
    }

    /**
     * Set <p>Merged unconsumed unbinding count = (Flagship Edition total + Pro Edition total) × 2 - Unbound count in the current month</p>
     * @param UnbindCountLeft <p>Merged unconsumed unbinding count = (Flagship Edition total + Pro Edition total) × 2 - Unbound count in the current month</p>
     */
    public void setUnbindCountLeft(Long UnbindCountLeft) {
        this.UnbindCountLeft = UnbindCountLeft;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeLicenseStatusResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeLicenseStatusResponse(DescribeLicenseStatusResponse source) {
        if (source.List != null) {
            this.List = new LicenseStatusItem[source.List.length];
            for (int i = 0; i < source.List.length; i++) {
                this.List[i] = new LicenseStatusItem(source.List[i]);
            }
        }
        if (source.AutoRepurchaseSwitch != null) {
            this.AutoRepurchaseSwitch = new Long(source.AutoRepurchaseSwitch);
        }
        if (source.UnbindCountLeft != null) {
            this.UnbindCountLeft = new Long(source.UnbindCountLeft);
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamArrayObj(map, prefix + "List.", this.List);
        this.setParamSimple(map, prefix + "AutoRepurchaseSwitch", this.AutoRepurchaseSwitch);
        this.setParamSimple(map, prefix + "UnbindCountLeft", this.UnbindCountLeft);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

