/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.csip.v20221121.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeBaselineCalculatingStatisticsPolicyIDListResponse extends AbstractModel {

    /**
    * <p>List of parent category IDs for the system in the current statistical calculation.</p>
    */
    @SerializedName("SystemCategoryIDList")
    @Expose
    private Long [] SystemCategoryIDList;

    /**
    * <p>List of custom policy IDs currently in statistical calculation.</p>
    */
    @SerializedName("SelfDefinedPolicyIDList")
    @Expose
    private Long [] SelfDefinedPolicyIDList;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get <p>List of parent category IDs for the system in the current statistical calculation.</p> 
     * @return SystemCategoryIDList <p>List of parent category IDs for the system in the current statistical calculation.</p>
     */
    public Long [] getSystemCategoryIDList() {
        return this.SystemCategoryIDList;
    }

    /**
     * Set <p>List of parent category IDs for the system in the current statistical calculation.</p>
     * @param SystemCategoryIDList <p>List of parent category IDs for the system in the current statistical calculation.</p>
     */
    public void setSystemCategoryIDList(Long [] SystemCategoryIDList) {
        this.SystemCategoryIDList = SystemCategoryIDList;
    }

    /**
     * Get <p>List of custom policy IDs currently in statistical calculation.</p> 
     * @return SelfDefinedPolicyIDList <p>List of custom policy IDs currently in statistical calculation.</p>
     */
    public Long [] getSelfDefinedPolicyIDList() {
        return this.SelfDefinedPolicyIDList;
    }

    /**
     * Set <p>List of custom policy IDs currently in statistical calculation.</p>
     * @param SelfDefinedPolicyIDList <p>List of custom policy IDs currently in statistical calculation.</p>
     */
    public void setSelfDefinedPolicyIDList(Long [] SelfDefinedPolicyIDList) {
        this.SelfDefinedPolicyIDList = SelfDefinedPolicyIDList;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeBaselineCalculatingStatisticsPolicyIDListResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeBaselineCalculatingStatisticsPolicyIDListResponse(DescribeBaselineCalculatingStatisticsPolicyIDListResponse source) {
        if (source.SystemCategoryIDList != null) {
            this.SystemCategoryIDList = new Long[source.SystemCategoryIDList.length];
            for (int i = 0; i < source.SystemCategoryIDList.length; i++) {
                this.SystemCategoryIDList[i] = new Long(source.SystemCategoryIDList[i]);
            }
        }
        if (source.SelfDefinedPolicyIDList != null) {
            this.SelfDefinedPolicyIDList = new Long[source.SelfDefinedPolicyIDList.length];
            for (int i = 0; i < source.SelfDefinedPolicyIDList.length; i++) {
                this.SelfDefinedPolicyIDList[i] = new Long(source.SelfDefinedPolicyIDList[i]);
            }
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamArraySimple(map, prefix + "SystemCategoryIDList.", this.SystemCategoryIDList);
        this.setParamArraySimple(map, prefix + "SelfDefinedPolicyIDList.", this.SelfDefinedPolicyIDList);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

