/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.csip.v20221121.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeSecurityRiskTrendResponse extends AbstractModel {

    /**
    * <p>Trend data grouped by dimension</p>
    */
    @SerializedName("TrendData")
    @Expose
    private DimensionTrendData [] TrendData;

    /**
    * <p>Last day risk abstract (alerts + applicable vulnerability items)</p>
    */
    @SerializedName("RiskItems")
    @Expose
    private RiskTrendItem [] RiskItems;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get <p>Trend data grouped by dimension</p> 
     * @return TrendData <p>Trend data grouped by dimension</p>
     */
    public DimensionTrendData [] getTrendData() {
        return this.TrendData;
    }

    /**
     * Set <p>Trend data grouped by dimension</p>
     * @param TrendData <p>Trend data grouped by dimension</p>
     */
    public void setTrendData(DimensionTrendData [] TrendData) {
        this.TrendData = TrendData;
    }

    /**
     * Get <p>Last day risk abstract (alerts + applicable vulnerability items)</p> 
     * @return RiskItems <p>Last day risk abstract (alerts + applicable vulnerability items)</p>
     */
    public RiskTrendItem [] getRiskItems() {
        return this.RiskItems;
    }

    /**
     * Set <p>Last day risk abstract (alerts + applicable vulnerability items)</p>
     * @param RiskItems <p>Last day risk abstract (alerts + applicable vulnerability items)</p>
     */
    public void setRiskItems(RiskTrendItem [] RiskItems) {
        this.RiskItems = RiskItems;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeSecurityRiskTrendResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeSecurityRiskTrendResponse(DescribeSecurityRiskTrendResponse source) {
        if (source.TrendData != null) {
            this.TrendData = new DimensionTrendData[source.TrendData.length];
            for (int i = 0; i < source.TrendData.length; i++) {
                this.TrendData[i] = new DimensionTrendData(source.TrendData[i]);
            }
        }
        if (source.RiskItems != null) {
            this.RiskItems = new RiskTrendItem[source.RiskItems.length];
            for (int i = 0; i < source.RiskItems.length; i++) {
                this.RiskItems[i] = new RiskTrendItem(source.RiskItems[i]);
            }
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamArrayObj(map, prefix + "TrendData.", this.TrendData);
        this.setParamArrayObj(map, prefix + "RiskItems.", this.RiskItems);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

