/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.csip.v20221121.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeAKAnalysisDetailResponse extends AbstractModel {

    /**
    * Alarm AI analysis status -1 Analysis failed 0 Not analyzed 1 Under analysis 2 Analysis successful, real alarm 3 Analysis successful, suspicious alarm
    */
    @SerializedName("AIStatus")
    @Expose
    private Long AIStatus;

    /**
    * AI Analysis Task ID
    */
    @SerializedName("AITaskID")
    @Expose
    private String AITaskID;

    /**
    * Alarm AI analysis result, base64 format, avoid data interception
    */
    @SerializedName("AIResult")
    @Expose
    private String AIResult;

    /**
    * Feedback and Suggestions
    */
    @SerializedName("Feedback")
    @Expose
    private String Feedback;

    /**
    * Feedback status  0 means no feedback, 1 means recognized, 2 means not recognized
    */
    @SerializedName("FeedbackResult")
    @Expose
    private Long FeedbackResult;

    /**
    * Reason for failure
    */
    @SerializedName("FailedReason")
    @Expose
    private String FailedReason;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Alarm AI analysis status -1 Analysis failed 0 Not analyzed 1 Under analysis 2 Analysis successful, real alarm 3 Analysis successful, suspicious alarm 
     * @return AIStatus Alarm AI analysis status -1 Analysis failed 0 Not analyzed 1 Under analysis 2 Analysis successful, real alarm 3 Analysis successful, suspicious alarm
     */
    public Long getAIStatus() {
        return this.AIStatus;
    }

    /**
     * Set Alarm AI analysis status -1 Analysis failed 0 Not analyzed 1 Under analysis 2 Analysis successful, real alarm 3 Analysis successful, suspicious alarm
     * @param AIStatus Alarm AI analysis status -1 Analysis failed 0 Not analyzed 1 Under analysis 2 Analysis successful, real alarm 3 Analysis successful, suspicious alarm
     */
    public void setAIStatus(Long AIStatus) {
        this.AIStatus = AIStatus;
    }

    /**
     * Get AI Analysis Task ID 
     * @return AITaskID AI Analysis Task ID
     */
    public String getAITaskID() {
        return this.AITaskID;
    }

    /**
     * Set AI Analysis Task ID
     * @param AITaskID AI Analysis Task ID
     */
    public void setAITaskID(String AITaskID) {
        this.AITaskID = AITaskID;
    }

    /**
     * Get Alarm AI analysis result, base64 format, avoid data interception 
     * @return AIResult Alarm AI analysis result, base64 format, avoid data interception
     */
    public String getAIResult() {
        return this.AIResult;
    }

    /**
     * Set Alarm AI analysis result, base64 format, avoid data interception
     * @param AIResult Alarm AI analysis result, base64 format, avoid data interception
     */
    public void setAIResult(String AIResult) {
        this.AIResult = AIResult;
    }

    /**
     * Get Feedback and Suggestions 
     * @return Feedback Feedback and Suggestions
     */
    public String getFeedback() {
        return this.Feedback;
    }

    /**
     * Set Feedback and Suggestions
     * @param Feedback Feedback and Suggestions
     */
    public void setFeedback(String Feedback) {
        this.Feedback = Feedback;
    }

    /**
     * Get Feedback status  0 means no feedback, 1 means recognized, 2 means not recognized 
     * @return FeedbackResult Feedback status  0 means no feedback, 1 means recognized, 2 means not recognized
     */
    public Long getFeedbackResult() {
        return this.FeedbackResult;
    }

    /**
     * Set Feedback status  0 means no feedback, 1 means recognized, 2 means not recognized
     * @param FeedbackResult Feedback status  0 means no feedback, 1 means recognized, 2 means not recognized
     */
    public void setFeedbackResult(Long FeedbackResult) {
        this.FeedbackResult = FeedbackResult;
    }

    /**
     * Get Reason for failure 
     * @return FailedReason Reason for failure
     */
    public String getFailedReason() {
        return this.FailedReason;
    }

    /**
     * Set Reason for failure
     * @param FailedReason Reason for failure
     */
    public void setFailedReason(String FailedReason) {
        this.FailedReason = FailedReason;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeAKAnalysisDetailResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeAKAnalysisDetailResponse(DescribeAKAnalysisDetailResponse source) {
        if (source.AIStatus != null) {
            this.AIStatus = new Long(source.AIStatus);
        }
        if (source.AITaskID != null) {
            this.AITaskID = new String(source.AITaskID);
        }
        if (source.AIResult != null) {
            this.AIResult = new String(source.AIResult);
        }
        if (source.Feedback != null) {
            this.Feedback = new String(source.Feedback);
        }
        if (source.FeedbackResult != null) {
            this.FeedbackResult = new Long(source.FeedbackResult);
        }
        if (source.FailedReason != null) {
            this.FailedReason = new String(source.FailedReason);
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "AIStatus", this.AIStatus);
        this.setParamSimple(map, prefix + "AITaskID", this.AITaskID);
        this.setParamSimple(map, prefix + "AIResult", this.AIResult);
        this.setParamSimple(map, prefix + "Feedback", this.Feedback);
        this.setParamSimple(map, prefix + "FeedbackResult", this.FeedbackResult);
        this.setParamSimple(map, prefix + "FailedReason", this.FailedReason);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

