/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.csip.v20221121.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeCheckViewRisksResponse extends AbstractModel {

    /**
    * <p>Number of risks from check perspective</p>
    */
    @SerializedName("TotalCount")
    @Expose
    private Long TotalCount;

    /**
    * <p>Risk list in check perspective</p>
    */
    @SerializedName("CheckViewRiskList")
    @Expose
    private CheckViewRiskItem [] CheckViewRiskList;

    /**
    * <p>Tag list of cspm standard from a checking perspective</p>
    */
    @SerializedName("StandardNameList")
    @Expose
    private StandardItem [] StandardNameList;

    /**
    * <p>Asset type collection</p>
    */
    @SerializedName("AssetTypeList")
    @Expose
    private AttributeOptionSet [] AssetTypeList;

    /**
    * <p>Cloud vendor type collection</p>
    */
    @SerializedName("ProviderList")
    @Expose
    private AttributeOptionSet [] ProviderList;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get <p>Number of risks from check perspective</p> 
     * @return TotalCount <p>Number of risks from check perspective</p>
     */
    public Long getTotalCount() {
        return this.TotalCount;
    }

    /**
     * Set <p>Number of risks from check perspective</p>
     * @param TotalCount <p>Number of risks from check perspective</p>
     */
    public void setTotalCount(Long TotalCount) {
        this.TotalCount = TotalCount;
    }

    /**
     * Get <p>Risk list in check perspective</p> 
     * @return CheckViewRiskList <p>Risk list in check perspective</p>
     */
    public CheckViewRiskItem [] getCheckViewRiskList() {
        return this.CheckViewRiskList;
    }

    /**
     * Set <p>Risk list in check perspective</p>
     * @param CheckViewRiskList <p>Risk list in check perspective</p>
     */
    public void setCheckViewRiskList(CheckViewRiskItem [] CheckViewRiskList) {
        this.CheckViewRiskList = CheckViewRiskList;
    }

    /**
     * Get <p>Tag list of cspm standard from a checking perspective</p> 
     * @return StandardNameList <p>Tag list of cspm standard from a checking perspective</p>
     */
    public StandardItem [] getStandardNameList() {
        return this.StandardNameList;
    }

    /**
     * Set <p>Tag list of cspm standard from a checking perspective</p>
     * @param StandardNameList <p>Tag list of cspm standard from a checking perspective</p>
     */
    public void setStandardNameList(StandardItem [] StandardNameList) {
        this.StandardNameList = StandardNameList;
    }

    /**
     * Get <p>Asset type collection</p> 
     * @return AssetTypeList <p>Asset type collection</p>
     */
    public AttributeOptionSet [] getAssetTypeList() {
        return this.AssetTypeList;
    }

    /**
     * Set <p>Asset type collection</p>
     * @param AssetTypeList <p>Asset type collection</p>
     */
    public void setAssetTypeList(AttributeOptionSet [] AssetTypeList) {
        this.AssetTypeList = AssetTypeList;
    }

    /**
     * Get <p>Cloud vendor type collection</p> 
     * @return ProviderList <p>Cloud vendor type collection</p>
     */
    public AttributeOptionSet [] getProviderList() {
        return this.ProviderList;
    }

    /**
     * Set <p>Cloud vendor type collection</p>
     * @param ProviderList <p>Cloud vendor type collection</p>
     */
    public void setProviderList(AttributeOptionSet [] ProviderList) {
        this.ProviderList = ProviderList;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeCheckViewRisksResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeCheckViewRisksResponse(DescribeCheckViewRisksResponse source) {
        if (source.TotalCount != null) {
            this.TotalCount = new Long(source.TotalCount);
        }
        if (source.CheckViewRiskList != null) {
            this.CheckViewRiskList = new CheckViewRiskItem[source.CheckViewRiskList.length];
            for (int i = 0; i < source.CheckViewRiskList.length; i++) {
                this.CheckViewRiskList[i] = new CheckViewRiskItem(source.CheckViewRiskList[i]);
            }
        }
        if (source.StandardNameList != null) {
            this.StandardNameList = new StandardItem[source.StandardNameList.length];
            for (int i = 0; i < source.StandardNameList.length; i++) {
                this.StandardNameList[i] = new StandardItem(source.StandardNameList[i]);
            }
        }
        if (source.AssetTypeList != null) {
            this.AssetTypeList = new AttributeOptionSet[source.AssetTypeList.length];
            for (int i = 0; i < source.AssetTypeList.length; i++) {
                this.AssetTypeList[i] = new AttributeOptionSet(source.AssetTypeList[i]);
            }
        }
        if (source.ProviderList != null) {
            this.ProviderList = new AttributeOptionSet[source.ProviderList.length];
            for (int i = 0; i < source.ProviderList.length; i++) {
                this.ProviderList[i] = new AttributeOptionSet(source.ProviderList[i]);
            }
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "TotalCount", this.TotalCount);
        this.setParamArrayObj(map, prefix + "CheckViewRiskList.", this.CheckViewRiskList);
        this.setParamArrayObj(map, prefix + "StandardNameList.", this.StandardNameList);
        this.setParamArrayObj(map, prefix + "AssetTypeList.", this.AssetTypeList);
        this.setParamArrayObj(map, prefix + "ProviderList.", this.ProviderList);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

