/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.csip.v20221121.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeDspmBackupLogListResponse extends AbstractModel {

    /**
    * <p>How many are there in total</p>
    */
    @SerializedName("TotalCount")
    @Expose
    private Long TotalCount;

    /**
    * <p>Backup log list.</p>
    */
    @SerializedName("List")
    @Expose
    private BackupLog [] List;

    /**
    * <p>Whether recovery tasks currently exist</p>
    */
    @SerializedName("HasRestoringTask")
    @Expose
    private Boolean HasRestoringTask;

    /**
    * <p>Maximum recovery space</p>
    */
    @SerializedName("MaxRestoreSizeInGB")
    @Expose
    private Long MaxRestoreSizeInGB;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get <p>How many are there in total</p> 
     * @return TotalCount <p>How many are there in total</p>
     */
    public Long getTotalCount() {
        return this.TotalCount;
    }

    /**
     * Set <p>How many are there in total</p>
     * @param TotalCount <p>How many are there in total</p>
     */
    public void setTotalCount(Long TotalCount) {
        this.TotalCount = TotalCount;
    }

    /**
     * Get <p>Backup log list.</p> 
     * @return List <p>Backup log list.</p>
     */
    public BackupLog [] getList() {
        return this.List;
    }

    /**
     * Set <p>Backup log list.</p>
     * @param List <p>Backup log list.</p>
     */
    public void setList(BackupLog [] List) {
        this.List = List;
    }

    /**
     * Get <p>Whether recovery tasks currently exist</p> 
     * @return HasRestoringTask <p>Whether recovery tasks currently exist</p>
     */
    public Boolean getHasRestoringTask() {
        return this.HasRestoringTask;
    }

    /**
     * Set <p>Whether recovery tasks currently exist</p>
     * @param HasRestoringTask <p>Whether recovery tasks currently exist</p>
     */
    public void setHasRestoringTask(Boolean HasRestoringTask) {
        this.HasRestoringTask = HasRestoringTask;
    }

    /**
     * Get <p>Maximum recovery space</p> 
     * @return MaxRestoreSizeInGB <p>Maximum recovery space</p>
     */
    public Long getMaxRestoreSizeInGB() {
        return this.MaxRestoreSizeInGB;
    }

    /**
     * Set <p>Maximum recovery space</p>
     * @param MaxRestoreSizeInGB <p>Maximum recovery space</p>
     */
    public void setMaxRestoreSizeInGB(Long MaxRestoreSizeInGB) {
        this.MaxRestoreSizeInGB = MaxRestoreSizeInGB;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeDspmBackupLogListResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeDspmBackupLogListResponse(DescribeDspmBackupLogListResponse source) {
        if (source.TotalCount != null) {
            this.TotalCount = new Long(source.TotalCount);
        }
        if (source.List != null) {
            this.List = new BackupLog[source.List.length];
            for (int i = 0; i < source.List.length; i++) {
                this.List[i] = new BackupLog(source.List[i]);
            }
        }
        if (source.HasRestoringTask != null) {
            this.HasRestoringTask = new Boolean(source.HasRestoringTask);
        }
        if (source.MaxRestoreSizeInGB != null) {
            this.MaxRestoreSizeInGB = new Long(source.MaxRestoreSizeInGB);
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "TotalCount", this.TotalCount);
        this.setParamArrayObj(map, prefix + "List.", this.List);
        this.setParamSimple(map, prefix + "HasRestoringTask", this.HasRestoringTask);
        this.setParamSimple(map, prefix + "MaxRestoreSizeInGB", this.MaxRestoreSizeInGB);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

