/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.csip.v20221121.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeCLSLogListV3Response extends AbstractModel {

    /**
    * <p>context</p>
    */
    @SerializedName("Context")
    @Expose
    private String Context;

    /**
    * <p>listover</p>
    */
    @SerializedName("ListOver")
    @Expose
    private Boolean ListOver;

    /**
    * <p>Whether to adopt analytics</p>
    */
    @SerializedName("Analysis")
    @Expose
    private Boolean Analysis;

    /**
    * <p>Result.</p>
    */
    @SerializedName("Results")
    @Expose
    private LogSearchResult [] Results;

    /**
    * <p>Column name.</p>
    */
    @SerializedName("ColNames")
    @Expose
    private String [] ColNames;

    /**
    * <p>Analysis result</p>
    */
    @SerializedName("AnalysisResults")
    @Expose
    private LogItems [] AnalysisResults;

    /**
    * <p>Analysis records</p>
    */
    @SerializedName("AnalysisRecords")
    @Expose
    private String [] AnalysisRecords;

    /**
    * <p>Column name.</p>
    */
    @SerializedName("Columns")
    @Expose
    private LogColumn [] Columns;

    /**
    * <p>Sampling</p>
    */
    @SerializedName("SamplingRate")
    @Expose
    private Float SamplingRate;

    /**
    * <p>Topic information</p>
    */
    @SerializedName("Topics")
    @Expose
    private LogSearchTopics Topics;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get <p>context</p> 
     * @return Context <p>context</p>
     */
    public String getContext() {
        return this.Context;
    }

    /**
     * Set <p>context</p>
     * @param Context <p>context</p>
     */
    public void setContext(String Context) {
        this.Context = Context;
    }

    /**
     * Get <p>listover</p> 
     * @return ListOver <p>listover</p>
     */
    public Boolean getListOver() {
        return this.ListOver;
    }

    /**
     * Set <p>listover</p>
     * @param ListOver <p>listover</p>
     */
    public void setListOver(Boolean ListOver) {
        this.ListOver = ListOver;
    }

    /**
     * Get <p>Whether to adopt analytics</p> 
     * @return Analysis <p>Whether to adopt analytics</p>
     */
    public Boolean getAnalysis() {
        return this.Analysis;
    }

    /**
     * Set <p>Whether to adopt analytics</p>
     * @param Analysis <p>Whether to adopt analytics</p>
     */
    public void setAnalysis(Boolean Analysis) {
        this.Analysis = Analysis;
    }

    /**
     * Get <p>Result.</p> 
     * @return Results <p>Result.</p>
     */
    public LogSearchResult [] getResults() {
        return this.Results;
    }

    /**
     * Set <p>Result.</p>
     * @param Results <p>Result.</p>
     */
    public void setResults(LogSearchResult [] Results) {
        this.Results = Results;
    }

    /**
     * Get <p>Column name.</p> 
     * @return ColNames <p>Column name.</p>
     */
    public String [] getColNames() {
        return this.ColNames;
    }

    /**
     * Set <p>Column name.</p>
     * @param ColNames <p>Column name.</p>
     */
    public void setColNames(String [] ColNames) {
        this.ColNames = ColNames;
    }

    /**
     * Get <p>Analysis result</p> 
     * @return AnalysisResults <p>Analysis result</p>
     */
    public LogItems [] getAnalysisResults() {
        return this.AnalysisResults;
    }

    /**
     * Set <p>Analysis result</p>
     * @param AnalysisResults <p>Analysis result</p>
     */
    public void setAnalysisResults(LogItems [] AnalysisResults) {
        this.AnalysisResults = AnalysisResults;
    }

    /**
     * Get <p>Analysis records</p> 
     * @return AnalysisRecords <p>Analysis records</p>
     */
    public String [] getAnalysisRecords() {
        return this.AnalysisRecords;
    }

    /**
     * Set <p>Analysis records</p>
     * @param AnalysisRecords <p>Analysis records</p>
     */
    public void setAnalysisRecords(String [] AnalysisRecords) {
        this.AnalysisRecords = AnalysisRecords;
    }

    /**
     * Get <p>Column name.</p> 
     * @return Columns <p>Column name.</p>
     */
    public LogColumn [] getColumns() {
        return this.Columns;
    }

    /**
     * Set <p>Column name.</p>
     * @param Columns <p>Column name.</p>
     */
    public void setColumns(LogColumn [] Columns) {
        this.Columns = Columns;
    }

    /**
     * Get <p>Sampling</p> 
     * @return SamplingRate <p>Sampling</p>
     */
    public Float getSamplingRate() {
        return this.SamplingRate;
    }

    /**
     * Set <p>Sampling</p>
     * @param SamplingRate <p>Sampling</p>
     */
    public void setSamplingRate(Float SamplingRate) {
        this.SamplingRate = SamplingRate;
    }

    /**
     * Get <p>Topic information</p> 
     * @return Topics <p>Topic information</p>
     */
    public LogSearchTopics getTopics() {
        return this.Topics;
    }

    /**
     * Set <p>Topic information</p>
     * @param Topics <p>Topic information</p>
     */
    public void setTopics(LogSearchTopics Topics) {
        this.Topics = Topics;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeCLSLogListV3Response() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeCLSLogListV3Response(DescribeCLSLogListV3Response source) {
        if (source.Context != null) {
            this.Context = new String(source.Context);
        }
        if (source.ListOver != null) {
            this.ListOver = new Boolean(source.ListOver);
        }
        if (source.Analysis != null) {
            this.Analysis = new Boolean(source.Analysis);
        }
        if (source.Results != null) {
            this.Results = new LogSearchResult[source.Results.length];
            for (int i = 0; i < source.Results.length; i++) {
                this.Results[i] = new LogSearchResult(source.Results[i]);
            }
        }
        if (source.ColNames != null) {
            this.ColNames = new String[source.ColNames.length];
            for (int i = 0; i < source.ColNames.length; i++) {
                this.ColNames[i] = new String(source.ColNames[i]);
            }
        }
        if (source.AnalysisResults != null) {
            this.AnalysisResults = new LogItems[source.AnalysisResults.length];
            for (int i = 0; i < source.AnalysisResults.length; i++) {
                this.AnalysisResults[i] = new LogItems(source.AnalysisResults[i]);
            }
        }
        if (source.AnalysisRecords != null) {
            this.AnalysisRecords = new String[source.AnalysisRecords.length];
            for (int i = 0; i < source.AnalysisRecords.length; i++) {
                this.AnalysisRecords[i] = new String(source.AnalysisRecords[i]);
            }
        }
        if (source.Columns != null) {
            this.Columns = new LogColumn[source.Columns.length];
            for (int i = 0; i < source.Columns.length; i++) {
                this.Columns[i] = new LogColumn(source.Columns[i]);
            }
        }
        if (source.SamplingRate != null) {
            this.SamplingRate = new Float(source.SamplingRate);
        }
        if (source.Topics != null) {
            this.Topics = new LogSearchTopics(source.Topics);
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "Context", this.Context);
        this.setParamSimple(map, prefix + "ListOver", this.ListOver);
        this.setParamSimple(map, prefix + "Analysis", this.Analysis);
        this.setParamArrayObj(map, prefix + "Results.", this.Results);
        this.setParamArraySimple(map, prefix + "ColNames.", this.ColNames);
        this.setParamArrayObj(map, prefix + "AnalysisResults.", this.AnalysisResults);
        this.setParamArraySimple(map, prefix + "AnalysisRecords.", this.AnalysisRecords);
        this.setParamArrayObj(map, prefix + "Columns.", this.Columns);
        this.setParamSimple(map, prefix + "SamplingRate", this.SamplingRate);
        this.setParamObj(map, prefix + "Topics.", this.Topics);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

