/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.csip.v20221121.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeVULListResponse extends AbstractModel {

    /**
    * Total number.
    */
    @SerializedName("TotalCount")
    @Expose
    private Long TotalCount;

    /**
    * Vulnerability list
    */
    @SerializedName("Data")
    @Expose
    private VULBaseInfo [] Data;

    /**
    * Vulnerability Type List
    */
    @SerializedName("VULTypeLists")
    @Expose
    private FilterDataObject [] VULTypeLists;

    /**
    * Risk level list.
    */
    @SerializedName("RiskLevels")
    @Expose
    private FilterDataObject [] RiskLevels;

    /**
    * Tag.
    */
    @SerializedName("Tags")
    @Expose
    private FilterDataObject [] Tags;

    /**
    * Product support.
    */
    @SerializedName("ProductSupport")
    @Expose
    private FilterDataObject [] ProductSupport;

    /**
    * Product support.
    */
    @SerializedName("CheckStatus")
    @Expose
    private FilterDataObject [] CheckStatus;

    /**
    * Attack intensity enumeration.
    */
    @SerializedName("AttackHeat")
    @Expose
    private FilterDataObject [] AttackHeat;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get Total number. 
     * @return TotalCount Total number.
     */
    public Long getTotalCount() {
        return this.TotalCount;
    }

    /**
     * Set Total number.
     * @param TotalCount Total number.
     */
    public void setTotalCount(Long TotalCount) {
        this.TotalCount = TotalCount;
    }

    /**
     * Get Vulnerability list 
     * @return Data Vulnerability list
     */
    public VULBaseInfo [] getData() {
        return this.Data;
    }

    /**
     * Set Vulnerability list
     * @param Data Vulnerability list
     */
    public void setData(VULBaseInfo [] Data) {
        this.Data = Data;
    }

    /**
     * Get Vulnerability Type List 
     * @return VULTypeLists Vulnerability Type List
     */
    public FilterDataObject [] getVULTypeLists() {
        return this.VULTypeLists;
    }

    /**
     * Set Vulnerability Type List
     * @param VULTypeLists Vulnerability Type List
     */
    public void setVULTypeLists(FilterDataObject [] VULTypeLists) {
        this.VULTypeLists = VULTypeLists;
    }

    /**
     * Get Risk level list. 
     * @return RiskLevels Risk level list.
     */
    public FilterDataObject [] getRiskLevels() {
        return this.RiskLevels;
    }

    /**
     * Set Risk level list.
     * @param RiskLevels Risk level list.
     */
    public void setRiskLevels(FilterDataObject [] RiskLevels) {
        this.RiskLevels = RiskLevels;
    }

    /**
     * Get Tag. 
     * @return Tags Tag.
     */
    public FilterDataObject [] getTags() {
        return this.Tags;
    }

    /**
     * Set Tag.
     * @param Tags Tag.
     */
    public void setTags(FilterDataObject [] Tags) {
        this.Tags = Tags;
    }

    /**
     * Get Product support. 
     * @return ProductSupport Product support.
     */
    public FilterDataObject [] getProductSupport() {
        return this.ProductSupport;
    }

    /**
     * Set Product support.
     * @param ProductSupport Product support.
     */
    public void setProductSupport(FilterDataObject [] ProductSupport) {
        this.ProductSupport = ProductSupport;
    }

    /**
     * Get Product support. 
     * @return CheckStatus Product support.
     */
    public FilterDataObject [] getCheckStatus() {
        return this.CheckStatus;
    }

    /**
     * Set Product support.
     * @param CheckStatus Product support.
     */
    public void setCheckStatus(FilterDataObject [] CheckStatus) {
        this.CheckStatus = CheckStatus;
    }

    /**
     * Get Attack intensity enumeration. 
     * @return AttackHeat Attack intensity enumeration.
     */
    public FilterDataObject [] getAttackHeat() {
        return this.AttackHeat;
    }

    /**
     * Set Attack intensity enumeration.
     * @param AttackHeat Attack intensity enumeration.
     */
    public void setAttackHeat(FilterDataObject [] AttackHeat) {
        this.AttackHeat = AttackHeat;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeVULListResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeVULListResponse(DescribeVULListResponse source) {
        if (source.TotalCount != null) {
            this.TotalCount = new Long(source.TotalCount);
        }
        if (source.Data != null) {
            this.Data = new VULBaseInfo[source.Data.length];
            for (int i = 0; i < source.Data.length; i++) {
                this.Data[i] = new VULBaseInfo(source.Data[i]);
            }
        }
        if (source.VULTypeLists != null) {
            this.VULTypeLists = new FilterDataObject[source.VULTypeLists.length];
            for (int i = 0; i < source.VULTypeLists.length; i++) {
                this.VULTypeLists[i] = new FilterDataObject(source.VULTypeLists[i]);
            }
        }
        if (source.RiskLevels != null) {
            this.RiskLevels = new FilterDataObject[source.RiskLevels.length];
            for (int i = 0; i < source.RiskLevels.length; i++) {
                this.RiskLevels[i] = new FilterDataObject(source.RiskLevels[i]);
            }
        }
        if (source.Tags != null) {
            this.Tags = new FilterDataObject[source.Tags.length];
            for (int i = 0; i < source.Tags.length; i++) {
                this.Tags[i] = new FilterDataObject(source.Tags[i]);
            }
        }
        if (source.ProductSupport != null) {
            this.ProductSupport = new FilterDataObject[source.ProductSupport.length];
            for (int i = 0; i < source.ProductSupport.length; i++) {
                this.ProductSupport[i] = new FilterDataObject(source.ProductSupport[i]);
            }
        }
        if (source.CheckStatus != null) {
            this.CheckStatus = new FilterDataObject[source.CheckStatus.length];
            for (int i = 0; i < source.CheckStatus.length; i++) {
                this.CheckStatus[i] = new FilterDataObject(source.CheckStatus[i]);
            }
        }
        if (source.AttackHeat != null) {
            this.AttackHeat = new FilterDataObject[source.AttackHeat.length];
            for (int i = 0; i < source.AttackHeat.length; i++) {
                this.AttackHeat[i] = new FilterDataObject(source.AttackHeat[i]);
            }
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "TotalCount", this.TotalCount);
        this.setParamArrayObj(map, prefix + "Data.", this.Data);
        this.setParamArrayObj(map, prefix + "VULTypeLists.", this.VULTypeLists);
        this.setParamArrayObj(map, prefix + "RiskLevels.", this.RiskLevels);
        this.setParamArrayObj(map, prefix + "Tags.", this.Tags);
        this.setParamArrayObj(map, prefix + "ProductSupport.", this.ProductSupport);
        this.setParamArrayObj(map, prefix + "CheckStatus.", this.CheckStatus);
        this.setParamArrayObj(map, prefix + "AttackHeat.", this.AttackHeat);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

