/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.csip.v20221121.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeExposureAutoTagAttributeResponse extends AbstractModel {

    /**
    * <p>Asset type</p>
    */
    @SerializedName("AssetTypeList")
    @Expose
    private ExposeAssetTypeItem [] AssetTypeList;

    /**
    * <p>Tag set</p>
    */
    @SerializedName("TagList")
    @Expose
    private AttributeOptionSet [] TagList;

    /**
    * <p>Open status set</p>
    */
    @SerializedName("OpenStatusList")
    @Expose
    private AttributeOptionSet [] OpenStatusList;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get <p>Asset type</p> 
     * @return AssetTypeList <p>Asset type</p>
     */
    public ExposeAssetTypeItem [] getAssetTypeList() {
        return this.AssetTypeList;
    }

    /**
     * Set <p>Asset type</p>
     * @param AssetTypeList <p>Asset type</p>
     */
    public void setAssetTypeList(ExposeAssetTypeItem [] AssetTypeList) {
        this.AssetTypeList = AssetTypeList;
    }

    /**
     * Get <p>Tag set</p> 
     * @return TagList <p>Tag set</p>
     */
    public AttributeOptionSet [] getTagList() {
        return this.TagList;
    }

    /**
     * Set <p>Tag set</p>
     * @param TagList <p>Tag set</p>
     */
    public void setTagList(AttributeOptionSet [] TagList) {
        this.TagList = TagList;
    }

    /**
     * Get <p>Open status set</p> 
     * @return OpenStatusList <p>Open status set</p>
     */
    public AttributeOptionSet [] getOpenStatusList() {
        return this.OpenStatusList;
    }

    /**
     * Set <p>Open status set</p>
     * @param OpenStatusList <p>Open status set</p>
     */
    public void setOpenStatusList(AttributeOptionSet [] OpenStatusList) {
        this.OpenStatusList = OpenStatusList;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeExposureAutoTagAttributeResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeExposureAutoTagAttributeResponse(DescribeExposureAutoTagAttributeResponse source) {
        if (source.AssetTypeList != null) {
            this.AssetTypeList = new ExposeAssetTypeItem[source.AssetTypeList.length];
            for (int i = 0; i < source.AssetTypeList.length; i++) {
                this.AssetTypeList[i] = new ExposeAssetTypeItem(source.AssetTypeList[i]);
            }
        }
        if (source.TagList != null) {
            this.TagList = new AttributeOptionSet[source.TagList.length];
            for (int i = 0; i < source.TagList.length; i++) {
                this.TagList[i] = new AttributeOptionSet(source.TagList[i]);
            }
        }
        if (source.OpenStatusList != null) {
            this.OpenStatusList = new AttributeOptionSet[source.OpenStatusList.length];
            for (int i = 0; i < source.OpenStatusList.length; i++) {
                this.OpenStatusList[i] = new AttributeOptionSet(source.OpenStatusList[i]);
            }
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamArrayObj(map, prefix + "AssetTypeList.", this.AssetTypeList);
        this.setParamArrayObj(map, prefix + "TagList.", this.TagList);
        this.setParamArrayObj(map, prefix + "OpenStatusList.", this.OpenStatusList);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

