/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.csip.v20221121.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeClusterAssetsResponse extends AbstractModel {

    /**
    * List
    */
    @SerializedName("Data")
    @Expose
    private AssetCluster [] Data;

    /**
    * Total number.
    */
    @SerializedName("TotalCount")
    @Expose
    private Long TotalCount;

    /**
    * Cluster Type Enumeration
    */
    @SerializedName("ClusterTypeList")
    @Expose
    private FilterDataObject [] ClusterTypeList;

    /**
    * Cluster Status Enumeration
    */
    @SerializedName("ClusterStatusList")
    @Expose
    private FilterDataObject [] ClusterStatusList;

    /**
    * Component Status Enumeration
    */
    @SerializedName("ComponentStatusList")
    @Expose
    private FilterDataObject [] ComponentStatusList;

    /**
    * VPC Enumeration
    */
    @SerializedName("VpcList")
    @Expose
    private FilterDataObject [] VpcList;

    /**
    * Region Enumeration
    */
    @SerializedName("RegionList")
    @Expose
    private FilterDataObject [] RegionList;

    /**
    * Tenant Enumeration
    */
    @SerializedName("AppIdList")
    @Expose
    private FilterDataObject [] AppIdList;

    /**
    * Cluster protection status enumeration.
    */
    @SerializedName("ProtectStatusList")
    @Expose
    private FilterDataObject [] ProtectStatusList;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get List 
     * @return Data List
     */
    public AssetCluster [] getData() {
        return this.Data;
    }

    /**
     * Set List
     * @param Data List
     */
    public void setData(AssetCluster [] Data) {
        this.Data = Data;
    }

    /**
     * Get Total number. 
     * @return TotalCount Total number.
     */
    public Long getTotalCount() {
        return this.TotalCount;
    }

    /**
     * Set Total number.
     * @param TotalCount Total number.
     */
    public void setTotalCount(Long TotalCount) {
        this.TotalCount = TotalCount;
    }

    /**
     * Get Cluster Type Enumeration 
     * @return ClusterTypeList Cluster Type Enumeration
     */
    public FilterDataObject [] getClusterTypeList() {
        return this.ClusterTypeList;
    }

    /**
     * Set Cluster Type Enumeration
     * @param ClusterTypeList Cluster Type Enumeration
     */
    public void setClusterTypeList(FilterDataObject [] ClusterTypeList) {
        this.ClusterTypeList = ClusterTypeList;
    }

    /**
     * Get Cluster Status Enumeration 
     * @return ClusterStatusList Cluster Status Enumeration
     */
    public FilterDataObject [] getClusterStatusList() {
        return this.ClusterStatusList;
    }

    /**
     * Set Cluster Status Enumeration
     * @param ClusterStatusList Cluster Status Enumeration
     */
    public void setClusterStatusList(FilterDataObject [] ClusterStatusList) {
        this.ClusterStatusList = ClusterStatusList;
    }

    /**
     * Get Component Status Enumeration 
     * @return ComponentStatusList Component Status Enumeration
     */
    public FilterDataObject [] getComponentStatusList() {
        return this.ComponentStatusList;
    }

    /**
     * Set Component Status Enumeration
     * @param ComponentStatusList Component Status Enumeration
     */
    public void setComponentStatusList(FilterDataObject [] ComponentStatusList) {
        this.ComponentStatusList = ComponentStatusList;
    }

    /**
     * Get VPC Enumeration 
     * @return VpcList VPC Enumeration
     */
    public FilterDataObject [] getVpcList() {
        return this.VpcList;
    }

    /**
     * Set VPC Enumeration
     * @param VpcList VPC Enumeration
     */
    public void setVpcList(FilterDataObject [] VpcList) {
        this.VpcList = VpcList;
    }

    /**
     * Get Region Enumeration 
     * @return RegionList Region Enumeration
     */
    public FilterDataObject [] getRegionList() {
        return this.RegionList;
    }

    /**
     * Set Region Enumeration
     * @param RegionList Region Enumeration
     */
    public void setRegionList(FilterDataObject [] RegionList) {
        this.RegionList = RegionList;
    }

    /**
     * Get Tenant Enumeration 
     * @return AppIdList Tenant Enumeration
     */
    public FilterDataObject [] getAppIdList() {
        return this.AppIdList;
    }

    /**
     * Set Tenant Enumeration
     * @param AppIdList Tenant Enumeration
     */
    public void setAppIdList(FilterDataObject [] AppIdList) {
        this.AppIdList = AppIdList;
    }

    /**
     * Get Cluster protection status enumeration. 
     * @return ProtectStatusList Cluster protection status enumeration.
     */
    public FilterDataObject [] getProtectStatusList() {
        return this.ProtectStatusList;
    }

    /**
     * Set Cluster protection status enumeration.
     * @param ProtectStatusList Cluster protection status enumeration.
     */
    public void setProtectStatusList(FilterDataObject [] ProtectStatusList) {
        this.ProtectStatusList = ProtectStatusList;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeClusterAssetsResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeClusterAssetsResponse(DescribeClusterAssetsResponse source) {
        if (source.Data != null) {
            this.Data = new AssetCluster[source.Data.length];
            for (int i = 0; i < source.Data.length; i++) {
                this.Data[i] = new AssetCluster(source.Data[i]);
            }
        }
        if (source.TotalCount != null) {
            this.TotalCount = new Long(source.TotalCount);
        }
        if (source.ClusterTypeList != null) {
            this.ClusterTypeList = new FilterDataObject[source.ClusterTypeList.length];
            for (int i = 0; i < source.ClusterTypeList.length; i++) {
                this.ClusterTypeList[i] = new FilterDataObject(source.ClusterTypeList[i]);
            }
        }
        if (source.ClusterStatusList != null) {
            this.ClusterStatusList = new FilterDataObject[source.ClusterStatusList.length];
            for (int i = 0; i < source.ClusterStatusList.length; i++) {
                this.ClusterStatusList[i] = new FilterDataObject(source.ClusterStatusList[i]);
            }
        }
        if (source.ComponentStatusList != null) {
            this.ComponentStatusList = new FilterDataObject[source.ComponentStatusList.length];
            for (int i = 0; i < source.ComponentStatusList.length; i++) {
                this.ComponentStatusList[i] = new FilterDataObject(source.ComponentStatusList[i]);
            }
        }
        if (source.VpcList != null) {
            this.VpcList = new FilterDataObject[source.VpcList.length];
            for (int i = 0; i < source.VpcList.length; i++) {
                this.VpcList[i] = new FilterDataObject(source.VpcList[i]);
            }
        }
        if (source.RegionList != null) {
            this.RegionList = new FilterDataObject[source.RegionList.length];
            for (int i = 0; i < source.RegionList.length; i++) {
                this.RegionList[i] = new FilterDataObject(source.RegionList[i]);
            }
        }
        if (source.AppIdList != null) {
            this.AppIdList = new FilterDataObject[source.AppIdList.length];
            for (int i = 0; i < source.AppIdList.length; i++) {
                this.AppIdList[i] = new FilterDataObject(source.AppIdList[i]);
            }
        }
        if (source.ProtectStatusList != null) {
            this.ProtectStatusList = new FilterDataObject[source.ProtectStatusList.length];
            for (int i = 0; i < source.ProtectStatusList.length; i++) {
                this.ProtectStatusList[i] = new FilterDataObject(source.ProtectStatusList[i]);
            }
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamArrayObj(map, prefix + "Data.", this.Data);
        this.setParamSimple(map, prefix + "TotalCount", this.TotalCount);
        this.setParamArrayObj(map, prefix + "ClusterTypeList.", this.ClusterTypeList);
        this.setParamArrayObj(map, prefix + "ClusterStatusList.", this.ClusterStatusList);
        this.setParamArrayObj(map, prefix + "ComponentStatusList.", this.ComponentStatusList);
        this.setParamArrayObj(map, prefix + "VpcList.", this.VpcList);
        this.setParamArrayObj(map, prefix + "RegionList.", this.RegionList);
        this.setParamArrayObj(map, prefix + "AppIdList.", this.AppIdList);
        this.setParamArrayObj(map, prefix + "ProtectStatusList.", this.ProtectStatusList);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

