/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.csip.v20221121.models;

import com.tencentcloudapi.common.AbstractModel;
import com.tencentcloudapi.common.SSEResponseModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class DescribeAgentRunPolicyResponse extends AbstractModel {

    /**
    * <p>Basic running policy</p>
    */
    @SerializedName("BasicPolicy")
    @Expose
    private AgentRunModePolicy BasicPolicy;

    /**
    * <p>Advanced running policy</p>
    */
    @SerializedName("AdvancePolicy")
    @Expose
    private AgentRunModePolicy AdvancePolicy;

    /**
    * <p>Custom running strategy</p>
    */
    @SerializedName("CustomPolicy")
    @Expose
    private AgentRunModePolicy CustomPolicy;

    /**
    * <p>instance id list of machines associated with the custom mode</p>
    */
    @SerializedName("CustomModeInstanceIDs")
    @Expose
    private String [] CustomModeInstanceIDs;

    /**
    * <p>instance id list of machines associated with the advanced mode</p>
    */
    @SerializedName("AdvanceModeInstanceIDs")
    @Expose
    private String [] AdvanceModeInstanceIDs;

    /**
    * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
    */
    @SerializedName("RequestId")
    @Expose
    private String RequestId;

    /**
     * Get <p>Basic running policy</p> 
     * @return BasicPolicy <p>Basic running policy</p>
     */
    public AgentRunModePolicy getBasicPolicy() {
        return this.BasicPolicy;
    }

    /**
     * Set <p>Basic running policy</p>
     * @param BasicPolicy <p>Basic running policy</p>
     */
    public void setBasicPolicy(AgentRunModePolicy BasicPolicy) {
        this.BasicPolicy = BasicPolicy;
    }

    /**
     * Get <p>Advanced running policy</p> 
     * @return AdvancePolicy <p>Advanced running policy</p>
     */
    public AgentRunModePolicy getAdvancePolicy() {
        return this.AdvancePolicy;
    }

    /**
     * Set <p>Advanced running policy</p>
     * @param AdvancePolicy <p>Advanced running policy</p>
     */
    public void setAdvancePolicy(AgentRunModePolicy AdvancePolicy) {
        this.AdvancePolicy = AdvancePolicy;
    }

    /**
     * Get <p>Custom running strategy</p> 
     * @return CustomPolicy <p>Custom running strategy</p>
     */
    public AgentRunModePolicy getCustomPolicy() {
        return this.CustomPolicy;
    }

    /**
     * Set <p>Custom running strategy</p>
     * @param CustomPolicy <p>Custom running strategy</p>
     */
    public void setCustomPolicy(AgentRunModePolicy CustomPolicy) {
        this.CustomPolicy = CustomPolicy;
    }

    /**
     * Get <p>instance id list of machines associated with the custom mode</p> 
     * @return CustomModeInstanceIDs <p>instance id list of machines associated with the custom mode</p>
     */
    public String [] getCustomModeInstanceIDs() {
        return this.CustomModeInstanceIDs;
    }

    /**
     * Set <p>instance id list of machines associated with the custom mode</p>
     * @param CustomModeInstanceIDs <p>instance id list of machines associated with the custom mode</p>
     */
    public void setCustomModeInstanceIDs(String [] CustomModeInstanceIDs) {
        this.CustomModeInstanceIDs = CustomModeInstanceIDs;
    }

    /**
     * Get <p>instance id list of machines associated with the advanced mode</p> 
     * @return AdvanceModeInstanceIDs <p>instance id list of machines associated with the advanced mode</p>
     */
    public String [] getAdvanceModeInstanceIDs() {
        return this.AdvanceModeInstanceIDs;
    }

    /**
     * Set <p>instance id list of machines associated with the advanced mode</p>
     * @param AdvanceModeInstanceIDs <p>instance id list of machines associated with the advanced mode</p>
     */
    public void setAdvanceModeInstanceIDs(String [] AdvanceModeInstanceIDs) {
        this.AdvanceModeInstanceIDs = AdvanceModeInstanceIDs;
    }

    /**
     * Get The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. 
     * @return RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public String getRequestId() {
        return this.RequestId;
    }

    /**
     * Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     * @param RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    public DescribeAgentRunPolicyResponse() {
    }

    /**
     * NOTE: Any ambiguous key set via .set("AnyKey", "value") will be a shallow copy,
     *       and any explicit key, i.e Foo, set via .setFoo("value") will be a deep copy.
     */
    public DescribeAgentRunPolicyResponse(DescribeAgentRunPolicyResponse source) {
        if (source.BasicPolicy != null) {
            this.BasicPolicy = new AgentRunModePolicy(source.BasicPolicy);
        }
        if (source.AdvancePolicy != null) {
            this.AdvancePolicy = new AgentRunModePolicy(source.AdvancePolicy);
        }
        if (source.CustomPolicy != null) {
            this.CustomPolicy = new AgentRunModePolicy(source.CustomPolicy);
        }
        if (source.CustomModeInstanceIDs != null) {
            this.CustomModeInstanceIDs = new String[source.CustomModeInstanceIDs.length];
            for (int i = 0; i < source.CustomModeInstanceIDs.length; i++) {
                this.CustomModeInstanceIDs[i] = new String(source.CustomModeInstanceIDs[i]);
            }
        }
        if (source.AdvanceModeInstanceIDs != null) {
            this.AdvanceModeInstanceIDs = new String[source.AdvanceModeInstanceIDs.length];
            for (int i = 0; i < source.AdvanceModeInstanceIDs.length; i++) {
                this.AdvanceModeInstanceIDs[i] = new String(source.AdvanceModeInstanceIDs[i]);
            }
        }
        if (source.RequestId != null) {
            this.RequestId = new String(source.RequestId);
        }
    }


    /**
     * Internal implementation, normal users should not use it.
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamObj(map, prefix + "BasicPolicy.", this.BasicPolicy);
        this.setParamObj(map, prefix + "AdvancePolicy.", this.AdvancePolicy);
        this.setParamObj(map, prefix + "CustomPolicy.", this.CustomPolicy);
        this.setParamArraySimple(map, prefix + "CustomModeInstanceIDs.", this.CustomModeInstanceIDs);
        this.setParamArraySimple(map, prefix + "AdvanceModeInstanceIDs.", this.AdvanceModeInstanceIDs);
        this.setParamSimple(map, prefix + "RequestId", this.RequestId);

    }
}

